import * as THREE from 'https://esm.sh/three@0.180.0';
import { GLTFLoader } from 'https://esm.sh/three@0.180.0/examples/jsm/loaders/GLTFLoader.js';

const SB_URL='https://rliymfbbhqoejgfvsbuu.supabase.co';
const SB_KEY='sb_publishable_E4go4X7yZ6d-aXnKAT-fWw_Y8uHIJT0';
const MODEL_URL='https://raw.githubusercontent.com/nirholas/three.ws/main/public/avatars/parametric-base.glb';
const sb=window.supabase.createClient(SB_URL,SB_KEY);
const $=id=>document.getElementById(id);
const state={version:7,style:'zuno-glb-parametric',body:'male',skin:'#e7b18b',hair:'#17151a',eyes:'#4ba3c7',top:'tee',bottom:'shorts',shoes:'sneaker',accent:'#9b5cff',head:'none',face:'none',neck:'none',back:'none',morphs:{}};
const COLORS={skin:['#f4d1b8','#e7b18b','#cb8b63','#a76849','#79503a','#4d3226'],hair:['#17151a','#3a271f','#6b4634','#c18a43','#ddd9d2','#6c3a87'],eyes:['#493229','#4ba3c7','#4db37b','#8b5cf6','#76869a','#d05b94'],accent:['#9b5cff','#6366f1','#38bdf8','#22d3ee','#ec4899','#f59e0b']};
const OPT={body:[['male','Masculino'],['female','Feminino'],['slim','Slim'],['athletic','Atlético']],top:[['tee','Camiseta'],['hoodie','Hoodie'],['jacket','Jaqueta']],bottom:[['shorts','Short'],['jeans','Jeans'],['cargo','Cargo']],shoes:[['sneaker','Tênis'],['high','Cano alto'],['boot','Bota']],head:[['none','Nenhum'],['cap','Boné'],['headphones','Fones']],face:[['none','Nenhum'],['glasses','Óculos'],['mask','Máscara']],neck:[['none','Nenhum'],['chain','Corrente']],back:[['none','Nenhum'],['backpack','Mochila']]};
let renderer,scene,camera,pivot,model,wardrobe,morphTargets=[],drag=false,lastX=0,targetRot=0,currentRot=0;

function initScene(){const viewer=$('viewer');scene=new THREE.Scene();scene.background=new THREE.Color('#dce8f7');camera=new THREE.PerspectiveCamera(29,viewer.clientWidth/viewer.clientHeight,.01,100);camera.position.set(0,1.62,5.2);renderer=new THREE.WebGLRenderer({antialias:true,alpha:false,preserveDrawingBuffer:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setSize(viewer.clientWidth,viewer.clientHeight);renderer.shadowMap.enabled=true;renderer.outputColorSpace=THREE.SRGBColorSpace;viewer.replaceChildren(renderer.domElement);scene.add(new THREE.HemisphereLight(0xffffff,0x6b7280,2.25));const key=new THREE.DirectionalLight(0xffffff,3.2);key.position.set(3,5,4);key.castShadow=true;scene.add(key);const rim=new THREE.DirectionalLight(0x9b5cff,2.0);rim.position.set(-4,3,-2);scene.add(rim);const ground=new THREE.Mesh(new THREE.CircleGeometry(2.4,64),new THREE.MeshStandardMaterial({color:0xd7e4f5,roughness:1}));ground.rotation.x=-Math.PI/2;ground.receiveShadow=true;scene.add(ground);pivot=new THREE.Group();scene.add(pivot);wardrobe=new THREE.Group();pivot.add(wardrobe);bindDrag(viewer);addEventListener('resize',resize);animate();}
function resize(){const v=$('viewer');if(!renderer||!v)return;camera.aspect=v.clientWidth/v.clientHeight;camera.updateProjectionMatrix();renderer.setSize(v.clientWidth,v.clientHeight);}
function bindDrag(v){v.addEventListener('pointerdown',e=>{drag=true;lastX=e.clientX;v.setPointerCapture?.(e.pointerId)});v.addEventListener('pointermove',e=>{if(!drag)return;targetRot+=(e.clientX-lastX)*.012;lastX=e.clientX});v.addEventListener('pointerup',()=>drag=false);v.addEventListener('pointercancel',()=>drag=false)}
function animate(){requestAnimationFrame(animate);currentRot+=(targetRot-currentRot)*.12;if(pivot)pivot.rotation.y=currentRot;renderer?.render(scene,camera)}
function fitModel(root){const box=new THREE.Box3().setFromObject(root),size=new THREE.Vector3(),center=new THREE.Vector3();box.getSize(size);box.getCenter(center);const targetH=3.45,scale=targetH/Math.max(size.y,.001);root.scale.setScalar(scale);root.updateMatrixWorld(true);const box2=new THREE.Box3().setFromObject(root);root.position.y-=box2.min.y;const box3=new THREE.Box3().setFromObject(root);box3.getCenter(center);root.position.x-=center.x;root.position.z-=center.z;}
function discoverMorphs(){morphTargets=[];model?.traverse(o=>{if(o.isMesh&&o.morphTargetDictionary&&o.morphTargetInfluences){for(const [name,index] of Object.entries(o.morphTargetDictionary)){if(!morphTargets.some(m=>m.name===name))morphTargets.push({name,index,meshes:[]});}for(const m of morphTargets){if(o.morphTargetDictionary[m.name]!=null)m.meshes.push({mesh:o,index:o.morphTargetDictionary[m.name]});}}});}
function applyMorphs(){for(const m of morphTargets){const v=Number(state.morphs[m.name]||0);for(const x of m.meshes)x.mesh.morphTargetInfluences[x.index]=v;}}
function applyBody(){if(!model)return;const sx=state.body==='athletic'?1.08:state.body==='slim'?.93:state.body==='female'?.97:1;const sz=state.body==='athletic'?1.05:state.body==='slim'?.95:1;pivot.scale.set(sx,1,sz);const candidates={female:['female','gender-female','macrodetails-female'],male:['male','gender-male','macrodetails-male'],slim:['weight','thin','slim'],athletic:['muscle','athletic']};for(const m of morphTargets){const n=m.name.toLowerCase();let v=0;if((candidates[state.body]||[]).some(k=>n.includes(k)))v=.75;state.morphs[m.name]=v;}applyMorphs();buildWardrobe();}
function tintSkin(){if(!model)return;model.traverse(o=>{if(!o.isMesh)return;const mats=Array.isArray(o.material)?o.material:[o.material];for(let i=0;i<mats.length;i++){const old=mats[i];if(!old)continue;const name=(old.name||o.name||'').toLowerCase();if(/skin|body|human|base/.test(name)&&old.color){const clone=old.clone();clone.color.set(state.skin);clone.needsUpdate=true;if(Array.isArray(o.material)){const a=[...o.material];a[i]=clone;o.material=a}else o.material=clone;}}});}
function mesh(geo,color,pos,scale=[1,1,1],rot=[0,0,0],metal=.05){const m=new THREE.Mesh(geo,new THREE.MeshStandardMaterial({color,roughness:.65,metalness:metal}));m.position.set(...pos);m.scale.set(...scale);m.rotation.set(...rot);m.castShadow=true;wardrobe.add(m);return m}
function clearWardrobe(){while(wardrobe.children.length)wardrobe.remove(wardrobe.children[0]);}
function buildWardrobe(){if(!wardrobe)return;clearWardrobe();const a=state.accent, dark='#20232c';
 if(state.top==='tee')mesh(new THREE.CylinderGeometry(.58,.48,.92,32),0xf7f7f7,[0,2.35,0],[1,1,.62]);
 if(state.top==='hoodie'){mesh(new THREE.CylinderGeometry(.63,.52,1.02,32),0x20232c,[0,2.35,0],[1,1,.66]);mesh(new THREE.TorusGeometry(.34,.09,16,32,Math.PI),a,[0,2.78,-.18],[1,1,1],[0,0,Math.PI]);}
 if(state.top==='jacket'){mesh(new THREE.CylinderGeometry(.66,.54,1.02,32),0x161a22,[0,2.35,0],[1,1,.68]);mesh(new THREE.BoxGeometry(.08,.82,.04),a,[0,2.35,.43]);}
 if(state.bottom==='shorts')mesh(new THREE.CylinderGeometry(.48,.5,.62,32),0x282b32,[0,1.55,0],[1,1,.72]);
 if(state.bottom==='jeans')mesh(new THREE.CylinderGeometry(.47,.43,.88,32),0x283544,[0,1.42,0],[1,1,.7]);
 if(state.bottom==='cargo')mesh(new THREE.CylinderGeometry(.5,.46,.9,32),0x1b2028,[0,1.43,0],[1,1,.72]);
 const shoeY=.12, shoeGeo=new THREE.BoxGeometry(.42,.25,.72);mesh(shoeGeo,0xf2f2f2,[-.24,shoeY,.12],[1,1,1],[0,0,0]);mesh(shoeGeo,0xf2f2f2,[.24,shoeY,.12]);
 if(state.head==='cap'){mesh(new THREE.SphereGeometry(.42,32,16,0,Math.PI*2,0,Math.PI/2),0x171a22,[0,3.34,0],[1,1,.9]);mesh(new THREE.BoxGeometry(.5,.05,.35),dark,[0,3.28,.34]);}
 if(state.head==='headphones'){const t=mesh(new THREE.TorusGeometry(.49,.08,16,48,Math.PI),0x191d27,[0,3.16,0],[1,1,1],[0,0,Math.PI]);t.material.metalness=.3;}
 if(state.face==='glasses'){mesh(new THREE.TorusGeometry(.16,.018,10,24),0xd8dbe2,[-.17,3.05,.35],[1,.7,1]);mesh(new THREE.TorusGeometry(.16,.018,10,24),0xd8dbe2,[.17,3.05,.35],[1,.7,1]);mesh(new THREE.BoxGeometry(.12,.018,.02),0xd8dbe2,[0,3.05,.35]);}
 if(state.face==='mask')mesh(new THREE.BoxGeometry(.55,.25,.12),0x151922,[0,2.89,.36],[1,1,1]);
 if(state.neck==='chain'){const c=mesh(new THREE.TorusGeometry(.24,.018,10,40),0xcfd3da,[0,2.68,.28],[1,.7,1],[Math.PI/2,0,0],.7);c.material.metalness=.8;}
 if(state.back==='backpack')mesh(new THREE.BoxGeometry(.72,.9,.32),0x191d26,[0,2.18,-.47],[1,1,1]);
}
async function loadModel(){const status=$('modelStatus');status.textContent='Carregando corpo GLB...';try{const gltf=await new GLTFLoader().loadAsync(MODEL_URL);model=gltf.scene;model.traverse(o=>{if(o.isMesh){o.castShadow=true;o.receiveShadow=true;}});fitModel(model);pivot.add(model);discoverMorphs();tintSkin();applyBody();status.textContent=`Base GLB carregada · ${morphTargets.length} morph targets`;status.className='status ok';buildMorphUI();}catch(err){console.error(err);status.textContent='GLB indisponível. Usando fallback 3D atual.';status.className='status err';await import('./avatar-3d-v54.js?v=54');}}
function btnGroup(title,key,items){const d=document.createElement('div');d.className='group';d.innerHTML=`<h3>${title}</h3><div class="options"></div>`;const box=d.lastElementChild;for(const [v,l] of items){const b=document.createElement('button');b.className='opt'+(state[key]===v?' active':'');b.textContent=l;b.onclick=()=>{state[key]=v;renderUI();if(key==='body')applyBody();else buildWardrobe();};box.appendChild(b)}return d}
function colorGroup(title,key,items){const d=document.createElement('div');d.className='group';d.innerHTML=`<h3>${title}</h3><div class="options colors"></div>`;const box=d.lastElementChild;for(const c of items){const b=document.createElement('button');b.className='color'+(state[key]===c?' active':'');b.innerHTML=`<i style="background:${c}"></i>`;b.onclick=()=>{state[key]=c;renderUI();if(key==='skin')tintSkin();else buildWardrobe();};box.appendChild(b)}return d}
function buildMorphUI(){const root=$('morphPanel');root.innerHTML='';const preferred=morphTargets.filter(m=>/height|weight|muscle|breast|waist|hip|head|face|nose|mouth|eye/i.test(m.name)).slice(0,10);for(const m of preferred){const row=document.createElement('label');row.className='sliderRow';const v=state.morphs[m.name]||0;row.innerHTML=`<span>${m.name}</span><input type="range" min="-1" max="1" step="0.05" value="${v}">`;row.querySelector('input').oninput=e=>{state.morphs[m.name]=Number(e.target.value);applyMorphs()};root.appendChild(row)}}
function renderUI(){const p=$('panels');p.innerHTML='';p.append(btnGroup('Tipo de corpo','body',OPT.body),colorGroup('Tom de pele','skin',COLORS.skin),btnGroup('Parte de cima','top',OPT.top),btnGroup('Parte de baixo','bottom',OPT.bottom),btnGroup('Calçados','shoes',OPT.shoes),btnGroup('Cabeça','head',OPT.head),btnGroup('Rosto','face',OPT.face),btnGroup('Pescoço','neck',OPT.neck),btnGroup('Costas','back',OPT.back),colorGroup('Cor Zuno','accent',COLORS.accent));}
async function restore(){const {data:{user}}=await sb.auth.getUser();if(!user)return;const {data}=await sb.from('profiles').select('avatar_config').eq('id',user.id).maybeSingle();if(data?.avatar_config?.style==='zuno-glb-parametric'){Object.assign(state,data.avatar_config);renderUI();if(model){tintSkin();applyBody();applyMorphs();}}}
async function save(){const b=$('save'),msg=$('msg');b.disabled=true;msg.className='msg';msg.textContent='Salvando...';try{const {data:{user},error:u}=await sb.auth.getUser();if(u||!user)throw new Error('Sessão inválida');renderer.render(scene,camera);const png=renderer.domElement.toDataURL('image/png',.92);const cfg={...state,updatedAt:new Date().toISOString(),modelSource:'MakeHuman/MPFB2 CC0 via three.ws'};const sex=state.body==='female'?'feminino':'masculino';const {error}=await sb.from('profiles').update({avatar_config:cfg,avatar_url:png,sex}).eq('id',user.id);if(error)throw error;msg.textContent='Personagem 3D salvo! ✅';}catch(e){console.error(e);msg.className='msg err';msg.textContent='Erro: '+(e.message||'não foi possível salvar')}finally{b.disabled=false}}

initScene();renderUI();restore().catch(console.warn);loadModel().catch(console.error);$('save').onclick=save;
