(()=>{
'use strict';
const SB_URL='https://rliymfbbhqoejgfvsbuu.supabase.co';
const SB_KEY='sb_publishable_E4go4X7yZ6d-aXnKAT-fWw_Y8uHIJT0';
const sb=window.supabase.createClient(SB_URL,SB_KEY);
const $=id=>document.getElementById(id);
const state={version:6,style:'zuno-webgl-3d',body:'male',skin:'#e7b18b',hair:'#17151a',eyes:'#4ba3c7',hairStyle:'short',top:'tee',bottom:'shorts',shoes:'sneaker',head:'none',face:'none',neck:'none',wrist:'none',back:'none',accent:'#9b5cff'};
const COLORS={skin:['#f4d1b8','#e7b18b','#cb8b63','#a76849','#79503a','#4d3226'],hair:['#17151a','#3a271f','#6b4634','#c18a43','#ddd9d2','#6c3a87','#2d456c','#8b3859'],eyes:['#493229','#4ba3c7','#4db37b','#8b5cf6','#76869a','#d05b94','#38b9b0'],accent:['#9b5cff','#6366f1','#38bdf8','#22d3ee','#ec4899','#f43f5e','#f59e0b','#4ade80']};
const OPTIONS={body:[['male','Masculino'],['female','Feminino'],['slim','Slim'],['athletic','Atlético']],hairStyle:[['short','Curto'],['spike','Espetado'],['wave','Ondulado'],['bob','Chanel'],['long','Longo'],['pony','Rabo alto']],top:[['tee','Camiseta'],['hoodie','Hoodie'],['jacket','Jaqueta'],['crop','Cropped']],bottom:[['shorts','Short'],['jeans','Jeans'],['cargo','Cargo'],['skirt','Saia']],shoes:[['sneaker','Tênis'],['high','Cano alto'],['boot','Bota']],head:[['none','Nenhum'],['cap','Boné'],['headphones','Fones']],face:[['none','Nenhum'],['glasses','Óculos'],['mask','Máscara']],neck:[['none','Nenhum'],['chain','Corrente']],wrist:[['none','Nenhum'],['watch','Relógio']],back:[['none','Nenhum'],['backpack','Mochila']]};
let renderer,scene,camera,avatar,ground,keyLight,fillLight,rimLight;
let dragging=false,lastX=0,targetRot=0,currentRot=0;
function mat(color,rough=.7,metal=.05){return new THREE.MeshStandardMaterial({color,roughness:rough,metalness:metal});}
function roundedBox(w,h,d,r=0.12,segments=4){const shape=new THREE.Shape();const x=-w/2,y=-h/2;shape.moveTo(x+r,y);shape.lineTo(x+w-r,y);shape.quadraticCurveTo(x+w,y,x+w,y+r);shape.lineTo(x+w,y+h-r);shape.quadraticCurveTo(x+w,y+h,x+w-r,y+h);shape.lineTo(x+r,y+h);shape.quadraticCurveTo(x,y+h,x,y+h-r);shape.lineTo(x,y+r);shape.quadraticCurveTo(x,y,x+r,y);const geo=new THREE.ExtrudeGeometry(shape,{depth:d,bevelEnabled:true,bevelSize:r*.45,bevelThickness:r*.45,bevelSegments:segments,steps:1});geo.center();return geo;}
function mesh(geo,material,name){const m=new THREE.Mesh(geo,material);m.name=name||'';m.castShadow=true;m.receiveShadow=true;return m;}
function group(name){const g=new THREE.Group();g.name=name;return g;}
function clearAvatar(){if(avatar){scene.remove(avatar);avatar.traverse(o=>{if(o.geometry)o.geometry.dispose();if(o.material&&o.material.dispose)o.material.dispose()});}}
function limb(radius,length,material){return mesh(new THREE.CapsuleGeometry(radius,length,8,18),material);}
function addHair(g,headY){const m=mat(state.hair,.78,.02);const add=(x,y,z,sx,sy,sz,rx=0,rz=0)=>{const h=mesh(new THREE.SphereGeometry(.24,22,16),m,'hair');h.position.set(x,y,z);h.scale.set(sx,sy,sz);h.rotation.x=rx;h.rotation.z=rz;g.add(h)};
 if(state.hairStyle==='short'){add(0,headY+.2,-.01,1.08,.62,1.03);add(-.16,headY+.22,.03,.6,.56,.86,0,.35);add(.16,headY+.23,.02,.65,.58,.9,0,-.35)}
 else if(state.hairStyle==='spike'){for(let i=0;i<7;i++){const a=(i/6-.5)*1.0;add(Math.sin(a)*.18,headY+.25+Math.cos(a)*.03,-.01,.45,.95,.42,0,-a)}}
 else if(state.hairStyle==='wave'){add(0,headY+.19,-.02,1.1,.72,1.05);for(let i=0;i<4;i++)add((i-1.5)*.11,headY+.2,(i%2)*.025,.58,.62,.62,0,(i-1.5)*.2)}
 else if(state.hairStyle==='bob'){add(0,headY+.08,-.01,1.16,1.0,1.05);const cut=mesh(new THREE.BoxGeometry(.7,.24,.56),mat(state.skin), 'haircut');cut.position.set(0,headY-.03,.08);g.add(cut)}
 else if(state.hairStyle==='long'){add(0,headY+.1,-.08,1.12,1.4,1.02);const back=mesh(new THREE.CapsuleGeometry(.24,.72,8,18),m,'hair');back.position.set(0,headY-.42,-.12);back.scale.x=1.55;g.add(back)}
 else {add(0,headY+.14,-.02,1.08,.78,1.0);const pony=mesh(new THREE.CapsuleGeometry(.12,.45,8,14),m,'hair');pony.position.set(.27,headY-.05,-.14);pony.rotation.z=-.55;g.add(pony)}}
function addFace(g,headY){const eyeMat=mat(state.eyes,.35,.05),white=mat('#f7fbff',.4,0),dark=mat('#171820',.55,.05);[-.105,.105].forEach(x=>{const w=mesh(new THREE.SphereGeometry(.055,18,12),white,'eyeWhite');w.scale.set(1.25,.72,.35);w.position.set(x,headY+.015,.235);g.add(w);const e=mesh(new THREE.SphereGeometry(.029,16,10),eyeMat,'iris');e.position.set(x,headY+.013,.278);g.add(e);const p=mesh(new THREE.SphereGeometry(.012,12,8),dark,'pupil');p.position.set(x,headY+.012,.301);g.add(p)});const nose=mesh(new THREE.ConeGeometry(.026,.075,12),mat(state.skin,.65,0),'nose');nose.rotation.x=Math.PI/2;nose.position.set(0,headY-.045,.285);g.add(nose);const mouth=mesh(new THREE.TorusGeometry(.065,.008,8,28,Math.PI),mat('#b85f72',.6,0),'mouth');mouth.rotation.z=Math.PI;mouth.position.set(0,headY-.12,.29);g.add(mouth);if(state.face==='glasses'){[-.11,.11].forEach(x=>{const lens=mesh(new THREE.TorusGeometry(.072,.008,8,24),mat('#dbe4f1',.25,.25),'glasses');lens.position.set(x,headY+.02,.305);g.add(lens)});const bridge=mesh(new THREE.BoxGeometry(.07,.012,.012),mat('#dbe4f1',.25,.3),'glasses');bridge.position.set(0,headY+.02,.31);g.add(bridge)}if(state.face==='mask'){const mask=mesh(new THREE.SphereGeometry(.19,22,16,0,Math.PI*2,Math.PI*.44,Math.PI*.42),mat('#191b24',.5,.1),'mask');mask.scale.set(1,.55,.52);mask.position.set(0,headY-.11,.17);g.add(mask)}}
function addClothes(g,dims){const accent=mat(state.accent,.4,.18),black=mat('#171820',.62,.08),white=mat('#f5f6f8',.76,.01),denim=mat('#273240',.82,.02);let topMat=state.top==='tee'?white:black;if(state.top==='crop')topMat=mat('#22232d',.62,.05);const torso=mesh(roundedBox(dims.shoulder,.62,.32,.12),topMat,'top');torso.position.y=1.46;g.add(torso);if(state.top==='hoodie'){const hood=mesh(new THREE.TorusGeometry(.25,.07,10,28,Math.PI*1.25),black,'hood');hood.position.set(0,1.72,-.06);hood.rotation.x=Math.PI/2;g.add(hood)}if(state.top==='jacket'){const left=mesh(roundedBox(dims.shoulder*.49,.62,.34,.1),black,'jacket');left.position.set(-dims.shoulder*.255,1.46,.015);g.add(left);const right=left.clone();right.position.x*=-1;g.add(right);const zip=mesh(new THREE.BoxGeometry(.018,.5,.36),accent,'zip');zip.position.set(0,1.45,.02);g.add(zip)}if(state.top==='crop'){torso.scale.y=.72;torso.position.y=1.55}const z=mesh(new THREE.TorusGeometry(.09,.018,8,32),accent,'logo');z.position.set(.18,1.52,.18);z.rotation.x=Math.PI/2;g.add(z);const legMat=state.bottom==='jeans'?denim:black;if(state.bottom==='skirt'){const skirt=mesh(new THREE.CylinderGeometry(.34,.45,.42,28,1,true),legMat,'bottom');skirt.position.y=.95;g.add(skirt)}else{[-.17,.17].forEach(x=>{const len=state.bottom==='shorts'?.42:.78;const l=limb(.14,len,legMat);l.position.set(x,1.04-(len-.42)/2,0);g.add(l)})}[-.17,.17].forEach(x=>{const lower=limb(.115,.66,mat(state.skin,.72,0));lower.position.set(x,.38,0);if(state.bottom!=='shorts'){lower.material=legMat}g.add(lower);const shoeMat=mat('#d9dadd',.48,.12);const shoe=mesh(roundedBox(.28,.16,.48,.06),shoeMat,'shoes');shoe.position.set(x,.02,.09);if(state.shoes==='high')shoe.scale.y=1.8;if(state.shoes==='boot'){shoe.material=black;shoe.scale.y=2.2}g.add(shoe);const sole=mesh(new THREE.BoxGeometry(.3,.045,.5),accent,'sole');sole.position.set(x,-.07,.09);g.add(sole)})}
function addAccessories(g){const accent=mat(state.accent,.35,.25),dark=mat('#171820',.55,.12);if(state.head==='cap'){const cap=mesh(new THREE.SphereGeometry(.27,24,16,0,Math.PI*2,0,Math.PI/2),dark,'cap');cap.position.set(0,2.15,0);cap.scale.y=.58;g.add(cap);const brim=mesh(new THREE.BoxGeometry(.32,.035,.16),dark,'cap');brim.position.set(0,2.12,.26);g.add(brim)}if(state.head==='headphones'){const band=mesh(new THREE.TorusGeometry(.28,.035,10,32,Math.PI),dark,'headphones');band.position.set(0,2.09,0);g.add(band);[-.27,.27].forEach(x=>{const ear=mesh(new THREE.CylinderGeometry(.075,.075,.06,20),accent,'headphones');ear.rotation.z=Math.PI/2;ear.position.set(x,1.98,0);g.add(ear)})}if(state.neck==='chain'){const chain=mesh(new THREE.TorusGeometry(.16,.012,8,40,Math.PI*1.3),mat('#cbd1dc',.25,.55),'chain');chain.rotation.x=Math.PI/2;chain.rotation.z=-.48;chain.position.set(0,1.72,.13);g.add(chain)}if(state.wrist==='watch'){const watch=mesh(new THREE.BoxGeometry(.075,.06,.055),accent,'watch');watch.position.set(-.48,1.25,.04);g.add(watch)}if(state.back==='backpack'){const pack=mesh(roundedBox(.48,.58,.2,.1),dark,'backpack');pack.position.set(0,1.42,-.25);g.add(pack)}}
function buildAvatar(){clearAvatar();avatar=group('avatar');const male=state.body==='male'||state.body==='athletic',slim=state.body==='slim',ath=state.body==='athletic';const shoulder=ath?.88:slim?.66:male?.78:.7;const dims={shoulder};const skinMat=mat(state.skin,.72,.01);const torsoBase=mesh(new THREE.CapsuleGeometry(.28,.58,8,20),skinMat,'body');torsoBase.position.y=1.48;torsoBase.scale.x=male?1.05:.94;avatar.add(torsoBase);[-1,1].forEach(side=>{const arm=limb(.105,.68,skinMat);arm.position.set(side*(shoulder/2+.08),1.35,0);avatar.add(arm);const hand=mesh(new THREE.SphereGeometry(.115,18,14),skinMat,'hand');hand.scale.y=1.25;hand.position.set(side*(shoulder/2+.11),.94,.01);avatar.add(hand)});const neck=limb(.12,.12,skinMat);neck.position.y=1.82;avatar.add(neck);const headY=2.08;const head=mesh(new THREE.SphereGeometry(.28,32,24),skinMat,'head');head.scale.set(male?0.94:.9,1.08,.92);head.position.y=headY;avatar.add(head);addHair(avatar,headY);addFace(avatar,headY);addClothes(avatar,dims);addAccessories(avatar);avatar.scale.setScalar(state.body==='slim'?.95:state.body==='athletic'?1.04:1);scene.add(avatar)}
function init3d(){const host=$('viewer');renderer=new THREE.WebGLRenderer({antialias:true,alpha:true,preserveDrawingBuffer:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.08;host.appendChild(renderer.domElement);scene=new THREE.Scene();scene.background=new THREE.Color(0xdde8fb);scene.fog=new THREE.Fog(0xdde8fb,5.5,9);camera=new THREE.PerspectiveCamera(28,1,.1,30);camera.position.set(0,1.25,6.4);camera.lookAt(0,1.15,0);keyLight=new THREE.DirectionalLight(0xffffff,3.2);keyLight.position.set(3.5,5,4);keyLight.castShadow=true;keyLight.shadow.mapSize.set(1024,1024);scene.add(keyLight);fillLight=new THREE.HemisphereLight(0xcfe6ff,0x63728e,2.2);scene.add(fillLight);rimLight=new THREE.DirectionalLight(0xb296ff,1.8);rimLight.position.set(-4,2,-3);scene.add(rimLight);ground=mesh(new THREE.CircleGeometry(2.1,64),new THREE.MeshStandardMaterial({color:0xcfdcf0,roughness:.7,metalness:.05,transparent:true,opacity:.82}),'ground');ground.rotation.x=-Math.PI/2;ground.position.y=-.11;scene.add(ground);buildAvatar();resize();animate();host.addEventListener('pointerdown',e=>{dragging=true;lastX=e.clientX;host.setPointerCapture(e.pointerId)});host.addEventListener('pointermove',e=>{if(!dragging)return;targetRot+=(e.clientX-lastX)*.012;lastX=e.clientX});host.addEventListener('pointerup',()=>dragging=false);window.addEventListener('resize',resize)}
function resize(){const r=$('viewer').getBoundingClientRect();renderer.setSize(Math.max(1,r.width),Math.max(1,r.height),false);camera.aspect=r.width/r.height;camera.updateProjectionMatrix()}
function animate(){requestAnimationFrame(animate);currentRot+=(targetRot-currentRot)*.08;if(avatar)avatar.rotation.y=currentRot;renderer.render(scene,camera)}
function optionButton(key,value,label){const b=document.createElement('button');b.className='opt'+(state[key]===value?' active':'');b.textContent=label;b.onclick=()=>{state[key]=value;renderUI();buildAvatar()};return b}
function colorButton(key,value){const b=document.createElement('button');b.className='color'+(state[key]===value?' active':'');const i=document.createElement('i');i.style.background=value;b.appendChild(i);b.onclick=()=>{state[key]=value;renderUI();buildAvatar()};return b}
function section(title,key,items,color=false){const wrap=document.createElement('section');wrap.className='group';const h=document.createElement('h3');h.textContent=title;wrap.appendChild(h);const box=document.createElement('div');box.className=color?'options colors':'options';items.forEach(item=>box.appendChild(color?colorButton(key,item):optionButton(key,item[0],item[1])));wrap.appendChild(box);return wrap}
function renderUI(){const panels=$('panels');panels.innerHTML='';panels.append(section('Tipo de corpo','body',OPTIONS.body));panels.append(section('Tom de pele','skin',COLORS.skin,true));panels.append(section('Cabelo','hairStyle',OPTIONS.hairStyle));panels.append(section('Cor do cabelo','hair',COLORS.hair,true));panels.append(section('Cor dos olhos','eyes',COLORS.eyes,true));panels.append(section('Parte de cima','top',OPTIONS.top));panels.append(section('Parte de baixo','bottom',OPTIONS.bottom));panels.append(section('Calçados','shoes',OPTIONS.shoes));panels.append(section('Acessório de cabeça','head',OPTIONS.head));panels.append(section('Acessório facial','face',OPTIONS.face));panels.append(section('Pescoço','neck',OPTIONS.neck));panels.append(section('Pulso','wrist',OPTIONS.wrist));panels.append(section('Costas','back',OPTIONS.back));panels.append(section('Cor Zuno','accent',COLORS.accent,true))}
async function load(){const{data:{user},error}=await sb.auth.getUser();if(error||!user){location.href='login.html?next=avatar.html';return}const{data}=await sb.from('profiles').select('avatar_config').eq('id',user.id).maybeSingle();if(data?.avatar_config?.style==='zuno-webgl-3d')Object.assign(state,data.avatar_config);renderUI();buildAvatar()}
async function save(){const btn=$('save'),msg=$('msg');btn.disabled=true;msg.className='msg';msg.textContent='Salvando...';try{const{data:{user},error}=await sb.auth.getUser();if(error||!user)throw new Error('Sessão inválida');currentRot=0;targetRot=0;renderer.render(scene,camera);const png=renderer.domElement.toDataURL('image/png',.92);if(png.length>95000)throw new Error('Prévia ficou grande demais.');const cfg={...state,updatedAt:new Date().toISOString()};const sex=state.body==='female'?'feminino':'masculino';const r=await sb.from('profiles').update({avatar_config:cfg,avatar_url:png,sex}).eq('id',user.id);if(r.error)throw r.error;msg.textContent='Personagem 3D salvo ✅';window.dispatchEvent(new CustomEvent('zuno:avatar-saved',{detail:cfg}))}catch(e){console.error(e);msg.className='msg err';msg.textContent='Erro: '+(e.message||'não foi possível salvar')}finally{btn.disabled=false}}
window.addEventListener('DOMContentLoaded',()=>{if(!window.THREE){$('msg').className='msg err';$('msg').textContent='Falha ao carregar o motor 3D.';return}renderUI();init3d();load().catch(console.error);$('save').onclick=save});
})();