import * as THREE from 'https://esm.sh/three@0.180.0';
import {GLTFLoader} from 'https://esm.sh/three@0.180.0/examples/jsm/loaders/GLTFLoader.js';

const sb=window.supabase.createClient('https://rliymfbbhqoejgfvsbuu.supabase.co','sb_publishable_E4go4X7yZ6d-aXnKAT-fWw_Y8uHIJT0');
const MODEL='https://raw.githubusercontent.com/nirholas/three.ws/main/public/avatars/parametric-base.glb';
const $=id=>document.getElementById(id);
const COLORS={skin:['#f4d1b8','#e7b18b','#cb8b63','#a76849','#79503a','#4d3226']};
const BODIES=[['male','Masculino'],['female','Feminino'],['slim','Slim'],['athletic','Atlético']];
const state={version:11,style:'zuno-glb-parametric',body:'male',skin:'#e7b18b',top:'none',bottom:'none',shoes:'none',head:'none',face:'none',neck:'none',back:'none',morphs:{}};
let renderer,scene,camera,pivot,model,morphs=[],drag=false,lastX=0,targetRot=0,currentRot=0;

function init(){const v=$('viewer');scene=new THREE.Scene();scene.background=new THREE.Color(0xdce8f7);camera=new THREE.PerspectiveCamera(30,v.clientWidth/v.clientHeight,.01,100);renderer=new THREE.WebGLRenderer({antialias:true,preserveDrawingBuffer:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setSize(v.clientWidth,v.clientHeight);renderer.shadowMap.enabled=true;renderer.outputColorSpace=THREE.SRGBColorSpace;v.replaceChildren(renderer.domElement);scene.add(new THREE.HemisphereLight(0xffffff,0x64748b,2.15));const key=new THREE.DirectionalLight(0xffffff,3.1);key.position.set(3,5,4);key.castShadow=true;scene.add(key);const rim=new THREE.DirectionalLight(0x9b5cff,1.5);rim.position.set(-4,3,-2);scene.add(rim);pivot=new THREE.Group();scene.add(pivot);v.addEventListener('pointerdown',e=>{drag=true;lastX=e.clientX;v.setPointerCapture?.(e.pointerId)});v.addEventListener('pointermove',e=>{if(!drag)return;targetRot+=(e.clientX-lastX)*.012;lastX=e.clientX});v.addEventListener('pointerup',()=>drag=false);v.addEventListener('pointercancel',()=>drag=false);addEventListener('resize',()=>{camera.aspect=v.clientWidth/v.clientHeight;camera.updateProjectionMatrix();renderer.setSize(v.clientWidth,v.clientHeight);frameModel()});loop()}
function loop(){requestAnimationFrame(loop);currentRot+=(targetRot-currentRot)*.12;pivot.rotation.y=currentRot;renderer.render(scene,camera)}
function normalizeModel(root){const b=new THREE.Box3().setFromObject(root),s=new THREE.Vector3(),c=new THREE.Vector3();b.getSize(s);root.scale.setScalar(3.45/Math.max(s.y,.001));root.updateMatrixWorld(true);let b2=new THREE.Box3().setFromObject(root);root.position.y-=b2.min.y;root.updateMatrixWorld(true);b2=new THREE.Box3().setFromObject(root);b2.getCenter(c);root.position.x-=c.x;root.position.z-=c.z;root.updateMatrixWorld(true)}
function frameModel(){if(!model)return;const box=new THREE.Box3().setFromObject(pivot),size=new THREE.Vector3(),center=new THREE.Vector3();box.getSize(size);box.getCenter(center);const fov=THREE.MathUtils.degToRad(camera.fov),aspect=Math.max(camera.aspect,.5);const distV=(size.y*.5)/Math.tan(fov*.5),distH=(size.x*.5)/(Math.tan(fov*.5)*aspect);const dist=Math.max(distV,distH)*1.18;camera.position.set(0,center.y,dist);camera.lookAt(center.x,center.y,center.z);camera.near=Math.max(.01,dist-size.z*2);camera.far=dist+size.z*4+20;camera.updateProjectionMatrix()}
function scanMorphs(){morphs=[];model.traverse(o=>{if(!o.isMesh||!o.morphTargetDictionary||!o.morphTargetInfluences)return;for(const name of Object.keys(o.morphTargetDictionary)){let m=morphs.find(x=>x.name===name);if(!m){m={name,targets:[]};morphs.push(m)}m.targets.push({mesh:o,index:o.morphTargetDictionary[name]})}})}
function applyMorphs(){for(const m of morphs){const v=Number(state.morphs[m.name]||0);m.targets.forEach(t=>t.mesh.morphTargetInfluences[t.index]=v)}model?.updateMatrixWorld(true);frameModel()}
function bodyPreset(){if(!model)return;let sx=1,sz=1;if(state.body==='athletic'){sx=1.06;sz=1.035}else if(state.body==='slim'){sx=.95;sz=.97}else if(state.body==='female'){sx=.98}pivot.scale.set(sx,1,sz);const keys={female:['female','gender'],male:['male','gender'],slim:['thin','weight'],athletic:['muscle','athletic']};for(const m of morphs){const n=m.name.toLowerCase();state.morphs[m.name]=(keys[state.body]||[]).some(k=>n.includes(k))?.65:0}applyMorphs()}
function recolorSkin(){if(!model)return;model.traverse(o=>{if(!o.isMesh)return;const arr=Array.isArray(o.material)?o.material:[o.material];arr.forEach((mat,i)=>{if(!mat?.color)return;const n=(mat.name||o.name||'').toLowerCase();if(!/skin|body|human|base/.test(n))return;const c=mat.clone();c.color.set(state.skin);c.needsUpdate=true;if(Array.isArray(o.material)){const a=[...o.material];a[i]=c;o.material=a}else o.material=c})})}
function ui(){const p=$('bodySkinBlock');if(!p)return;p.innerHTML='';const body=document.createElement('div');body.className='group';body.innerHTML='<h3>Tipo de corpo</h3><div class="options"></div>';for(const [v,l] of BODIES){const b=document.createElement('button');b.className='opt'+(state.body===v?' active':'');b.textContent=l;b.onclick=()=>{state.body=v;ui();bodyPreset()};body.lastElementChild.appendChild(b)}p.appendChild(body);const skin=document.createElement('div');skin.className='group';skin.innerHTML='<h3>Tom de pele</h3><div class="options colors"></div>';for(const c of COLORS.skin){const b=document.createElement('button');b.className='color'+(state.skin===c?' active':'');b.innerHTML=`<i style="background:${c}"></i>`;b.onclick=()=>{state.skin=c;ui();recolorSkin()};skin.lastElementChild.appendChild(b)}p.appendChild(skin)}
function addSlider(root,m){const row=document.createElement('label');row.className='sliderRow';row.innerHTML=`<span>${m.name}</span><input type="range" min="-1" max="1" step="0.05" value="${state.morphs[m.name]||0}">`;row.querySelector('input').oninput=e=>{state.morphs[m.name]=Number(e.target.value);applyMorphs()};root.appendChild(row)}
function morphUI(){const bodyRoot=$('bodyMorphBlock'),faceRoot=$('faceMorphBlock');if(!bodyRoot||!faceRoot)return;bodyRoot.innerHTML='';faceRoot.innerHTML='';const bodyList=morphs.filter(m=>/height|weight|muscle|waist|hip|torso|chest|arm|leg|shoulder/i.test(m.name)).slice(0,12);const faceList=morphs.filter(m=>/head|face|nose|mouth|eye|chin|cheek|jaw|brow|lip/i.test(m.name)).slice(0,14);if(!bodyList.length)bodyRoot.innerHTML='<span style="font-size:10px;color:#8795aa">A base 3D não expôs ajustes corporais adicionais.</span>';else bodyList.forEach(m=>addSlider(bodyRoot,m));if(!faceList.length)faceRoot.innerHTML='<span style="font-size:10px;color:#8795aa">A base 3D não expôs ajustes faciais adicionais.</span>';else faceList.forEach(m=>addSlider(faceRoot,m))}
async function load(){const s=$('modelStatus');try{const gltf=await new GLTFLoader().loadAsync(MODEL);model=gltf.scene;model.traverse(o=>{if(o.isMesh){o.castShadow=true;o.receiveShadow=true}});normalizeModel(model);pivot.add(model);scanMorphs();recolorSkin();bodyPreset();morphUI();frameModel();s.textContent=`Base humana GLB carregada · ${morphs.length} morph targets`;s.className='status ok'}catch(e){console.error(e);s.textContent='Não foi possível carregar a base GLB. Verifique a conexão e abra novamente.';s.className='status err'}}
async function restore(){const {data:{user}}=await sb.auth.getUser();if(!user)return;const {data}=await sb.from('profiles').select('avatar_config').eq('id',user.id).maybeSingle();if(data?.avatar_config?.style==='zuno-glb-parametric'){Object.assign(state,data.avatar_config);state.version=11;state.top=state.bottom=state.shoes=state.head=state.face=state.neck=state.back='none';ui();if(model){recolorSkin();bodyPreset();applyMorphs();morphUI();frameModel()}}}
async function save(){const b=$('save'),msg=$('msg');b.disabled=true;msg.className='msg';msg.textContent='Salvando...';try{const {data:{user},error:u}=await sb.auth.getUser();if(u||!user)throw new Error('Sessão inválida');renderer.render(scene,camera);const png=renderer.domElement.toDataURL('image/png',.92);const cfg={...state,version:11,updatedAt:new Date().toISOString(),modelSource:'MakeHuman MPFB2 CC0 via three.ws',fittedWardrobe:false};const {error}=await sb.from('profiles').update({avatar_config:cfg,avatar_url:png,sex:state.body==='female'?'feminino':'masculino'}).eq('id',user.id);if(error)throw error;msg.textContent='Personagem 3D salvo! ✅'}catch(e){msg.className='msg err';msg.textContent='Erro: '+(e.message||'não foi possível salvar')}finally{b.disabled=false}}

init();ui();restore().catch(console.warn);load().then(()=>restore()).catch(console.warn);$('save').onclick=save;