import * as THREE from 'https://esm.sh/three@0.180.0';
import {GLTFLoader} from 'https://esm.sh/three@0.180.0/examples/jsm/loaders/GLTFLoader.js';
const sb=window.supabase.createClient('https://rliymfbbhqoejgfvsbuu.supabase.co','sb_publishable_E4go4X7yZ6d-aXnKAT-fWw_Y8uHIJT0');
const MODEL='https://raw.githubusercontent.com/nirholas/three.ws/main/public/avatars/parametric-base.glb';
const $=id=>document.getElementById(id);const COLORS={skin:['#f4d1b8','#e7b18b','#cb8b63','#a76849','#79503a','#4d3226']};
const BODIES=[['male','Masculino'],['female','Feminino'],['slim','Magro'],['athletic','Atlético']];
const TOPS=[['none','Sem peça'],['camiseta','Camiseta'],['regata','Regata'],['moletom','Moletom'],['jaqueta','Jaqueta']];
const BOTTOMS=[['none','Sem peça'],['shorts','Shorts'],['jeans','Calça jeans'],['cargo','Calça cargo'],['saia','Saia']];
const SHOES=[['none','Sem calçado'],['tenis','Tênis'],['cano-alto','Tênis cano alto'],['bota','Bota']];
const CLOTH_COLORS=['#111827','#f8fafc','#6d28d9','#2563eb','#dc2626','#15803d'];
const state={version:13,style:'zuno-glb-parametric',body:'male',skin:'#e7b18b',top:'camiseta',topColor:'#111827',bottom:'jeans',bottomColor:'#111827',shoes:'tenis',shoesColor:'#f8fafc',head:'none',face:'none',neck:'none',back:'none',morphs:{}};
let renderer,scene,camera,pivot,model,morphs=[],wardrobe,drag=false,lastX=0,targetRot=0,currentRot=0;
const EXACT={height:'Altura',weight:'Peso',muscle:'Musculatura',waist:'Cintura',hip:'Quadril',hips:'Quadril',torso:'Tronco',chest:'Peitoral',shoulder:'Ombros',head:'Cabeça',face:'Rosto',nose:'Nariz',mouth:'Boca',eye:'Olhos',eyes:'Olhos',chin:'Queixo',cheek:'Bochechas',jaw:'Mandíbula',brow:'Sobrancelhas',lip:'Lábios',forehead:'Testa',ear:'Orelhas'};
function ptMorph(n){const raw=String(n||'');const k=raw.toLowerCase().replace(/[^a-z0-9]+/g,'');if(EXACT[k])return EXACT[k];return raw.replace(/[_\-.]+/g,' ').replace(/height/ig,'Altura').replace(/weight/ig,'Peso').replace(/muscle/ig,'Musculatura').replace(/waist/ig,'Cintura').replace(/hip/ig,'Quadril').replace(/shoulder/ig,'Ombro').replace(/chest/ig,'Peitoral').replace(/head/ig,'Cabeça').replace(/face/ig,'Rosto').replace(/nose/ig,'Nariz').replace(/mouth/ig,'Boca').replace(/eye/ig,'Olho').replace(/chin/ig,'Queixo').replace(/cheek/ig,'Bochecha').replace(/jaw/ig,'Mandíbula').replace(/brow/ig,'Sobrancelha').replace(/lip/ig,'Lábio')}
function init(){const v=$('viewer');scene=new THREE.Scene();scene.background=new THREE.Color(0xdce8f7);camera=new THREE.PerspectiveCamera(30,v.clientWidth/v.clientHeight,.01,100);renderer=new THREE.WebGLRenderer({antialias:true,preserveDrawingBuffer:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setSize(v.clientWidth,v.clientHeight);renderer.shadowMap.enabled=true;renderer.outputColorSpace=THREE.SRGBColorSpace;v.replaceChildren(renderer.domElement);scene.add(new THREE.HemisphereLight(0xffffff,0x64748b,2.15));const key=new THREE.DirectionalLight(0xffffff,3.1);key.position.set(3,5,4);key.castShadow=true;scene.add(key);const rim=new THREE.DirectionalLight(0x9b5cff,1.5);rim.position.set(-4,3,-2);scene.add(rim);pivot=new THREE.Group();wardrobe=new THREE.Group();pivot.add(wardrobe);scene.add(pivot);v.onpointerdown=e=>{drag=true;lastX=e.clientX};v.onpointermove=e=>{if(drag){targetRot+=(e.clientX-lastX)*.012;lastX=e.clientX}};v.onpointerup=()=>drag=false;v.onpointercancel=()=>drag=false;addEventListener('resize',()=>{camera.aspect=v.clientWidth/v.clientHeight;camera.updateProjectionMatrix();renderer.setSize(v.clientWidth,v.clientHeight);frameModel()});loop()}
function loop(){requestAnimationFrame(loop);currentRot+=(targetRot-currentRot)*.12;pivot.rotation.y=currentRot;renderer.render(scene,camera)}
function normalizeModel(root){const b=new THREE.Box3().setFromObject(root),s=new THREE.Vector3(),c=new THREE.Vector3();b.getSize(s);root.scale.setScalar(3.45/Math.max(s.y,.001));root.updateMatrixWorld(true);let b2=new THREE.Box3().setFromObject(root);root.position.y-=b2.min.y;root.updateMatrixWorld(true);b2=new THREE.Box3().setFromObject(root);b2.getCenter(c);root.position.x-=c.x;root.position.z-=c.z;root.updateMatrixWorld(true)}
function frameModel(){if(!model)return;const box=new THREE.Box3().setFromObject(pivot),size=new THREE.Vector3(),center=new THREE.Vector3();box.getSize(size);box.getCenter(center);const fov=THREE.MathUtils.degToRad(camera.fov),aspect=Math.max(camera.aspect,.5);const dist=Math.max((size.y*.5)/Math.tan(fov*.5),(size.x*.5)/(Math.tan(fov*.5)*aspect))*1.2;camera.position.set(0,center.y,dist);camera.lookAt(center);camera.near=.01;camera.far=dist+30;camera.updateProjectionMatrix()}
function scanMorphs(){morphs=[];model.traverse(o=>{if(!o.isMesh||!o.morphTargetDictionary||!o.morphTargetInfluences)return;for(const name of Object.keys(o.morphTargetDictionary)){let m=morphs.find(x=>x.name===name);if(!m){m={name,label:ptMorph(name),targets:[]};morphs.push(m)}m.targets.push({mesh:o,index:o.morphTargetDictionary[name]})}})}
function applyMorphs(){for(const m of morphs){const v=Number(state.morphs[m.name]||0);m.targets.forEach(t=>t.mesh.morphTargetInfluences[t.index]=v)}model?.updateMatrixWorld(true);buildWardrobe();frameModel()}
function bodyPreset(){if(!model)return;let sx=1,sz=1;if(state.body==='athletic'){sx=1.06;sz=1.035}else if(state.body==='slim'){sx=.95;sz=.97}else if(state.body==='female'){sx=.98}pivot.scale.set(sx,1,sz);const keys={female:['female','gender'],male:['male','gender'],slim:['thin','weight'],athletic:['muscle','athletic']};for(const m of morphs){const n=m.name.toLowerCase();state.morphs[m.name]=(keys[state.body]||[]).some(k=>n.includes(k))?.65:0}applyMorphs()}
function recolorSkin(){if(!model)return;model.traverse(o=>{if(!o.isMesh)return;const arr=Array.isArray(o.material)?o.material:[o.material];arr.forEach((mat,i)=>{if(!mat?.color)return;const n=(mat.name||o.name||'').toLowerCase();if(!/skin|body|human|base/.test(n))return;const c=mat.clone();c.color.set(state.skin);if(Array.isArray(o.material)){const a=[...o.material];a[i]=c;o.material=a}else o.material=c})})}
function clearWardrobe(){while(wardrobe.children.length){const o=wardrobe.children.pop();o.traverse?.(x=>{x.geometry?.dispose();if(x.material){(Array.isArray(x.material)?x.material:[x.material]).forEach(m=>m.dispose?.())}})}}
function mat(color,rough=.72){return new THREE.MeshStandardMaterial({color,roughness:rough,metalness:.03,side:THREE.DoubleSide})}
function addMesh(g,color,pos,scale=[1,1,1]){const m=new THREE.Mesh(g,mat(color));m.position.set(...pos);m.scale.set(...scale);m.castShadow=true;m.receiveShadow=true;wardrobe.add(m);return m}
function bodyDims(){const b=new THREE.Box3().setFromObject(model),s=new THREE.Vector3();b.getSize(s);return{h:s.y,w:s.x,d:s.z}}
function buildWardrobe(){if(!model||!wardrobe)return;clearWardrobe();const d=bodyDims(),h=d.h,w=Math.max(.55,d.w),depth=Math.max(.3,d.d);const torsoY=h*.64,hipY=h*.47,legY=h*.27;const tw=w*.56,td=depth*.58;
 if(state.top!=='none'){let len=.48;if(state.top==='regata')len=.4;if(state.top==='moletom'||state.top==='jaqueta')len=.56;const geo=new THREE.CapsuleGeometry(tw*.46,len,5,12);const top=addMesh(geo,state.topColor,[0,torsoY,0],[1,1,td/(tw*.7)]);top.rotation.z=Math.PI/2;if(state.top==='jaqueta'){const stripe=addMesh(new THREE.BoxGeometry(.025,len*.95,.018),'#7c3aed',[0,torsoY,td*.72]);stripe.rotation.z=0}}
 if(state.bottom==='shorts'){addMesh(new THREE.BoxGeometry(w*.47,h*.14,depth*.7),state.bottomColor,[0,hipY,0])}else if(state.bottom==='saia'){addMesh(new THREE.CylinderGeometry(w*.22,w*.31,h*.18,18),state.bottomColor,[0,hipY-.03,0])}else if(state.bottom!=='none'){const cargo=state.bottom==='cargo';[-1,1].forEach(side=>{addMesh(new THREE.CapsuleGeometry(w*.105,h*.34,5,10),state.bottomColor,[side*w*.135,legY,0],[cargo?1.12:1,1,depth/(w*.8)]);if(cargo)addMesh(new THREE.BoxGeometry(w*.13,h*.07,depth*.75),state.bottomColor,[side*w*.24,h*.34,depth*.02])})}
 if(state.shoes!=='none'){[-1,1].forEach(side=>{const high=state.shoes==='cano-alto'||state.shoes==='bota';const geo=new THREE.BoxGeometry(w*.22,high?h*.095:h*.065,depth*.95);const shoe=addMesh(geo,state.shoesColor,[side*w*.145,h*.035,depth*.12]);shoe.geometry.translate(0,0,depth*.12)})}
 frameModel()}
function buttons(root,title,items,key,onchange){const g=document.createElement('div');g.className='group';g.innerHTML=`<h3>${title}</h3><div class="options"></div>`;items.forEach(([v,l])=>{const b=document.createElement('button');b.className='opt'+(state[key]===v?' active':'');b.textContent=l;b.onclick=()=>{state[key]=v;onchange()};g.lastElementChild.appendChild(b)});root.appendChild(g)}
function colorButtons(root,title,key,onchange){const g=document.createElement('div');g.className='group';g.innerHTML=`<h3>${title}</h3><div class="options colors"></div>`;CLOTH_COLORS.forEach(c=>{const b=document.createElement('button');b.className='color'+(state[key]===c?' active':'');b.innerHTML=`<i style="background:${c}"></i>`;b.onclick=()=>{state[key]=c;onchange()};g.lastElementChild.appendChild(b)});root.appendChild(g)}
function ui(){const p=$('bodySkinBlock');if(p){p.innerHTML='';buttons(p,'Tipo de corpo',BODIES,'body',()=>{ui();bodyPreset()});const skin=document.createElement('div');skin.className='group';skin.innerHTML='<h3>Tom de pele</h3><div class="options colors"></div>';COLORS.skin.forEach(c=>{const b=document.createElement('button');b.className='color'+(state.skin===c?' active':'');b.innerHTML=`<i style="background:${c}"></i>`;b.onclick=()=>{state.skin=c;ui();recolorSkin()};skin.lastElementChild.appendChild(b)});p.appendChild(skin)}const c=$('clothesBlock');if(c){c.innerHTML='';buttons(c,'Parte de cima',TOPS,'top',()=>{ui();buildWardrobe()});colorButtons(c,'Cor da parte de cima','topColor',()=>{ui();buildWardrobe()});buttons(c,'Parte de baixo',BOTTOMS,'bottom',()=>{ui();buildWardrobe()});colorButtons(c,'Cor da parte de baixo','bottomColor',()=>{ui();buildWardrobe()})}const sh=$('shoesBlock');if(sh){sh.innerHTML='';buttons(sh,'Tipo de calçado',SHOES,'shoes',()=>{ui();buildWardrobe()});colorButtons(sh,'Cor do calçado','shoesColor',()=>{ui();buildWardrobe()})}}
function addSlider(root,m){const row=document.createElement('label');row.className='sliderRow';row.innerHTML=`<span>${m.label}</span><input type="range" min="-1" max="1" step="0.05" value="${state.morphs[m.name]||0}">`;row.querySelector('input').oninput=e=>{state.morphs[m.name]=Number(e.target.value);applyMorphs()};root.appendChild(row)}
function morphUI(){const b=$('bodyMorphBlock'),f=$('faceMorphBlock');if(!b||!f)return;b.innerHTML='';f.innerHTML='';const bl=morphs.filter(m=>/height|weight|muscle|waist|hip|torso|chest|arm|leg|shoulder/i.test(m.name)).slice(0,14),fl=morphs.filter(m=>/head|face|nose|mouth|eye|chin|cheek|jaw|brow|lip|forehead|ear/i.test(m.name)).slice(0,16);bl.forEach(m=>addSlider(b,m));fl.forEach(m=>addSlider(f,m));if(!bl.length)b.textContent='Sem ajustes corporais adicionais.';if(!fl.length)f.textContent='Sem ajustes faciais adicionais.'}
async function load(){const s=$('modelStatus');try{const gltf=await new GLTFLoader().loadAsync(MODEL);model=gltf.scene;model.traverse(o=>{if(o.isMesh){o.castShadow=true;o.receiveShadow=true}});normalizeModel(model);pivot.add(model);pivot.remove(wardrobe);pivot.add(wardrobe);scanMorphs();recolorSkin();bodyPreset();morphUI();buildWardrobe();frameModel();s.textContent=`Personagem 3D carregado · roupas disponíveis`;s.className='status ok'}catch(e){console.error(e);s.textContent='Não foi possível carregar o personagem 3D.';s.className='status err'}}
async function restore(){const {data:{user}}=await sb.auth.getUser();if(!user)return;const {data}=await sb.from('profiles').select('avatar_config').eq('id',user.id).maybeSingle();if(data?.avatar_config?.style==='zuno-glb-parametric'){Object.assign(state,data.avatar_config);state.version=13;ui();if(model){recolorSkin();applyMorphs();morphUI();buildWardrobe()}}}
async function save(){const b=$('save'),msg=$('msg');b.disabled=true;msg.textContent='Salvando...';try{const {data:{user}}=await sb.auth.getUser();if(!user)throw new Error('Sessão inválida');renderer.render(scene,camera);const png=renderer.domElement.toDataURL('image/jpeg',.72);const cfg={...state,version:13,updatedAt:new Date().toISOString(),modelSource:'MakeHuman MPFB2 CC0 via three.ws',fittedWardrobe:'procedural-v1'};const {error}=await sb.from('profiles').update({avatar_config:cfg,avatar_url:png,sex:state.body==='female'?'feminino':'masculino'}).eq('id',user.id);if(error)throw error;msg.className='msg';msg.textContent='Personagem e roupas salvos! ✅'}catch(e){msg.className='msg err';msg.textContent='Erro: '+e.message}finally{b.disabled=false}}
init();ui();restore().catch(console.warn);load().then(()=>restore()).catch(console.warn);$('save').onclick=save;