import * as THREE from 'https://esm.sh/three@0.180.0';
import {GLTFLoader} from 'https://esm.sh/three@0.180.0/examples/jsm/loaders/GLTFLoader.js';
const sb=window.supabase.createClient('https://rliymfbbhqoejgfvsbuu.supabase.co','sb_publishable_E4go4X7yZ6d-aXnKAT-fWw_Y8uHIJT0');
const MODEL='https://raw.githubusercontent.com/nirholas/three.ws/main/public/avatars/parametric-base.glb';
const $=id=>document.getElementById(id),SKIN=['#f4d1b8','#e7b18b','#cb8b63','#a76849','#79503a','#4d3226'],COLORS=['#111827','#f8fafc','#6d28d9','#2563eb','#dc2626','#15803d'];
const BODIES=[['male','Masculino'],['female','Feminino'],['slim','Magro'],['athletic','Atlético']],TOPS=[['none','Sem peça'],['camiseta','Camiseta'],['regata','Regata'],['moletom','Moletom'],['jaqueta','Jaqueta']],BOTTOMS=[['none','Sem peça'],['shorts','Shorts'],['jeans','Calça jeans'],['cargo','Calça cargo'],['saia','Saia']],SHOES=[['none','Sem calçado'],['tenis','Tênis'],['cano-alto','Tênis cano alto'],['bota','Bota']];
const state={version:14,style:'zuno-glb-parametric',body:'male',skin:'#e7b18b',top:'camiseta',topColor:'#111827',bottom:'jeans',bottomColor:'#111827',shoes:'tenis',shoesColor:'#f8fafc',morphs:{}};
let renderer,scene,camera,pivot,model,wardrobe,morphs=[],drag=false,lastX=0,targetRot=0,currentRot=0;
const PT={height:'Altura',weight:'Peso',muscle:'Musculatura',waist:'Cintura',hip:'Quadril',hips:'Quadril',torso:'Tronco',chest:'Peitoral',shoulder:'Ombros',head:'Cabeça',face:'Rosto',nose:'Nariz',mouth:'Boca',eye:'Olhos',eyes:'Olhos',chin:'Queixo',cheek:'Bochechas',jaw:'Mandíbula',brow:'Sobrancelhas',lip:'Lábios',forehead:'Testa',ear:'Orelhas'};
function label(n){const k=String(n).toLowerCase().replace(/[^a-z0-9]/g,'');if(PT[k])return PT[k];let s=String(n).replace(/[_\-.]+/g,' ');for(const [a,b] of Object.entries(PT))s=s.replace(new RegExp(a,'ig'),b);return s}
function init(){const v=$('viewer');scene=new THREE.Scene();scene.background=new THREE.Color(0xdce8f7);camera=new THREE.PerspectiveCamera(30,v.clientWidth/v.clientHeight,.01,100);renderer=new THREE.WebGLRenderer({antialias:true,preserveDrawingBuffer:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setSize(v.clientWidth,v.clientHeight);renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.shadowMap.enabled=true;v.replaceChildren(renderer.domElement);scene.add(new THREE.HemisphereLight(0xffffff,0x64748b,2.2));const l=new THREE.DirectionalLight(0xffffff,3);l.position.set(3,5,4);scene.add(l);const r=new THREE.DirectionalLight(0x8b5cf6,1.2);r.position.set(-3,3,-2);scene.add(r);pivot=new THREE.Group();wardrobe=new THREE.Group();pivot.add(wardrobe);scene.add(pivot);v.onpointerdown=e=>{drag=true;lastX=e.clientX};v.onpointermove=e=>{if(drag){targetRot+=(e.clientX-lastX)*.012;lastX=e.clientX}};v.onpointerup=v.onpointercancel=()=>drag=false;addEventListener('resize',()=>{camera.aspect=v.clientWidth/v.clientHeight;camera.updateProjectionMatrix();renderer.setSize(v.clientWidth,v.clientHeight);frame()});loop()}
function loop(){requestAnimationFrame(loop);currentRot+=(targetRot-currentRot)*.12;pivot.rotation.y=currentRot;renderer.render(scene,camera)}
function normalize(root){const b=new THREE.Box3().setFromObject(root),s=new THREE.Vector3(),c=new THREE.Vector3();b.getSize(s);root.scale.setScalar(3.45/Math.max(s.y,.001));root.updateMatrixWorld(true);let x=new THREE.Box3().setFromObject(root);root.position.y-=x.min.y;root.updateMatrixWorld(true);x=new THREE.Box3().setFromObject(root);x.getCenter(c);root.position.x-=c.x;root.position.z-=c.z}
function frame(){if(!model)return;const b=new THREE.Box3().setFromObject(pivot),s=new THREE.Vector3(),c=new THREE.Vector3();b.getSize(s);b.getCenter(c);const f=THREE.MathUtils.degToRad(camera.fov),d=Math.max((s.y*.5)/Math.tan(f*.5),(s.x*.5)/(Math.tan(f*.5)*Math.max(camera.aspect,.5)))*1.18;camera.position.set(0,c.y,d);camera.lookAt(c);camera.far=d+30;camera.updateProjectionMatrix()}
function scan(){morphs=[];model.traverse(o=>{if(!o.isMesh||!o.morphTargetDictionary)return;for(const n of Object.keys(o.morphTargetDictionary)){let m=morphs.find(x=>x.name===n);if(!m){m={name:n,label:label(n),targets:[]};morphs.push(m)}m.targets.push({mesh:o,index:o.morphTargetDictionary[n]})}})}
function apply(){for(const m of morphs){const v=Number(state.morphs[m.name]||0);m.targets.forEach(t=>t.mesh.morphTargetInfluences[t.index]=v)}model.updateMatrixWorld(true);buildClothes();frame()}
function preset(){let x=1,z=1;if(state.body==='athletic'){x=1.06;z=1.035}else if(state.body==='slim'){x=.95;z=.97}else if(state.body==='female')x=.98;pivot.scale.set(x,1,z);const keys={female:['female','gender'],male:['male','gender'],slim:['thin','weight'],athletic:['muscle','athletic']};morphs.forEach(m=>state.morphs[m.name]=(keys[state.body]||[]).some(k=>m.name.toLowerCase().includes(k))?.65:0);apply()}
function skin(){model?.traverse(o=>{if(!o.isMesh)return;const a=Array.isArray(o.material)?o.material:[o.material];a.forEach((m,i)=>{if(!m?.color||!/skin|body|human|base/i.test(m.name||o.name||''))return;const n=m.clone();n.color.set(state.skin);if(Array.isArray(o.material)){const z=[...o.material];z[i]=n;o.material=z}else o.material=n})})}
function clear(){while(wardrobe.children.length){const o=wardrobe.children[0];wardrobe.remove(o);o.traverse(x=>{x.geometry?.dispose();x.material?.dispose?.()})}}
function material(c){return new THREE.MeshStandardMaterial({color:c,roughness:.8,side:THREE.DoubleSide})}
function mesh(g,c){const m=new THREE.Mesh(g,material(c));m.castShadow=true;wardrobe.add(m);return m}
function dims(){const b=new THREE.Box3().setFromObject(model),s=new THREE.Vector3();b.getSize(s);return{h:s.y,w:s.x,d:s.z}}
function torsoGeometry(w,d,h,loose=1){const g=new THREE.CylinderGeometry(w*.31*loose,w*.27*loose,h,32,8,true);g.scale(1,1,Math.max(.55,d/(w*.62)));return g}
function limb(r,len,c,pos){const m=mesh(new THREE.CapsuleGeometry(r,len,6,14),c);m.position.set(...pos);return m}
function buildClothes(){if(!model)return;clear();const d=dims(),h=d.h,w=d.w,dep=d.d,loose=state.top==='moletom'?1.13:state.top==='jaqueta'?1.09:1.035;
 if(state.top!=='none'){const len=h*(state.top==='regata'?.19:state.top==='camiseta'?.22:.25),y=h*.67;const t=mesh(torsoGeometry(w,dep,len,loose),state.topColor);t.position.y=y;if(state.top!=='regata'){const sleeve=state.top==='camiseta'?h*.08:h*.19;[-1,1].forEach(side=>{const a=limb(w*.055*loose,sleeve,state.topColor,[side*w*.34,y+len*.25,0]);a.rotation.z=side*Math.PI*.46})}if(state.top==='jaqueta'){const zip=mesh(new THREE.BoxGeometry(.018,len*.92,.015),'#8b5cf6');zip.position.set(0,y,dep*.34)}}
 if(state.bottom==='saia'){const m=mesh(new THREE.CylinderGeometry(w*.25,w*.31,h*.18,32,5,true),state.bottomColor);m.position.y=h*.43}else if(state.bottom!=='none'){const short=state.bottom==='shorts',len=h*(short?.13:.36),y=short?h*.43:h*.28;[-1,1].forEach(side=>{const leg=limb(w*(state.bottom==='cargo'?.105:.09),len,state.bottomColor,[side*w*.13,y,0]);leg.scale.z=Math.max(.6,dep/(w*.75))})}
 if(state.shoes!=='none'){[-1,1].forEach(side=>{const high=state.shoes!=='tenis',g=new THREE.CapsuleGeometry(w*.085,high?h*.07:h*.035,5,12),m=mesh(g,state.shoesColor);m.position.set(side*w*.13,h*.035,dep*.09);m.rotation.x=Math.PI/2;m.scale.z=1.45})}}
function opts(root,title,data,key,cb){const g=document.createElement('div');g.className='group';g.innerHTML=`<h3>${title}</h3><div class="options"></div>`;data.forEach(([v,l])=>{const b=document.createElement('button');b.className='opt'+(state[key]===v?' active':'');b.textContent=l;b.onclick=()=>{state[key]=v;ui();cb()};g.lastElementChild.appendChild(b)});root.appendChild(g)}
function colors(root,title,key){const g=document.createElement('div');g.className='group';g.innerHTML=`<h3>${title}</h3><div class="options colors"></div>`;COLORS.forEach(c=>{const b=document.createElement('button');b.className='color'+(state[key]===c?' active':'');b.innerHTML=`<i style="background:${c}"></i>`;b.onclick=()=>{state[key]=c;ui();buildClothes()};g.lastElementChild.appendChild(b)});root.appendChild(g)}
function ui(){const p=$('bodySkinBlock');if(p){p.innerHTML='';opts(p,'Tipo de corpo',BODIES,'body',preset);const g=document.createElement('div');g.className='group';g.innerHTML='<h3>Tom de pele</h3><div class="options colors"></div>';SKIN.forEach(c=>{const b=document.createElement('button');b.className='color'+(state.skin===c?' active':'');b.innerHTML=`<i style="background:${c}"></i>`;b.onclick=()=>{state.skin=c;ui();skin()};g.lastElementChild.appendChild(b)});p.appendChild(g)}const c=$('clothesBlock');if(c){c.innerHTML='';opts(c,'Parte de cima',TOPS,'top',buildClothes);colors(c,'Cor da parte de cima','topColor');opts(c,'Parte de baixo',BOTTOMS,'bottom',buildClothes);colors(c,'Cor da parte de baixo','bottomColor')}const s=$('shoesBlock');if(s){s.innerHTML='';opts(s,'Tipo de calçado',SHOES,'shoes',buildClothes);colors(s,'Cor do calçado','shoesColor')}}
function sliders(){const b=$('bodyMorphBlock'),f=$('faceMorphBlock');if(!b||!f)return;b.innerHTML='';f.innerHTML='';const add=(r,m)=>{const x=document.createElement('label');x.className='sliderRow';x.innerHTML=`<span>${m.label}</span><input type="range" min="-1" max="1" step=".05" value="${state.morphs[m.name]||0}">`;x.lastElementChild.oninput=e=>{state.morphs[m.name]=+e.target.value;apply()};r.appendChild(x)};morphs.filter(m=>/height|weight|muscle|waist|hip|torso|chest|arm|leg|shoulder/i.test(m.name)).slice(0,14).forEach(m=>add(b,m));morphs.filter(m=>/head|face|nose|mouth|eye|chin|cheek|jaw|brow|lip|forehead|ear/i.test(m.name)).slice(0,16).forEach(m=>add(f,m))}
async function load(){const s=$('modelStatus');try{const g=await new GLTFLoader().loadAsync(MODEL);model=g.scene;normalize(model);pivot.add(model);pivot.remove(wardrobe);pivot.add(wardrobe);scan();skin();preset();sliders();buildClothes();frame();s.textContent='Personagem 3D carregado · vestuário adaptativo ativo';s.className='status ok'}catch(e){console.error(e);s.textContent='Não foi possível carregar o personagem 3D.';s.className='status err'}}
async function restore(){const {data:{user}}=await sb.auth.getUser();if(!user)return;const {data}=await sb.from('profiles').select('avatar_config').eq('id',user.id).maybeSingle();if(data?.avatar_config?.style==='zuno-glb-parametric'){Object.assign(state,data.avatar_config);state.version=14;ui();if(model){skin();apply();sliders()}}}
async function save(){const b=$('save'),msg=$('msg');b.disabled=true;msg.textContent='Salvando...';try{const {data:{user}}=await sb.auth.getUser();if(!user)throw Error('Sessão inválida');const preview=renderer.domElement.toDataURL('image/jpeg',.55);const cfg={...state,version:14,updatedAt:new Date().toISOString(),fittedWardrobe:'adaptive-v2'};const {error}=await sb.from('profiles').update({avatar_config:cfg,avatar_url:preview,sex:state.body==='female'?'feminino':'masculino'}).eq('id',user.id);if(error)throw error;msg.textContent='Personagem salvo! ✅'}catch(e){msg.className='msg err';msg.textContent='Erro: '+e.message}finally{b.disabled=false}}
init();ui();restore().catch(console.warn);load().then(restore).catch(console.warn);$('save').onclick=save;