(()=>{
  'use strict';
  const SUPABASE_URL='https://rliymfbbhqoejgfvsbuu.supabase.co';
  const SUPABASE_KEY='sb_publishable_E4go4X7yZ6d-aXnKAT-fWw_Y8uHIJT0';
  const supabaseClient=window.ZunoSupabaseClient||window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY);
  window.ZunoSupabaseClient=window.ZunoSupabaseClient||supabaseClient;
  const $=id=>document.getElementById(id);
  const loading=$('loading'),app=$('app'),welcomeScreen=$('welcomeScreen'),homeScreen=$('homeScreen');
  let currentUser=null,currentProfile=null,friendProfiles=[],profileChannel=null,homeRevealTimer=0,homeRevealStartedAt=0,bootSeq=0;

  function esc(v){const d=document.createElement('div');d.textContent=v==null?'':String(v);return d.innerHTML}
  function safeAvatar(v){const s=String(v||'');return /^(data:image\/(?:svg\+xml|png|jpeg|webp);|https:\/\/)/i.test(s)?s:''}
  function avatarHTML(p,cls='friend-avatar'){const src=safeAvatar(p?.avatar_url),name=p?.username||'?';return src?'<img class="'+cls+'" src="'+esc(src)+'" alt="Avatar de '+esc(name)+'">':'<div class="'+cls+' friend-avatar-fallback">'+esc(name.charAt(0).toUpperCase())+'</div>'}
  function playerName(){return String(currentProfile?.username||'ZunoPlayer').trim()||'ZunoPlayer'}
  function syncPlayerName(){const el=$('username');if(!el)return;const name=playerName();el.textContent=name;el.dataset.playerName='1';el.setAttribute('title',name);window.dispatchEvent(new CustomEvent('zuno:player-name-ready',{detail:{name}}))}
  function hideLoading(){if(loading)loading.style.display='none'}
  function markHomeUsable(){if(!homeScreen)return false;const currentRuntime=!!window.__ZUNOPLAY_CURRENT_HOME__||document.body?.classList.contains('zuno-official-v33')||document.documentElement.dataset.zunoInterface==='current';if(currentRuntime&&document.documentElement.dataset.zunoHomeCurrentReady!=='1')document.documentElement.dataset.zunoHomeCurrentReady='1';return document.documentElement.dataset.zunoHomeCurrentReady==='1'}
  function showWelcome(){clearTimeout(homeRevealTimer);homeRevealStartedAt=0;document.documentElement.dataset.zunoAuthState='guest';if(app)app.style.display='block';if(welcomeScreen)welcomeScreen.style.display='flex';if(homeScreen)homeScreen.style.display='none';hideLoading()}
  function revealCurrentHome(){if(!currentUser||!currentProfile)return;if(!homeRevealStartedAt)homeRevealStartedAt=performance.now();if(markHomeUsable()||document.documentElement.dataset.zunoAppReady==='1'){clearTimeout(homeRevealTimer);homeRevealStartedAt=0;document.documentElement.dataset.zunoAppReady='1';hideLoading();return}if(performance.now()-homeRevealStartedAt>1800){document.documentElement.dataset.zunoHomeCurrentReady='1';document.documentElement.dataset.zunoAppReady='1';clearTimeout(homeRevealTimer);homeRevealStartedAt=0;hideLoading();return}clearTimeout(homeRevealTimer);homeRevealTimer=setTimeout(revealCurrentHome,32)}
  function showHome({resume=false}={}){if(!currentUser||!currentProfile)return;document.documentElement.dataset.zunoAuthState='member';if(app)app.style.display='block';if(welcomeScreen)welcomeScreen.style.display='none';if(homeScreen)homeScreen.style.display='block';syncPlayerName();const alreadyReady=markHomeUsable()||document.documentElement.dataset.zunoAppReady==='1';if(loading)loading.style.display=alreadyReady||resume?'none':'flex';if(alreadyReady||resume){document.documentElement.dataset.zunoAppReady='1';hideLoading()}else revealCurrentHome()}
  function restoreHomeFromLifecycle(){if(!currentUser||!currentProfile)return;markHomeUsable();showHome({resume:true});window.ZunoBrand?.refresh?.();window.dispatchEvent(new CustomEvent('zuno:home-resumed'))}
  window.addEventListener('zuno:home-current-ready',()=>{if(currentProfile){syncPlayerName();revealCurrentHome()}});
  window.addEventListener('pageshow',()=>setTimeout(restoreHomeFromLifecycle,0));
  document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible')setTimeout(restoreHomeFromLifecycle,0)});

  function auraFor(level){if(level>=10)return'Lenda Zuno';if(level>=8)return'Guardião Estelar';if(level>=6)return'Mestre Cósmico';if(level>=4)return'Explorador Astral';if(level>=2)return'Aventureiro';return'Explorador'}
  function renderProfile(){const p=currentProfile||{},level=Math.max(1,Math.min(10,Number(p.level)||1));syncPlayerName();if($('coinCount'))$('coinCount').textContent=Number(p.coins||0).toLocaleString('pt-BR');if($('auraEmblem'))$('auraEmblem').dataset.level=level;if($('auraTitle'))$('auraTitle').textContent=auraFor(level);if($('levelProgress'))$('levelProgress').style.width=(level*10)+'%';if($('levelProgressText'))$('levelProgressText').textContent='Nível '+level+' de 10';if($('challengeBadge'))$('challengeBadge').textContent='N'+level}
  async function loadProfile(){if(!currentUser)return false;const{data,error}=await supabaseClient.from('profiles').select('id,username,sex,level,coins').eq('id',currentUser.id).maybeSingle();if(error){console.error('Perfil:',error);return false}if(!data){console.error('Perfil canônico não encontrado');return false}currentProfile=data;renderProfile();return true}
  function presenceMap(){return window.ZunoRealtime?.getPresence?.()||{}}
  function renderFriends(){const state=presenceMap(),online=new Set(Object.keys(state)),onlyOnline=friendProfiles.filter(p=>online.has(p.id));const strip=$('friendsStrip');if(!strip)return;strip.innerHTML='';if(!onlyOnline.length){const empty=document.createElement('div');empty.className='empty-friends';empty.textContent='Nenhum amigo online agora.';strip.appendChild(empty)}onlyOnline.slice(0,7).forEach(p=>{const el=document.createElement('button');el.type='button';el.className='friend';el.onclick=()=>location.href='perfil.html?user='+encodeURIComponent(p.id);el.innerHTML='<div class="friend-avatar-wrap">'+avatarHTML(p)+'<span class="friend-status"></span></div><div class="friend-name">'+esc(p.username||'Usuário')+'</div>';strip.appendChild(el)});const invite=document.createElement('button');invite.type='button';invite.className='friend invite';invite.onclick=()=>location.href='amigos.html';invite.innerHTML='<div class="friend-avatar-wrap">+</div><div class="friend-name">Convidar</div>';strip.appendChild(invite);if($('onlineCount'))$('onlineCount').textContent=String(onlyOnline.length)}
  async function loadFriends(){if(!currentUser)return;const{data,error}=await supabaseClient.from('friendships').select('user_id,friend_id').or('user_id.eq.'+currentUser.id+',friend_id.eq.'+currentUser.id);if(error){console.error('Amigos:',error);return}const ids=[...new Set((data||[]).map(f=>f.user_id===currentUser.id?f.friend_id:f.user_id))];if(!ids.length){friendProfiles=[];renderFriends();return}const r=await supabaseClient.from('profiles').select('id,username,avatar_url').in('id',ids);if(r.error){console.error('Perfis de amigos:',r.error);return}friendProfiles=r.data||[];renderFriends()}
  async function subscribeProfile(){if(profileChannel){await supabaseClient.removeChannel(profileChannel);profileChannel=null}if(!currentUser)return;profileChannel=supabaseClient.channel('zuno-home-profile-'+currentUser.id).on('postgres_changes',{event:'UPDATE',schema:'public',table:'profiles',filter:'id=eq.'+currentUser.id},loadProfile).subscribe()}
  ['zuno:presence:sync','zuno:presence:join','zuno:presence:leave'].forEach(ev=>window.addEventListener(ev,renderFriends));

  async function enterMember(sessionUser){const seq=++bootSeq;currentUser=sessionUser;currentProfile=null;document.documentElement.dataset.zunoAuthState='loading-profile';if(loading)loading.style.display='flex';const ok=await loadProfile();if(seq!==bootSeq)return;if(!ok){showWelcome();return}showHome();loadFriends().catch(console.error);subscribeProfile().catch(console.error)}
  async function boot(){try{const{data,error}=await supabaseClient.auth.getSession();if(error)throw error;const user=data?.session?.user||null;if(!user){showWelcome();return}await enterMember(user)}catch(e){console.error(e);showWelcome()}}
  supabaseClient.auth.onAuthStateChange((event,session)=>{if(event==='SIGNED_OUT'){bootSeq++;currentUser=null;currentProfile=null;friendProfiles=[];if(profileChannel)supabaseClient.removeChannel(profileChannel).catch(()=>{});profileChannel=null;showWelcome();return}if((event==='SIGNED_IN'||event==='USER_UPDATED')&&session?.user){if(session.user.id===currentUser?.id&&currentProfile){currentUser=session.user;return}enterMember(session.user).catch(console.error)}});
  const logout=$('logoutButton');if(logout)logout.onclick=async()=>{logout.disabled=true;logout.textContent='Saindo...';try{if(profileChannel)await supabaseClient.removeChannel(profileChannel);await supabaseClient.auth.signOut()}finally{location.href='index.html'}};
  window.addEventListener('beforeunload',()=>{if(profileChannel)supabaseClient.removeChannel(profileChannel)});
  if('serviceWorker'in navigator)window.addEventListener('load',async()=>{try{const reg=await navigator.serviceWorker.register('./sw.js',{updateViaCache:'none'});reg.update().catch(()=>{})}catch(e){console.error(e)}});
  boot();
})();