(()=>{
if(window.__ZUNOPLAY_GLOBAL_BOOT_V350__)return;window.__ZUNOPLAY_GLOBAL_BOOT_V350__=true;
const V='350',page=(location.pathname.split('/').pop()||'index.html').toLowerCase(),home=page==='index.html',moments=page==='pulso.html',pub=new Set(['login.html','cadastro.html','entrada.html']),social=['amigos.html','conversas.html','comunidades.html','perfil.html','notificacoes.html'],profile=['perfil.html','avatar.html'],rooms=['salas.html'],games=['jogos.html','historico.html','zuno-stack.html'];
document.documentElement.classList.add('zuno-fluid-page');document.documentElement.dataset.zunoPage=page.replace('.html','');
if('serviceWorker'in navigator&&page==='perfil.html'){const key='zuno-profile-sw-v350-reloaded';navigator.serviceWorker.addEventListener('controllerchange',()=>{if(sessionStorage.getItem(key)==='1')return;sessionStorage.setItem(key,'1');location.reload()});window.addEventListener('load',()=>navigator.serviceWorker.getRegistration().then(reg=>reg?.update()).catch(()=>{}),{once:true})}
const ver=f=>f+(f.includes('?')?'&':'?')+'v='+V;
function css(id,f){if(document.getElementById(id))return;const l=document.createElement('link');l.id=id;l.rel='stylesheet';l.href=new URL(ver(f),location.href).href;document.head.appendChild(l)}
function js(id,f,done){const old=document.getElementById(id);if(old){if(old.dataset.loaded==='1')done?.();else if(done)old.addEventListener('load',done,{once:true});return}const s=document.createElement('script');s.id=id;s.src=new URL(ver(f),location.href).href;s.defer=true;s.onload=()=>{s.dataset.loaded='1';done?.()};s.onerror=()=>console.error('ZunoPlay: falha ao carregar '+f);document.head.appendChild(s)}
css('zunoplay-fluid-ui-style','./zuno-fluid-ui.css');css('zunoplay-loading-style','./zuno-loading-v1.css');css('zunoplay-mobile-top-gap-fix','./zuno-mobile-top-gap-fix.css');js('zunoplay-loading-runtime','./zuno-loading-v1.js');js('zunoplay-navigation-policy','./zuno-navigation-policy-v1.js');css('zunoplay-brand-official-style','./zuno-brand-official.css');js('zunoplay-brand-official-script','./zuno-brand-official.js',()=>{css('zunoplay-presence-official-style','./zuno-presence-official.css');js('zunoplay-presence-official-script','./zuno-presence-official.js')});
if(home){css('zunoplay-home-premium-v1-style','./zuno-home-premium-v1.css');css('zunoplay-home-motion-v1-style','./zuno-home-motion-v1.css');css('zunoplay-home-world-v1-style','./zuno-home-world-v1.css');css('zunoplay-home-priorities-v1-style','./zuno-home-priorities-v1.css');css('zunoplay-home-avatar-motion-v1-style','./zuno-home-avatar-motion-v1.css');js('zunoplay-room-history-v1','./zuno-room-history-v1.js');js('zunoplay-home-v2-script','./zuno-home-v2.js')}
if(window.supabase?.createClient&&!window.ZunoSupabaseClient){try{const canonical=window.supabase.createClient('https://rliymfbbhqoejgfvsbuu.supabase.co','sb_publishable_E4go4X7yZ6d-aXnKAT-fWw_Y8uHIJT0',{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});window.ZunoSupabaseClient=canonical;window.__zunoSupabaseClient=canonical}catch(e){console.error('ZunoPlay: Supabase bootstrap',e)}}
js('zunoplay-avatar-renderer','./avatar-renderer.js',()=>js('zunoplay-official-avatars','./zuno-official-avatars.js',()=>js('zunoplay-avatar-home-sync','./avatar-home-sync.js')));
let shellLoaded=false;
function loadAuthenticatedShell(){if(shellLoaded||pub.has(page))return;shellLoaded=true;js('zunoplay-onboarding-guard','./zuno-onboarding-guard.js');js('zunoplay-notification-engine','./zuno-notifications.js');js('zunoplay-settings-runtime','./zuno-settings-runtime-v1.js');css('zunoplay-xp-ui-style','./zuno-xp-ui-v1.css');js('zunoplay-xp-ui-script','./zuno-xp-ui-v1.js');css('zunoplay-canonical-navigation-style','./zuno-global-navigation-v1.css');js('zunoplay-canonical-navigation-script','./zuno-global-navigation-v1.js');if(!moments){css('zunoplay-mini-profile-style','./zuno-mini-profile-v1.css');js('zunoplay-mini-profile-script','./zuno-mini-profile-v1.js');css('zunoplay-message-entry-style','./zuno-message-entry.css');js('zunoplay-message-entry-script','./zuno-message-entry.js')}if(!moments){css('zunoplay-global-chrome-style','./zuno-global-chrome.css');js('zunoplay-global-chrome-script','./zuno-global-chrome.js')}js('zunoplay-avatar-social-sync','./zuno-avatar-social-sync.js');js('zunoplay-integration-phase4','./zuno-integration-phase4.js')}
function loadFriendsExperience(){css('zunoplay-friends-experience-style','./zuno-friends-experience.css');js('zunoplay-friends-experience-script','./zuno-friends-experience.js')}
function loadFriendRequests(){css('zunoplay-friend-requests-style','./zuno-friend-requests.css');js('zunoplay-friend-requests-script','./zuno-friend-requests.js')}
function syncHomeShell(){if(!home)return;const member=document.documentElement.dataset.zunoAuthState==='member';document.documentElement.classList.toggle('zuno-member-shell',member);document.documentElement.classList.toggle('zuno-guest-shell',!member);if(member){loadAuthenticatedShell();loadFriendsExperience()}}
if(!pub.has(page)&&!home)loadAuthenticatedShell();
if(home){syncHomeShell();new MutationObserver(records=>{if(records.some(r=>r.type==='attributes'&&r.attributeName==='data-zuno-auth-state'))syncHomeShell()}).observe(document.documentElement,{attributes:true,attributeFilter:['data-zuno-auth-state']});window.addEventListener('zuno:home-resumed',syncHomeShell)}
if(social.includes(page)){css('zunoplay-social-style','./zuno-social.css');js('zunoplay-social-script','./zuno-social.js')}
if(page==='amigos.html'){loadFriendsExperience();loadFriendRequests()}
if(page==='perfil.html')loadFriendRequests();
if(games.includes(page)){css('zunoplay-game-progression-style','./zuno-game-progression.css');js('zunoplay-game-progression','./zuno-game-progression.js');css('zunoplay-games-stage7-style','./zuno-games-stage7.css');js('zunoplay-games-stage7-script','./zuno-games-stage7.js')}
if(page==='zuno-stack.html'){js('zunoplay-room-game-return','./zuno-room-game-return.js');js('zunoplay-stack-lobby-v2','./zuno-stack-lobby-v2.js')}
if(!home&&!pub.has(page)&&!moments)css('zunoplay-ui-components','./zuno-ui-components.css');
if(profile.includes(page)){css('zunoplay-profile-avatar-stage5-style','./zuno-profile-avatar-stage5.css');js('zunoplay-profile-avatar-stage5-script','./zuno-profile-avatar-stage5.js')}
if(!home)js('zunoplay-realtime-global','./realtime-global.js');else{const loadHomeRealtime=()=>{if(document.documentElement.dataset.zunoAuthState==='member')js('zunoplay-realtime-global','./realtime-global.js')};loadHomeRealtime();new MutationObserver(loadHomeRealtime).observe(document.documentElement,{attributes:true,attributeFilter:['data-zuno-auth-state']})}
})();
