(()=>{
if(window.__ZUNOPLAY_GLOBAL_BOOT_V251__)return;window.__ZUNOPLAY_GLOBAL_BOOT_V251__=true;
const V='251',page=(location.pathname.split('/').pop()||'index.html').toLowerCase(),home=page==='index.html',pub=new Set(['login.html','cadastro.html','entrada.html']),social=['amigos.html','conversas.html','comunidades.html','perfil.html','notificacoes.html'],profile=['perfil.html','avatar.html'],rooms=['salas.html','sala.html'],games=['jogos.html','historico.html','zuno-stack.html'],roomGames=['zuno-stack.html'];
const ver=f=>f+(f.includes('?')?'&':'?')+'v='+V;
function css(id,f){if(document.getElementById(id))return;const l=document.createElement('link');l.id=id;l.rel='stylesheet';l.href=new URL(ver(f),location.href).href;document.head.appendChild(l)}
function js(id,f,done){const old=document.getElementById(id);if(old){if(old.dataset.loaded==='1')done?.();else if(done)old.addEventListener('load',done,{once:true});return}const s=document.createElement('script');s.id=id;s.src=new URL(ver(f),location.href).href;s.defer=true;s.onload=()=>{s.dataset.loaded='1';done?.()};s.onerror=()=>console.error('ZunoPlay: falha ao carregar '+f);document.head.appendChild(s)}
css('zunoplay-brand-official-style','./zuno-brand-official.css');js('zunoplay-brand-official-script','./zuno-brand-official.js',()=>{css('zunoplay-presence-official-style','./zuno-presence-official.css');js('zunoplay-presence-official-script','./zuno-presence-official.js')});
if(home){js('zunoplay-home-auth-gate','./zuno-home-auth-gate.js');css('zunoplay-home-premium-v1-style','./zuno-home-premium-v1.css');js('zunoplay-home-v2-script','./zuno-home-v2.js')}
if(window.supabase?.createClient&&!window.ZunoSupabaseClient){try{const originalCreate=window.supabase.createClient.bind(window.supabase);const canonical=originalCreate('https://rliymfbbhqoejgfvsbuu.supabase.co','sb_publishable_E4go4X7yZ6d-aXnKAT-fWw_Y8uHIJT0',{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});window.ZunoSupabaseClient=canonical;window.__zunoSupabaseClient=canonical;if(page==='sala.html'){window.supabase.createClient=(url,key,options)=>{if(url==='https://rliymfbbhqoejgfvsbuu.supabase.co'&&key==='sb_publishable_E4go4X7yZ6d-aXnKAT-fWw_Y8uHIJT0')return canonical;return originalCreate(url,key,options)}}}catch(e){console.error('ZunoPlay: Supabase bootstrap',e)}}
if(!pub.has(page)){js('zunoplay-onboarding-guard','./zuno-onboarding-guard.js');js('zunoplay-notification-engine','./zuno-notifications.js');js('zunoplay-settings-runtime','./zuno-settings-runtime-v1.js');css('zunoplay-canonical-navigation-style','./zuno-global-navigation-v1.css');js('zunoplay-canonical-navigation-script','./zuno-global-navigation-v1.js');css('zunoplay-mini-profile-style','./zuno-mini-profile-v1.css');js('zunoplay-mini-profile-script','./zuno-mini-profile-v1.js')}
if(!pub.has(page)&&page!=='sala.html'){css('zunoplay-global-chrome-style','./zuno-global-chrome.css');js('zunoplay-global-chrome-script','./zuno-global-chrome.js')}
if(social.includes(page)){css('zunoplay-social-style','./zuno-social.css');js('zunoplay-social-script','./zuno-social.js')}
if(games.includes(page)){css('zunoplay-game-progression-style','./zuno-game-progression.css');js('zunoplay-game-progression','./zuno-game-progression.js')}
if(!home&&!pub.has(page)&&page!=='sala.html')css('zunoplay-ui-components','./zuno-ui-components.css');
if(profile.includes(page)){css('zunoplay-profile-avatar-stage5-style','./zuno-profile-avatar-stage5.css');js('zunoplay-profile-avatar-stage5-script','./zuno-profile-avatar-stage5.js')}
if(page==='sala.html'){css('zunoplay-room-stage5','./zuno-room-experience.css');css('zunoplay-room-fit','./zuno-room-fit.css');css('zunoplay-room-extras','./zuno-room-extras.css');js('zunoplay-room-connection-fix','./zuno-room-connection-fix.js');js('zunoplay-realtime-global','./realtime-global.js',()=>{js('zunoplay-room-session-guard','./room-session-guard.js');js('zunoplay-room-experience-stage5','./zuno-room-experience.js');js('zunoplay-room-voice','./voz-sala.js')})}else{js('zunoplay-realtime-global','./realtime-global.js');if(roomGames.includes(page))js('zunoplay-room-game-return','./zuno-room-game-return.js')}
if(rooms.includes(page)){css('zunoplay-rooms-stage6-style','./zuno-rooms-stage6.css');js('zunoplay-rooms-stage6-script','./zuno-rooms-stage6.js')}
if(games.includes(page)){css('zunoplay-games-stage7-style','./zuno-games-stage7.css');js('zunoplay-games-stage7-script','./zuno-games-stage7.js')}
if(page==='zuno-stack.html'){css('zunoplay-stack-premium-style','./zuno-stack-premium.css');css('zunoplay-stack-strategic-style','./zuno-stack-strategic.css');css('zunoplay-stack-islands-style','./zuno-stack-islands.css');css('zunoplay-stack-objective-style','./zuno-stack-objective.css');css('zunoplay-stack-relay-advanced-style','./zuno-stack-relay-advanced.css');css('zunoplay-stack-layout-v1-style','./zuno-stack-layout-v1.css');css('zunoplay-stack-visual-style','./zuno-stack-visual.css');css('zunoplay-stack-visual-final-style','./zuno-stack-visual-final.css');css('zunoplay-stack-lobby-style','./zuno-stack-lobby.css');js('zunoplay-stack-performance','./zuno-stack-performance.js');js('zunoplay-stack-premium','./zuno-stack-premium.js');js('zunoplay-stack-social','./zuno-stack-social.js');js('zunoplay-stack-progression','./zuno-stack-progression.js');js('zunoplay-stack-content','./zuno-stack-content.js');js('zunoplay-stack-mobile-shell','./zuno-stack-mobile-shell.js');js('zunoplay-stack-strategic','./zuno-stack-strategic.js');js('zunoplay-stack-islands','./zuno-stack-islands.js');js('zunoplay-stack-objective','./zuno-stack-objective.js');js('zunoplay-stack-relay-advanced','./zuno-stack-relay-advanced.js')}
if(!pub.has(page)){css('zunoplay-final-audit-style','./zuno-final-audit.css');js('zunoplay-final-audit-script','./zuno-final-audit.js')}
js('zunoplay-avatar-renderer','./avatar-renderer.js',()=>js('zunoplay-avatar-home-sync','./avatar-home-sync.js'));if(!pub.has(page))js('zunoplay-integration-phase4','./zuno-integration-phase4.js');if(page==='sala.html'){css('zunoplay-voice-room-official-style','./zuno-voice-room-official.css');js('zunoplay-voice-room-official-script','./zuno-voice-room-official.js')}
})();