(()=>{
if(window.__ZUNOPLAY_GLOBAL_BOOT_V335__)return;window.__ZUNOPLAY_GLOBAL_BOOT_V335__=true;
const V='335',page=(location.pathname.split('/').pop()||'index.html').toLowerCase(),home=page==='index.html',moments=page==='pulso.html',pub=new Set(['login.html','cadastro.html','entrada.html']),social=['amigos.html','conversas.html','comunidades.html','perfil.html','notificacoes.html'],profile=['perfil.html','avatar.html'],rooms=['salas.html'],games=['jogos.html','historico.html','zuno-stack.html'];
const ver=f=>f+(f.includes('?')?'&':'?')+'v='+V;
function css(id,f){if(document.getElementById(id))return;const l=document.createElement('link');l.id=id;l.rel='stylesheet';l.href=new URL(ver(f),location.href).href;document.head.appendChild(l)}
function js(id,f,done){const old=document.getElementById(id);if(old){if(old.dataset.loaded==='1')done?.();else if(done)old.addEventListener('load',done,{once:true});return}const s=document.createElement('script');s.id=id;s.src=new URL(ver(f),location.href).href;s.defer=true;s.onload=()=>{s.dataset.loaded='1';done?.()};s.onerror=()=>console.error('ZunoPlay: falha ao carregar '+f);document.head.appendChild(s)}
css('zunoplay-brand-official-style','./zuno-brand-official.css');js('zunoplay-brand-official-script','./zuno-brand-official.js',()=>{css('zunoplay-presence-official-style','./zuno-presence-official.css');js('zunoplay-presence-official-script','./zuno-presence-official.js')});
if(home){css('zunoplay-home-premium-v1-style','./zuno-home-premium-v1.css');css('zunoplay-home-motion-v1-style','./zuno-home-motion-v1.css');css('zunoplay-home-world-v1-style','./zuno-home-world-v1.css');js('zunoplay-room-history-v1','./zuno-room-history-v1.js');js('zunoplay-home-v2-script','./zuno-home-v2.js');js('zunoplay-moments-entry','./zuno-moments-entry.js')}
if(window.supabase?.createClient&&!window.ZunoSupabaseClient){try{const canonical=window.supabase.createClient('https://rliymfbbhqoejgfvsbuu.supabase.co','sb_publishable_E4go4X7yZ6d-aXnKAT-fWw_Y8uHIJT0',{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});window.ZunoSupabaseClient=canonical;window.__zunoSupabaseClient=canonical}catch(e){console.error('ZunoPlay: Supabase bootstrap',e)}}
if(!pub.has(page)){js('zunoplay-onboarding-guard','./zuno-onboarding-guard.js');js('zunoplay-notification-engine','./zuno-notifications.js');js('zunoplay-settings-runtime','./zuno-settings-runtime-v1.js');css('zunoplay-canonical-navigation-style','./zuno-global-navigation-v1.css');js('zunoplay-canonical-navigation-script','./zuno-global-navigation-v1.js');if(!moments){css('zunoplay-mini-profile-style','./zuno-mini-profile-v1.css');js('zunoplay-mini-profile-script','./zuno-mini-profile-v1.js');css('zunoplay-message-entry-style','./zuno-message-entry.css');js('zunoplay-message-entry-script','./zuno-message-entry.js')}}
if(!pub.has(page)&&!moments){css('zunoplay-global-chrome-style','./zuno-global-chrome.css');js('zunoplay-global-chrome-script','./zuno-global-chrome.js')}
if(social.includes(page)){css('zunoplay-social-style','./zuno-social.css');js('zunoplay-social-script','./zuno-social.js')}
if(games.includes(page)){css('zunoplay-game-progression-style','./zuno-game-progression.css');js('zunoplay-game-progression','./zuno-game-progression.js')}
if(!home&&!pub.has(page)&&!moments)css('zunoplay-ui-components','./zuno-ui-components.css');
if(profile.includes(page)){css('zunoplay-profile-avatar-stage5-style','./zuno-profile-avatar-stage5.css');js('zunoplay-profile-avatar-stage5-script','./zuno-profile-avatar-stage5.js')}
js('zunoplay-realtime-global','./realtime-global.js');
if(home||page==='amigos.html'){css('zunoplay-friends-experience-style','./zuno-friends-experience.css');js('zunoplay-friends-experience-script','./zuno-friends-experience.js')}
if(page==='amigos.html'||page==='perfil.html'){css('zunoplay-friend-requests-style','./zuno-friend-requests.css');js('zunoplay-friend-requests-script','./zuno-friend-requests.js')}
if(page==='zuno-stack.html')js('zunoplay-room-game-return','./zuno-room-game-return.js');
if(rooms.includes(page)){css('zunoplay-rooms-stage6-style','./zuno-rooms-stage6.css');js('zunoplay-rooms-stage6-script','./zuno-rooms-stage6.js')}
if(games.includes(page)){css('zunoplay-games-stage7-style','./zuno-games-stage7.css');js('zunoplay-games-stage7-script','./zuno-games-stage7.js')}
if(page==='zuno-stack.html')js('zunoplay-stack-lobby-v2','./zuno-stack-lobby-v2.js');
js('zunoplay-avatar-renderer','./avatar-renderer.js',()=>js('zunoplay-official-avatars','./zuno-official-avatars.js',()=>{js('zunoplay-avatar-home-sync','./avatar-home-sync.js');if(!pub.has(page))js('zunoplay-avatar-social-sync','./zuno-avatar-social-sync.js')}));if(!pub.has(page))js('zunoplay-integration-phase4','./zuno-integration-phase4.js');
})();