(()=>{
  if(window.__ZUNO_ROOM_PRESENCE__)return;window.__ZUNO_ROOM_PRESENCE__=true;
  const q=new URLSearchParams(location.search),room=q.get('room')||q.get('room_id')||q.get('id')||sessionStorage.getItem('zunoplay_room_id');
  let scope=null,user=null,currentState={},directory=[],directoryLoadedAt=0,bindScheduled=false,hasSynced=false;
  const reconnectTimers=new Map();
  const style=document.createElement('style');style.textContent=`.presence-status{font-size:9px;margin-top:3px;color:#4ade80}.is-away .avatar{filter:saturate(.55);opacity:.78}.is-away .presence-status{color:#fbbf24}.is-reconnecting .avatar{opacity:.68;filter:saturate(.65)}.is-reconnecting .presence-status{color:#fbbf24}.is-offline .presence-status{color:#858697}.avatar-slot.presence-vacant{cursor:default;pointer-events:none}.avatar-slot.presence-vacant>*{display:none!important}.avatar-slot.presence-vacant:before{content:'＋';width:62px;height:62px;border-radius:50%;border:1.5px solid #756c95;background:rgba(255,255,255,.015);display:grid;place-items:center;color:#8b8b9b;font-size:31px;font-weight:200}.avatar-slot.presence-vacant:after{content:'Livre';margin-top:7px;font-size:9px;color:#66687a}.member.presence-vacant,.top-avatar.presence-vacant{display:none!important}`;document.head.appendChild(style);
  function waitForCore(){if(window.ZunoRealtime)return Promise.resolve(window.ZunoRealtime);return new Promise((resolve,reject)=>{let settled=false;const done=()=>{if(!settled&&window.ZunoRealtime){settled=true;resolve(window.ZunoRealtime)}};window.addEventListener('zuno:realtime-installed',done,{once:true});setTimeout(()=>{if(settled)return;settled=true;window.ZunoRealtime?resolve(window.ZunoRealtime):reject(new Error('ZunoRealtime indisponível'))},5000)})}
  const memberIds=()=>directory.map(x=>x.user_id).filter(Boolean);
  const seatOf=id=>directory.find(x=>String(x.user_id)===String(id))?.seat_index;
  function statusText(v){return v==='speaking'?'🎙️ Falando':v==='listening'?'🎧 Ouvindo':v==='away'?'⏸️ Ausente':v==='reconnecting'?'↻ Reconectando':v==='offline'?'○ Offline':'● Online'}
  function rawStateFor(id){const list=currentState?.[id];if(!Array.isArray(list)||!list.length)return 'offline';const active=[...list].reverse().find(p=>p?.status&&p.status!=='offline');return active?.status||list[list.length-1]?.status||'online'}
  function stateFor(id){const node=document.querySelector('.avatar-slot[data-user-id="'+CSS.escape(String(id))+'"]');return node?.classList.contains('is-reconnecting')?'reconnecting':rawStateFor(id)}
  function activeIds(){if(!hasSynced)return memberIds();return memberIds().filter(id=>rawStateFor(id)!=='offline')}
  function updateVisibleCount(){if(!hasSynced)return;const count=activeIds().length;const rc=document.getElementById('roomCountText'),sc=document.getElementById('sheetCount');if(rc)rc.textContent=count+' '+(count===1?'pessoa':'pessoas');if(sc)sc.textContent=count+' '+(count===1?'participante':'participantes');document.querySelectorAll('.people-count').forEach(el=>el.textContent=String(count))}
  function applyStatus(id,state){const value=state||'offline',gone=hasSynced&&value==='offline',escaped=CSS.escape(String(id));document.querySelectorAll('.avatar-slot[data-user-id="'+escaped+'"],.member[data-user-id="'+escaped+'"],.top-avatar[data-user-id="'+escaped+'"]').forEach(el=>{el.dataset.presence=value;el.classList.toggle('presence-vacant',gone);el.classList.toggle('is-reconnecting',value==='reconnecting');el.classList.toggle('is-speaking',!gone&&value==='speaking');el.classList.toggle('is-away',!gone&&value==='away');el.classList.toggle('is-offline',gone);const badge=el.querySelector('.presence-status');if(badge)badge.textContent=statusText(value)})}
  function dispatchSeatMap(){const seats=Array.from({length:8},(_,seat_index)=>{const row=directory.find(x=>Number(x.seat_index)===seat_index);return{seat_index,user_id:row?.user_id||null,status:row?stateFor(row.user_id):'vacant'}});window.dispatchEvent(new CustomEvent('zuno:room-seat-map',{detail:{room_id:room,seats}}))}
  function applyAllStatuses(){memberIds().forEach(id=>applyStatus(id,stateFor(id)));updateVisibleCount();dispatchSeatMap()}
  async function refreshDirectory(force=false){if(!force&&directory.length&&Date.now()-directoryLoadedAt<4000)return;const core=await waitForCore();const{data,error}=await core.client.from('room_members').select('user_id,seat_index,joined_at').eq('room_id',room).order('seat_index',{ascending:true});if(error)return;directory=(data||[]).filter(x=>x.user_id!=null&&Number.isFinite(Number(x.seat_index))).map(x=>({...x,seat_index:Number(x.seat_index)}));directoryLoadedAt=Date.now()}
  function ensureBadge(el){if(!el||el.querySelector('.presence-status'))return;const badge=document.createElement('div');badge.className='presence-status';el.appendChild(badge)}
  function bindBySeat(){const bySeat=new Map(directory.map(row=>[Number(row.seat_index),row]));document.querySelectorAll('.avatar-slot[data-seat-index]').forEach(el=>{const row=bySeat.get(Number(el.dataset.seatIndex));if(!row)return;el.dataset.userId=String(row.user_id);ensureBadge(el);applyStatus(row.user_id,stateFor(row.user_id))});document.querySelectorAll('.member[data-seat-index]').forEach(el=>{const row=bySeat.get(Number(el.dataset.seatIndex));if(!row)return;el.dataset.userId=String(row.user_id);ensureBadge(el);applyStatus(row.user_id,stateFor(row.user_id))})}
  function bindTop(){const active=directory.filter(row=>!hasSynced||rawStateFor(row.user_id)!=='offline').sort((a,b)=>a.seat_index-b.seat_index);document.querySelectorAll('.top-avatar').forEach((el,index)=>{const row=active[index];if(!row)return;el.dataset.userId=String(row.user_id);applyStatus(row.user_id,stateFor(row.user_id))})}
  async function bindInterface(){bindScheduled=false;await refreshDirectory();bindBySeat();bindTop();applyAllStatuses()}
  function scheduleBind(force=false){if(force)directoryLoadedAt=0;if(bindScheduled)return;bindScheduled=true;requestAnimationFrame(()=>bindInterface().catch(console.error))}
  function cancelReconnect(id){const t=reconnectTimers.get(String(id));if(t){clearTimeout(t);reconnectTimers.delete(String(id))}}
  function startReconnect(id){if(!id)return;cancelReconnect(id);applyStatus(id,'reconnecting');const t=setTimeout(()=>{reconnectTimers.delete(String(id));if(rawStateFor(id)==='offline'){applyStatus(id,'offline');updateVisibleCount();dispatchSeatMap()}},3500);reconnectTimers.set(String(id),t)}
  function sync(){hasSynced=true;currentState=scope?.state()||{};memberIds().forEach(id=>{if(rawStateFor(id)!=='offline')cancelReconnect(id)});scheduleBind();window.dispatchEvent(new CustomEvent('zuno:room-presence-sync',{detail:currentState}))}
  async function start(){if(!room||scope)return;const core=await waitForCore();await core.start();user=core.getUser();if(!user)return;await refreshDirectory(true);scope=core.presence.scope('zunoplay-presence-'+room,user.id,{user_id:user.id,room_id:room,status:'online',seat_index:seatOf(user.id),at:new Date().toISOString()});scope.on('sync',sync).on('join',({key,newPresences})=>{hasSynced=true;currentState=scope.state();cancelReconnect(key);scheduleBind();window.dispatchEvent(new CustomEvent('zuno:room-presence-join',{detail:{key,newPresences,seat_index:seatOf(key)}}))}).on('leave',({key,leftPresences})=>{hasSynced=true;currentState=scope.state();startReconnect(key);updateVisibleCount();scheduleBind(true);window.dispatchEvent(new CustomEvent('zuno:room-presence-leave',{detail:{key,leftPresences,seat_index:seatOf(key)}}))});await scope.subscribe();sync();const roots=[document.getElementById('roomStage'),document.getElementById('members'),document.getElementById('topPeople')].filter(Boolean);const observer=new MutationObserver(()=>scheduleBind(true));roots.forEach(root=>observer.observe(root,{childList:true,subtree:false}))}
  window.zunoSetRoomPresence=async state=>{if(!scope)await start();if(!scope||!user)return false;await scope.track({user_id:user.id,room_id:room,status:state,seat_index:seatOf(user.id),at:new Date().toISOString()});currentState=scope.state();applyStatus(user.id,state);updateVisibleCount();dispatchSeatMap();return true};
  window.ZunoRoomPresence={start,getState:()=>currentState,set:window.zunoSetRoomPresence,getUser:()=>user,getSeatMap:()=>Array.from({length:8},(_,seat_index)=>{const row=directory.find(x=>x.seat_index===seat_index);return{seat_index,user_id:row?.user_id||null,status:row?stateFor(row.user_id):'vacant'}}),refresh:()=>{directoryLoadedAt=0;return bindInterface()}};
  start().catch(error=>console.error('Zuno room presence',error));window.addEventListener('beforeunload',()=>{reconnectTimers.forEach(clearTimeout);scope?.close?.().catch?.(()=>{})});
})();