(()=>{
if(window.__ZUNOPLAY_HOME_V2__)return;window.__ZUNOPLAY_HOME_V2__=true;
const page=(location.pathname.split('/').pop()||'index.html').toLowerCase();if(page!=='index.html')return;
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
function titleOf(card){return ($('h2',card)?.textContent||'').trim().toLowerCase()}
function cardBy(name){return $$('#homeScreen .menu-card').find(c=>titleOf(c).includes(name))}
function removeRedundantNav(){const grid=$('#homeScreen .menu-grid');if(!grid)return;$$('.menu-card',grid).forEach(card=>{const t=titleOf(card);if(t.includes('salas de voz')||t==='jogos'||t.includes('histórico'))card.remove()});grid.dataset.homeV2='1'}
function renameActivityCards(){const conversations=cardBy('conversa');if(conversations){$('h2',conversations).textContent='Conversas';$('p',conversations).textContent='Veja mensagens e novidades';conversations.dataset.homeRole='activity'}const communities=cardBy('comun');if(communities){$('h2',communities).textContent='Comunidades';$('p',communities).textContent='Descubra o que está movimentando seus grupos';communities.dataset.homeRole='activity'}const stack=cardBy('zuno stack');if(stack){stack.dataset.homeRole='featured';$('p',stack).textContent='Seu jogo em destaque · Jogar agora'}}
function makeSection(cls,title,sub){const s=document.createElement('section');s.className='zhome-v2-section '+cls;s.innerHTML=`<div class="zhome-v2-kicker">${sub}</div><div class="zhome-v2-title">${title}</div>`;return s}
function mountNow(){const grid=$('#homeScreen .menu-grid');if(!grid||$('#zhomeNow'))return;const s=makeSection('zhome-v2-now','Para você agora','Zuno recomenda');s.id='zhomeNow';s.innerHTML+=`<div class="zhome-v2-rail zhome-v2-recommend-rail"><button class="zhome-v2-mission" type="button" onclick="location.href='jogos.html'"><span class="zhome-v2-mission-copy"><b>Desafio Zuno</b><small>Continue evoluindo sua Aura e desbloqueie novas conquistas.</small></span><span class="zhome-v2-arrow">›</span></button></div>`;grid.parentNode.insertBefore(s,grid)}
function mountWorldLabel(){const grid=$('#homeScreen .menu-grid');if(!grid||$('#zhomeWorldLabel'))return;const h=document.createElement('div');h.id='zhomeWorldLabel';h.className='zhome-v2-world-label';h.innerHTML='<span>Seu mundo</span><small>Deslize para explorar</small>';grid.parentNode.insertBefore(h,grid)}
function mountPopularGames(){const stack=cardBy('zuno stack');const world=$('#zhomeWorldLabel');if(!stack||!world)return;let section=$('#zhomePopularGames');if(!section){section=makeSection('zhome-v2-popular','Jogos populares','Jogue agora');section.id='zhomePopularGames';const rail=document.createElement('div');rail.className='zhome-v2-rail zhome-v2-games-rail';section.appendChild(rail);world.parentNode.insertBefore(section,world)}const rail=$('.zhome-v2-games-rail',section);if(stack.parentElement!==rail)rail.appendChild(stack);section.dataset.items=String(rail.children.length)}
function compactFriends(){const friends=$('#friendsStrip');const section=friends?.closest('.section');if(!section)return;section.classList.add('zhome-v2-friends');const count=Number(($('#onlineCount')?.textContent||'0').replace(/\D/g,''))||0;section.dataset.empty=count<1?'1':'0';const empty=$('.empty-friends',friends)||$('.empty-inline',friends);if(count<1&&empty)empty.textContent='Encontre pessoas para começar seu mundo social.'}
function activeRoomsAsLiveContent(){const rooms=$('#activeRooms');const section=rooms?.closest('.section');const now=$('#zhomeNow');if(!section||!rooms)return;section.classList.add('zhome-v2-live');section.id='zhomeLiveNow';const title=$('.section-title',section);if(title)title.innerHTML='<span class="dot-online"></span> Acontecendo agora';const link=$('.section-link',section);if(link){link.textContent='Explorar';link.href='salas.html'}rooms.classList.add('zhome-v2-rail','zhome-v2-rooms-rail');const hasRealRoom=!!$('.room-card',rooms);section.hidden=!hasRealRoom;section.dataset.hasContent=hasRealRoom?'1':'0';if(hasRealRoom&&now&&now.nextElementSibling!==section)now.insertAdjacentElement('afterend',section)}
function makeSocialRail(){const grid=$('#homeScreen .menu-grid');if(!grid)return;grid.classList.add('zhome-v2-rail','zhome-v2-social-rail')}
function orderFriendsAfterWorld(){const friends=$('#friendsStrip')?.closest('.section');const grid=$('#homeScreen .menu-grid');if(friends&&grid&&grid.nextElementSibling!==friends)grid.insertAdjacentElement('afterend',friends)}
function removePermanentGuide(){document.querySelectorAll('#homeScreen .zuno-home-guide').forEach(el=>el.remove())}
function mount(){const home=$('#homeScreen');if(!home)return;home.dataset.homeExperience='v2';removePermanentGuide();removeRedundantNav();renameActivityCards();mountNow();mountWorldLabel();mountPopularGames();activeRoomsAsLiveContent();makeSocialRail();compactFriends();orderFriendsAfterWorld()}
let raf=0;const schedule=()=>{if(raf)return;raf=requestAnimationFrame(()=>{raf=0;mount()})};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',mount,{once:true});else mount();new MutationObserver(schedule).observe(document.documentElement,{subtree:true,childList:true,characterData:true});['zuno:presence:sync','zuno:presence:join','zuno:presence:leave','zuno:brand-ready','zuno:home-current-ready','zuno:home-resumed'].forEach(e=>window.addEventListener(e,schedule));
})();