(()=>{
if(window.__ZUNO_CORE_V02__)return;window.__ZUNO_CORE_V02__=true;
const $=id=>document.getElementById(id),canvas=$('arena'),ctx=canvas.getContext('2d',{alpha:false}),W=canvas.width,H=canvas.height,CX=W/2,CY=H/2,R=398;
const q=new URLSearchParams(location.search),roomId=q.get('room')||sessionStorage.getItem('zunoplay_room_id')||'',fromRoom=q.get('from')==='sala'&&!!roomId;
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),rand=(a,b)=>Math.random()*(b-a)+a,dist=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y),now=()=>performance.now();
const botData=[['Nova','#45dfff','collector'],['Kiro','#ff6dbd','hunter'],['Lumi','#ffd166','support'],['Mako','#6cffb2','collector'],['Yara','#8e6cff','support'],['Nox','#ff8c5a','chaos'],['Bibi','#77a9ff','hunter']];
let sb=null,user=null,userName='Você',avatarConfig=null,userAvatar=null,botMale=null,botFemale=null,players=[],frags=[],particles=[],portals=[],shockwaves=[],pads=[],active=false,startedAt=0,last=0,raf=0,phase='collect',eventName='',eventUntil=0,finalStarted=false,matchEnded=false,linkTarget=null,linkUntil=0,linkCooldown=0,jumpingUntil=0,jumpCooldown=0,echoUntil=0,core={x:CX,y:CY,r:32,vx:82,vy:58},coreCarrier=null,controls={x:0,y:0,keys:new Set()},joyPointer=null,best=Number(localStorage.getItem('zunoplay_zuno_core_best')||0),lastHint='';
const stats={links:0,fragments:0,echoes:0,coreSeconds:0,rare:0};
function announce(t){$('live').textContent=t}function banner(t){$('banner').textContent=t;announce(t)}function formatTime(ms){const s=Math.max(0,Math.ceil(ms/1000)),m=Math.floor(s/60),r=s%60;return String(m).padStart(2,'0')+':'+String(r).padStart(2,'0')}
function phaseText(){if(phase==='collect')return['FASE 1','Coleta'];if(phase==='converge')return['FASE 2','Convergência'];if(phase==='rupture')return['FASE 3','Ruptura'];return['CORE FINAL','Capture e defenda']}
function scoreOf(p){return Math.round((p.energy||0)+(p.coreTime||0)*46+(p.links||0)*72-(p.echoes||0)*42)}function sorted(){return [...players].sort((a,b)=>scoreOf(b)-scoreOf(a))}function me(){return players[0]}
function nearestLinkCandidate(max=176){const p=me();if(!p)return null;let bestP=null,bestD=Infinity;for(const other of players.slice(1)){if((other.echoUntil||0)>now())continue;const d=dist(p,other);if(d<bestD){bestD=d;bestP=other}}return bestD<=max?bestP:null}
function updateHud(){const p=me()||{energy:0},t=now(),rank=Math.max(1,sorted().findIndex(x=>x.id==='me')+1),candidate=nearestLinkCandidate();$('rank').textContent=rank+'º/8';$('energyText').textContent=Math.round(p.energy||0);$('links').textContent=stats.links;$('coreTime').textContent=stats.coreSeconds.toFixed(1)+'s';$('energyBar').style.width=clamp((p.energy||0)/300*100,0,100)+'%';const pt=phaseText();$('phaseKicker').textContent=pt[0];$('phaseTitle').textContent=pt[1];$('timer').textContent=formatTime(85000-(t-startedAt));const link=$('link'),hint=$('linkHint'),label=$('linkLabel'),linked=linkTarget&&linkUntil>t,cool=linkCooldown>t;link.classList.toggle('cool',cool&&!linked);link.classList.toggle('active',!!linked);link.classList.toggle('ready',!!candidate&&!cool&&!linked);if(linked){const mate=players.find(x=>x.id===linkTarget);label.textContent=mate?'LINK · '+mate.name:'LINK ATIVO';hint.textContent='⚡ PULSE LINK ATIVO · energia +50%';hint.classList.add('show')}else if(candidate&&!cool){label.textContent='LINK · '+candidate.name;hint.textContent='🔗 '+candidate.name+' está ao alcance';hint.classList.add('show')}else{label.textContent='LINK';hint.classList.remove('show')}if(linked&&linkTarget){const mate=players.find(x=>x.id===linkTarget);const txt=mate?'linked:'+mate.id:'';if(txt!==lastHint){lastHint=txt;announce('Pulse Link ativo com '+mate.name)}}else lastHint=''}
function createPlayer(id,name,x,y,color,isBot=false,role='collector',avatar=null){return{id,name,x,y,r:id==='me'?27:24,color,isBot,role,avatar,energy:0,links:0,echoes:0,coreTime:0,aiThink:0,target:null,echoUntil:0,botLinkTarget:null,botLinkUntil:0}}
function makePads(){pads=[];for(let i=0;i<7;i++){const a=i/7*Math.PI*2+.25,rr=i%2?255:292;pads.push({x:CX+Math.cos(a)*rr,y:CY+Math.sin(a)*rr,r:i%2?43:52,phase:rand(0,Math.PI*2)})}}
function reset(){players=[createPlayer('me',userName,CX,CY+150,'#c25cff',false,'player',userAvatar)];for(let i=0;i<7;i++){const a=i/7*Math.PI*2,meta=botData[i];players.push(createPlayer('b'+i,meta[0],CX+Math.cos(a)*250,CY+Math.sin(a)*250,meta[1],true,meta[2],i%2?botFemale:botMale))}frags=[];particles=[];portals=[];shockwaves=[];phase='collect';eventName='';eventUntil=0;finalStarted=false;matchEnded=false;linkTarget=null;linkUntil=0;linkCooldown=0;jumpingUntil=0;jumpCooldown=0;echoUntil=0;core={x:CX,y:CY,r:32,vx:82,vy:58};coreCarrier=null;stats.links=0;stats.fragments=0;stats.echoes=0;stats.coreSeconds=0;stats.rare=0;makePads();for(let i=0;i<15;i++)spawnFrag();startedAt=now();last=startedAt;active=true;$('overlay').classList.add('hide');banner('💎 Colete Fragmentos Core. O botão LINK acende quando alguém estiver ao alcance.');updateHud();cancelAnimationFrame(raf);raf=requestAnimationFrame(loop)}
function spawnFrag(){if(frags.length>=18)return;const a=rand(0,Math.PI*2),rr=rand(65,R-45),roll=Math.random(),kind=roll>.9?'rare':roll>.58?'medium':'small',value=kind==='rare'?30:kind==='medium'?16:9,r=kind==='rare'?12:kind==='medium'?9:7,color=kind==='rare'?'#ffd166':kind==='medium'?'#bd8cff':'#9bf3ff';frags.push({x:CX+Math.cos(a)*rr,y:CY+Math.sin(a)*rr,r,value,kind,color,spin:rand(0,Math.PI*2),pulse:rand(0,Math.PI*2)})}
function keepInArena(p){const dx=p.x-CX,dy=p.y-CY,d=Math.hypot(dx,dy),lim=R-p.r-3;if(d>lim){p.x=CX+dx/d*lim;p.y=CY+dy/d*lim}}
function burst(x,y,color,count=8){for(let i=0;i<count;i++)particles.push({x,y,vx:rand(-90,90),vy:rand(-90,90),life:rand(.35,.7),color,size:rand(2,5)})}
function setEcho(p,ms=3200){const t=now();if((p.echoUntil||0)>t)return;p.echoUntil=t+ms;p.echoes++;if(p.id==='me'){echoUntil=p.echoUntil;stats.echoes++;banner('👻 Echo Mode! Colete e se reposicione: você volta em alguns segundos.');burst(p.x,p.y,'#6be6ff',18)}if(coreCarrier===p.id){coreCarrier=null;core.x=p.x;core.y=p.y}}
function activateLink(){const t=now();if(!active||matchEnded||linkCooldown>t||echoUntil>t)return;const target=nearestLinkCandidate();if(!target){banner('🔗 Nenhum jogador ao alcance. Aproxime-se até o botão LINK acender.');return}linkTarget=target.id;linkUntil=t+6500;linkCooldown=t+1700;stats.links++;me().links++;target.links++;burst(me().x,me().y,'#64e9ff',12);burst(target.x,target.y,'#b568ff',12);banner('🔗 Pulse Link com '+target.name+'! Coleta +50% e transporte do Core mais rápido.');navigator.vibrate?.([20,35,20])}
function jump(){const t=now();if(!active||matchEnded||jumpCooldown>t||echoUntil>t)return;jumpingUntil=t+650;jumpCooldown=t+1750;const p=me(),m=Math.hypot(controls.x,controls.y);if(m>.1){p.x+=controls.x/m*55;p.y+=controls.y/m*55;keepInArena(p)}burst(p.x,p.y,'#bd87ff',8);navigator.vibrate?.(12)}
function collect(p,f,index){const linked=p.id==='me'&&linkTarget&&linkUntil>now(),gain=f.value*(linked?1.5:1);p.energy+=gain;if(p.id==='me'){stats.fragments++;if(f.kind==='rare')stats.rare++;burst(f.x,f.y,f.color,f.kind==='rare'?16:8);if(f.kind==='rare')banner('✨ Fragmento raro! +'+Math.round(gain)+' Energia');if(linked){const mate=players.find(x=>x.id===linkTarget);if(mate)mate.energy+=f.value*.3}}frags.splice(index,1);setTimeout(spawnFrag,120+Math.random()*280)}
function portalTouch(p){if(eventName!=='rift'||!portals.length)return;for(let i=0;i<portals.length;i++){const po=portals[i];if(Math.hypot(p.x-po.x,p.y-po.y)<35){const other=portals[(i+1)%portals.length];p.x=other.x+(Math.random()-.5)*42;p.y=other.y+(Math.random()-.5)*42;if(p.id==='me'){banner('🌀 Rift! Você atravessou a arena.');burst(p.x,p.y,'#b45cff',14)}break}}}
function updatePlayer(p,dt){const t=now(),echo=(p.echoUntil||0)>t;if(p.id==='me'){let x=controls.x,y=controls.y;if(controls.keys.has('arrowleft')||controls.keys.has('a'))x-=1;if(controls.keys.has('arrowright')||controls.keys.has('d'))x+=1;if(controls.keys.has('arrowup')||controls.keys.has('w'))y-=1;if(controls.keys.has('arrowdown')||controls.keys.has('s'))y+=1;let m=Math.hypot(x,y);if(m>1){x/=m;y/=m}let speed=echo?260:(eventName==='gravity'?240:208);if(coreCarrier==='me')speed*=linkTarget&&linkUntil>t?.84:.61;p.x+=x*speed*dt;p.y+=y*speed*dt;keepInArena(p);portalTouch(p)}else updateBot(p,dt);for(let i=frags.length-1;i>=0;i--){if(Math.hypot(p.x-frags[i].x,p.y-frags[i].y)<p.r+frags[i].r+5){collect(p,frags[i],i);break}}if(phase==='final')coreInteraction(p,dt)}
function targetFragment(p){let best=null,bd=Infinity;for(const f of frags){let d=Math.hypot(p.x-f.x,p.y-f.y);if(p.role==='hunter'&&f.kind==='rare')d*=.42;if(p.role==='collector'&&f.kind==='medium')d*=.75;if(d<bd){bd=d;best=f}}return best}
function maybeBotLink(p,t){if(p.botLinkUntil>t||Math.random()>.025)return;let best=null,bd=140;for(const o of players){if(o.id===p.id||(o.echoUntil||0)>t)continue;const d=dist(p,o);if(d<bd){bd=d;best=o}}if(best){p.botLinkTarget=best.id;p.botLinkUntil=t+rand(3500,5600);p.links++}}
function updateBot(p,dt){const t=now(),echo=(p.echoUntil||0)>t;maybeBotLink(p,t);if(t>p.aiThink){p.aiThink=t+rand(450,950);if(phase==='final'){if(p.role==='support'&&coreCarrier){const c=players.find(x=>x.id===coreCarrier);p.target=c||core}else if(coreCarrier&&coreCarrier!==p.id&&p.role==='hunter'){p.target=players.find(x=>x.id===coreCarrier)||core}else p.target=core}else if(p.role==='support'){const m=me();p.target=dist(p,m)<260?m:targetFragment(p)}else if(p.role==='chaos'&&eventName==='rift'&&portals.length)p.target=portals[Math.floor(Math.random()*portals.length)];else p.target=targetFragment(p)||{x:CX,y:CY}}let tx=p.target?.x??CX,ty=p.target?.y??CY,dx=tx-p.x,dy=ty-p.y,m=Math.hypot(dx,dy)||1,speed=echo?230:(eventName==='gravity'?215:p.role==='hunter'?188:178);if(coreCarrier===p.id)speed*=.66;p.x+=dx/m*speed*dt;p.y+=dy/m*speed*dt;keepInArena(p);portalTouch(p)}
function coreInteraction(p,dt){const t=now();if((p.echoUntil||0)>t)return;if(coreCarrier===p.id){p.coreTime+=dt;if(p.id==='me')stats.coreSeconds+=dt;core.x=p.x;core.y=p.y-34;return}if(coreCarrier){const c=players.find(x=>x.id===coreCarrier);if(c&&dist(p,c)<p.r+c.r+12&&Math.random()<dt*(p.isBot?1.05:.5)){coreCarrier=p.id;burst(p.x,p.y,'#ffd166',18);banner(p.id==='me'?'👑 Você ROUBOU o Core!':'⚡ '+p.name+' tomou o Core.')}}else if(Math.hypot(p.x-core.x,p.y-core.y)<p.r+core.r+7){coreCarrier=p.id;burst(core.x,core.y,'#f0a8ff',22);banner(p.id==='me'?'👑 CORE CAPTURADO! Fuja, faça Link e defenda a posse.':'⚡ '+p.name+' capturou o Core.')}}
function updateCore(dt){if(phase!=='final'||coreCarrier)return;core.x+=core.vx*dt;core.y+=core.vy*dt;const d=Math.hypot(core.x-CX,core.y-CY);if(d>R-60){const nx=(core.x-CX)/d,ny=(core.y-CY)/d,dot=core.vx*nx+core.vy*ny;core.vx-=2*dot*nx;core.vy-=2*dot*ny;core.x=CX+nx*(R-61);core.y=CY+ny*(R-61)}}
function triggerShockwave(){eventName='shock';eventUntil=now()+7200;shockwaves=[];banner('🌊 RUPTURA: pule sobre as ondas de choque!');for(let i=0;i<5;i++)shockwaves.push({born:now()+i*1250,speed:150,hit:false})}function triggerGravity(){eventName='gravity';eventUntil=now()+9000;banner('🌌 BAIXA GRAVIDADE: movimento acelerado. Aproveite para formar Links.')}function triggerRifts(){eventName='rift';eventUntil=now()+8800;portals=[{x:CX-R+82,y:CY-85},{x:CX+R-82,y:CY+85}];banner('🌀 RIFTS ABERTOS: use os portais para cruzar a arena.')}
function updateEvents(t,elapsed){if(!eventName){if(elapsed>18000&&elapsed<26000)triggerShockwave();else if(elapsed>34000&&elapsed<44000)triggerGravity();else if(elapsed>50000&&elapsed<58500)triggerRifts()}if(eventName&&t>eventUntil){eventName='';portals=[];shockwaves=[];banner(phase==='final'?'👑 Core Final em andamento.':'⚡ A arena estabilizou. Continue coletando.')}if(eventName==='shock')updateShockwaves(t)}
function updateShockwaves(t){const p=me();for(const w of shockwaves){if(t<w.born)continue;const radius=(t-w.born)/1000*w.speed;if(!w.hit&&echoUntil<t&&jumpingUntil<t){const d=Math.hypot(p.x-CX,p.y-CY);if(Math.abs(d-radius)<19){w.hit=true;setEcho(p)}}}}
function updatePhase(elapsed){if(elapsed<24000)phase='collect';else if(elapsed<50000)phase='converge';else if(elapsed<60000)phase='rupture';else if(!finalStarted){finalStarted=true;phase='final';eventName='';portals=[];shockwaves=[];frags.splice(7);core.x=CX;core.y=CY;coreCarrier=null;burst(CX,CY,'#d67aff',28);banner('👑 CORE FINAL! Capture o Núcleo. Um Link ajuda você a carregá-lo mais rápido.')}if(finalStarted)phase='final'}
function updateParticles(dt){for(let i=particles.length-1;i>=0;i--){const p=particles[i];p.life-=dt;if(p.life<=0){particles.splice(i,1);continue}p.x+=p.vx*dt;p.y+=p.vy*dt;p.vx*=.95;p.vy*=.95}}
function roundRect(x,y,w,h,r){const rr=Math.min(r,w/2,h/2);ctx.beginPath();ctx.moveTo(x+rr,y);ctx.arcTo(x+w,y,x+w,y+h,rr);ctx.arcTo(x+w,y+h,x,y+h,rr);ctx.arcTo(x,y+h,x,y,rr);ctx.arcTo(x,y,x+w,y,rr);ctx.closePath()}
function drawArena(){ctx.clearRect(0,0,W,H);const bg=ctx.createLinearGradient(0,0,0,H);bg.addColorStop(0,'#080b18');bg.addColorStop(.55,'#0d1122');bg.addColorStop(1,'#050711');ctx.fillStyle=bg;ctx.fillRect(0,0,W,H);ctx.save();ctx.beginPath();ctx.arc(CX,CY,R,0,Math.PI*2);ctx.clip();const floor=ctx.createRadialGradient(CX-75,CY-115,35,CX,CY,R);floor.addColorStop(0,'#39215b');floor.addColorStop(.35,'#171a35');floor.addColorStop(.72,'#0d1325');floor.addColorStop(1,'#070a14');ctx.fillStyle=floor;ctx.fillRect(CX-R,CY-R,R*2,R*2);drawFloor();drawPads();if(eventName==='rift')drawPortals();if(eventName==='shock')drawShockwaves();drawFragments();if(phase==='final')drawCoreZone();drawBotLinks();drawCandidateLink();drawLinks();drawPlayers();drawParticles();ctx.restore();ctx.strokeStyle='#7651ae';ctx.shadowColor='#8e4fff';ctx.shadowBlur=20;ctx.lineWidth=5;ctx.beginPath();ctx.arc(CX,CY,R,0,Math.PI*2);ctx.stroke();ctx.shadowBlur=0}
function drawFloor(){ctx.save();ctx.strokeStyle='rgba(143,103,210,.12)';ctx.lineWidth=2;for(let r=82;r<R;r+=72){ctx.beginPath();ctx.arc(CX,CY,r,0,Math.PI*2);ctx.stroke()}for(let a=0;a<Math.PI*2;a+=Math.PI/10){ctx.beginPath();ctx.moveTo(CX+Math.cos(a)*60,CY+Math.sin(a)*60);ctx.lineTo(CX+Math.cos(a)*R,CY+Math.sin(a)*R);ctx.stroke()}const halo=ctx.createRadialGradient(CX,CY,0,CX,CY,120);halo.addColorStop(0,'rgba(179,76,255,.17)');halo.addColorStop(1,'rgba(179,76,255,0)');ctx.fillStyle=halo;ctx.beginPath();ctx.arc(CX,CY,120,0,Math.PI*2);ctx.fill();ctx.restore()}
function drawPads(){const t=now()/700;for(const p of pads){ctx.save();ctx.translate(p.x,p.y+8);ctx.scale(1,.48);ctx.fillStyle='#0007';ctx.beginPath();ctx.arc(0,0,p.r+9,0,Math.PI*2);ctx.fill();ctx.restore();ctx.save();ctx.translate(p.x,p.y);const g=ctx.createRadialGradient(-10,-14,4,0,0,p.r);g.addColorStop(0,'#273150');g.addColorStop(1,'#14192c');ctx.fillStyle=g;ctx.strokeStyle='rgba(125,92,185,.42)';ctx.lineWidth=2;ctx.beginPath();ctx.arc(0,0,p.r,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.globalAlpha=.22+.08*Math.sin(t+p.phase);ctx.strokeStyle='#6ae8ff';ctx.beginPath();ctx.arc(0,0,p.r-8,0,Math.PI*2);ctx.stroke();ctx.restore()}}
function drawFragments(){const t=now()/350;for(const f of frags){ctx.save();ctx.translate(f.x,f.y);ctx.rotate(f.spin+=.008);const s=1+.1*Math.sin(t+f.pulse);ctx.scale(s,s);ctx.shadowColor=f.color;ctx.shadowBlur=f.kind==='rare'?24:13;ctx.fillStyle=f.color;ctx.beginPath();ctx.moveTo(0,-f.r*1.3);ctx.lineTo(f.r*.82,0);ctx.lineTo(0,f.r*1.3);ctx.lineTo(-f.r*.82,0);ctx.closePath();ctx.fill();if(f.kind==='rare'){ctx.strokeStyle='#fff';ctx.lineWidth=2;ctx.stroke()}ctx.restore()}}
function drawPortals(){for(const p of portals){ctx.save();ctx.translate(p.x,p.y);ctx.strokeStyle='#b35cff';ctx.shadowColor='#a84dff';ctx.shadowBlur=22;for(let i=0;i<3;i++){ctx.globalAlpha=1-i*.25;ctx.lineWidth=4-i;ctx.beginPath();ctx.ellipse(0,0,22+i*8,38-i*4,0,0,Math.PI*2);ctx.stroke()}ctx.restore()}}
function drawShockwaves(){const t=now();for(const w of shockwaves){if(t<w.born)continue;const r=(t-w.born)/1000*w.speed;if(r>R+40)continue;ctx.strokeStyle='rgba(93,222,255,.62)';ctx.shadowColor='#54e6ff';ctx.shadowBlur=13;ctx.lineWidth=11;ctx.beginPath();ctx.arc(CX,CY,r,0,Math.PI*2);ctx.stroke();ctx.shadowBlur=0}}
function drawCoreZone(){ctx.save();ctx.strokeStyle='rgba(211,111,255,.36)';ctx.lineWidth=7;ctx.setLineDash([15,13]);ctx.lineDashOffset=-now()/55;ctx.beginPath();ctx.arc(CX,CY,116,0,Math.PI*2);ctx.stroke();ctx.setLineDash([]);ctx.restore();drawCore()}
function drawCore(){ctx.save();ctx.translate(core.x,core.y);ctx.shadowColor='#d35cff';ctx.shadowBlur=38;const g=ctx.createRadialGradient(-9,-9,3,0,0,38);g.addColorStop(0,'#fff');g.addColorStop(.17,'#f3b5ff');g.addColorStop(.48,'#b04cff');g.addColorStop(1,'#3a1769');ctx.fillStyle=g;ctx.beginPath();ctx.arc(0,0,core.r,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#f3d3ff';ctx.lineWidth=3;ctx.stroke();ctx.restore()}
function drawCandidateLink(){if(linkTarget&&linkUntil>now())return;const c=nearestLinkCandidate();if(!c)return;const p=me(),pulse=1+.12*Math.sin(now()/150);ctx.save();ctx.strokeStyle='rgba(102,239,255,.55)';ctx.lineWidth=2;ctx.setLineDash([10,10]);ctx.beginPath();ctx.moveTo(p.x,p.y);ctx.lineTo(c.x,c.y);ctx.stroke();ctx.setLineDash([]);ctx.strokeStyle='#70f0ff';ctx.shadowColor='#70f0ff';ctx.shadowBlur=18;ctx.lineWidth=4;ctx.beginPath();ctx.arc(c.x,c.y,(c.r+13)*pulse,0,Math.PI*2);ctx.stroke();ctx.restore()}
function drawLinks(){const t=now();if(!(linkTarget&&linkUntil>t))return;const a=me(),b=players.find(x=>x.id===linkTarget);if(!b)return;ctx.save();ctx.strokeStyle='rgba(82,232,255,.22)';ctx.lineWidth=14;ctx.shadowColor='#5deaff';ctx.shadowBlur=25;ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.stroke();ctx.strokeStyle='#8eefff';ctx.lineWidth=4;ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.stroke();ctx.strokeStyle='#d47bff';ctx.lineWidth=1.5;ctx.stroke();for(let i=0;i<4;i++){const k=(now()/700+i/4)%1,x=a.x+(b.x-a.x)*k,y=a.y+(b.y-a.y)*k;ctx.fillStyle='#fff';ctx.beginPath();ctx.arc(x,y,3,0,Math.PI*2);ctx.fill()}ctx.restore()}
function drawBotLinks(){const t=now();ctx.save();for(const p of players.slice(1)){if(!(p.botLinkTarget&&p.botLinkUntil>t))continue;const b=players.find(x=>x.id===p.botLinkTarget);if(!b)continue;ctx.strokeStyle=p.color+'66';ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(p.x,p.y);ctx.lineTo(b.x,b.y);ctx.stroke()}ctx.restore()}
function shouldLabel(p){if(p.id==='me'||coreCarrier===p.id||linkTarget===p.id)return true;const m=me();return m&&dist(p,m)<135}
function drawAvatarCircle(p,echo){ctx.save();ctx.translate(p.x,p.y);const jumping=p.id==='me'&&jumpingUntil>now(),lift=jumping?-7:0;if(jumping)ctx.scale(1.13,1.13);ctx.translate(0,lift);ctx.globalAlpha=echo?.48:1;ctx.fillStyle='#0008';ctx.beginPath();ctx.ellipse(0,p.r+8,p.r*.9,p.r*.35,0,0,Math.PI*2);ctx.fill();ctx.shadowColor=echo?'#6be6ff':p.color;ctx.shadowBlur=p.id==='me'?24:14;ctx.fillStyle=echo?'#76ddff':'#111626';ctx.beginPath();ctx.arc(0,0,p.r,0,Math.PI*2);ctx.fill();ctx.shadowBlur=0;if(p.avatar&&p.avatar.complete&&p.avatar.naturalWidth){ctx.save();ctx.beginPath();ctx.arc(0,0,p.r-3,0,Math.PI*2);ctx.clip();try{ctx.drawImage(p.avatar,-p.r+3,-p.r+3,(p.r-3)*2,(p.r-3)*2)}catch(_){}ctx.restore()}else{ctx.fillStyle='#fff';ctx.font='900 '+(p.id==='me'?17:15)+'px system-ui';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText((p.name||'?').charAt(0).toUpperCase(),0,1)}ctx.strokeStyle=p.id==='me'?'#fff':p.color;ctx.lineWidth=p.id==='me'?4:3;ctx.beginPath();ctx.arc(0,0,p.r,0,Math.PI*2);ctx.stroke();if(coreCarrier===p.id){ctx.font='22px system-ui';ctx.textAlign='center';ctx.fillText('👑',0,-p.r-13)}if(shouldLabel(p)){const text=p.id==='me'?'VOCÊ':p.name;ctx.font='800 12px system-ui';const tw=ctx.measureText(text).width+14;ctx.fillStyle='rgba(5,7,16,.78)';roundRect(-tw/2,p.r+12,tw,20,10);ctx.fill();ctx.fillStyle='#fff';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(text,0,p.r+22)}ctx.restore()}
function drawPlayers(){const t=now();for(const p of players)drawAvatarCircle(p,(p.echoUntil||0)>t)}
function drawParticles(){ctx.save();for(const p of particles){ctx.globalAlpha=clamp(p.life/.65,0,1);ctx.fillStyle=p.color;ctx.beginPath();ctx.arc(p.x,p.y,p.size,0,Math.PI*2);ctx.fill()}ctx.restore()}
function update(dt,t){const elapsed=t-startedAt;updatePhase(elapsed);updateEvents(t,elapsed);if(linkTarget&&linkUntil>t){const mate=players.find(x=>x.id===linkTarget);if(!mate||dist(me(),mate)>210){linkUntil=t;banner('🔗 Link rompido: vocês se afastaram demais.')}}else if(linkTarget&&linkUntil<=t)linkTarget=null;for(const p of players)updatePlayer(p,dt);updateCore(dt);updateParticles(dt);if(elapsed>=85000)finishMatch();updateHud()}
function loop(t){if(!active)return;const dt=clamp((t-last)/1000,0,.034);last=t;update(dt,t);drawArena();if(active)raf=requestAnimationFrame(loop)}
function finishMatch(){if(matchEnded)return;matchEnded=true;active=false;cancelAnimationFrame(raf);const order=sorted(),rank=Math.max(1,order.findIndex(x=>x.id==='me')+1),score=scoreOf(me());if(score>best){best=score;localStorage.setItem('zunoplay_zuno_core_best',String(score))}$('overlayTitle').textContent=rank===1?'Core Master!':'Zuno Core concluído';$('overlayText').textContent='Alpha 0.2 testada: avatares, Link assistido, arena viva, novos fragmentos e Core Final refinado.';$('features').style.display='none';const grid=$('resultGrid');grid.classList.add('show');grid.innerHTML='<div class="result"><small>POSIÇÃO</small><b>'+rank+'º/8</b></div><div class="result"><small>PONTOS</small><b>'+score+'</b></div><div class="result"><small>ENERGIA</small><b>'+Math.round(me().energy)+'</b></div><div class="result"><small>LINKS</small><b>'+stats.links+'</b></div><div class="result"><small>RAROS</small><b>'+stats.rare+'</b></div><div class="result"><small>CORE</small><b>'+stats.coreSeconds.toFixed(1)+'s</b></div>';$('start').textContent='Jogar novamente';$('overlay').classList.remove('hide');banner('🏁 '+rank+'º lugar · '+score+' pontos · recorde '+best);announce('Zuno Core concluído')}
function setupInput(){const joy=$('joystick'),nub=$('joynub');function move(e){if(joyPointer!==e.pointerId)return;const r=joy.getBoundingClientRect(),cx=r.left+r.width/2,cy=r.top+r.height/2,dx=e.clientX-cx,dy=e.clientY-cy,m=Math.hypot(dx,dy),lim=r.width*.33,k=m>lim?lim/m:1;controls.x=dx/lim*k;controls.y=dy/lim*k;nub.style.transform='translate(calc(-50% + '+(controls.x*34)+'px),calc(-50% + '+(controls.y*34)+'px))'}function end(e){if(joyPointer!==e.pointerId)return;joyPointer=null;controls.x=controls.y=0;nub.style.transform='translate(-50%,-50%)'}joy.onpointerdown=e=>{joyPointer=e.pointerId;joy.setPointerCapture?.(e.pointerId);move(e)};joy.onpointermove=move;joy.onpointerup=end;joy.onpointercancel=end;window.addEventListener('keydown',e=>{const k=e.key.toLowerCase();controls.keys.add(k);if(k===' '){e.preventDefault();jump()}if(k==='e')activateLink()});window.addEventListener('keyup',e=>controls.keys.delete(e.key.toLowerCase()));$('jump').onclick=jump;$('link').onclick=activateLink}
function loadImage(src){return new Promise(resolve=>{if(!src)return resolve(null);const img=new Image();img.onload=()=>resolve(img);img.onerror=()=>resolve(null);img.src=src})}
async function waitRenderer(){for(let i=0;i<45;i++){if(window.ZunoAvatarRenderer)return window.ZunoAvatarRenderer;await new Promise(r=>setTimeout(r,100))}return null}
async function avatarFromConfig(cfg){try{const r=await waitRenderer();if(!r||!cfg)return null;const n=r.normalize(cfg)||cfg,display=JSON.parse(JSON.stringify(n));display.mode='Perfil';display.selections={...(display.selections||{}),Mascote:0,Efeitos:0};const src=await r.officialImage(display.model);return loadImage(r.officialComposite(display,src))}catch(e){console.warn('Zuno Core avatar',e);return null}}
async function prepareAvatars(){const r=await waitRenderer();if(r){const male=JSON.parse(JSON.stringify(r.official.masculino||r.defaults)),female=JSON.parse(JSON.stringify(r.official.feminino||r.defaults));botMale=await avatarFromConfig(male);botFemale=await avatarFromConfig(female)}let local=null;try{local=JSON.parse(localStorage.getItem('zunoAvatarPreset')||'null')}catch(_){}userAvatar=await avatarFromConfig(avatarConfig||local);const p=me();if(p)p.avatar=userAvatar;players.slice(1).forEach((x,i)=>x.avatar=i%2?botFemale:botMale)}
async function waitClient(){for(let i=0;i<50;i++){if(window.ZunoSupabaseClient)return window.ZunoSupabaseClient;await new Promise(r=>setTimeout(r,100))}return null}
async function loadProfile(){try{sb=await waitClient();if(!sb){prepareAvatars();return}const{data:{session}}=await sb.auth.getSession();user=session?.user||null;if(user){const{data}=await sb.from('profiles').select('username,avatar_config').eq('id',user.id).maybeSingle();userName=data?.username||user.user_metadata?.username||user.email?.split('@')[0]||'Você';avatarConfig=data?.avatar_config||null}await prepareAvatars()}catch(e){console.warn('Zuno Core profile',e);prepareAvatars()}}
$('back').onclick=()=>location.href=fromRoom?'sala.html?room='+encodeURIComponent(roomId):'jogos.html';$('exit').onclick=$('back').onclick;$('start').onclick=()=>{if($('features'))$('features').style.display='grid';$('resultGrid').classList.remove('show');reset()};if(roomId)$('room').classList.add('show');setupInput();loadProfile();window.addEventListener('pagehide',()=>{active=false;cancelAnimationFrame(raf)});document.addEventListener('visibilitychange',()=>{if(document.hidden)last=now()});makePads();drawArena();
})();