(()=>{
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const state={client:null,user:null,profile:null,posts:[],profiles:new Map(),likes:[],comments:[],friends:new Set(),view:'moments',topic:'',file:null};
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const timeAgo=v=>{const d=(Date.now()-new Date(v))/1000;if(d<60)return'agora';if(d<3600)return`${Math.floor(d/60)} min`;if(d<86400)return`${Math.floor(d/3600)} h`;if(d<604800)return`${Math.floor(d/86400)} d`;return new Date(v).toLocaleDateString('pt-BR',{day:'2-digit',month:'short'})};
function toast(t){const el=$('#toast');el.textContent=t;el.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>el.classList.remove('show'),2200)}
function avatarMarkup(p,cls='zm-post-avatar'){return p?.avatar_url?`<div class="${cls}"><img src="${esc(p.avatar_url)}" alt=""></div>`:`<div class="${cls}">${esc((p?.nickname||p?.username||'Z').slice(0,1).toUpperCase())}</div>`}
function setOwnAvatar(){const p=state.profile;['#composerAvatar','#myAvatarMini'].forEach(sel=>{const el=$(sel);if(!el)return;if(p?.avatar_url)el.innerHTML=`<img src="${esc(p.avatar_url)}" alt="">`;else el.textContent=(p?.nickname||p?.username||'Z').slice(0,1).toUpperCase()})}
function extractTags(text){return [...new Set((String(text).match(/#[\p{L}\p{N}_]{2,30}/gu)||[]).map(x=>x.slice(1).toLowerCase()))].slice(0,8)}
function linkify(text){return esc(text).replace(/#([\p{L}\p{N}_]{2,30})/gu,'<span class="zm-hashtag">#$1</span>')}
async function bootClient(){for(let i=0;i<40;i++){if(window.ZunoSupabaseClient)return window.ZunoSupabaseClient;if(window.supabase?.createClient){window.ZunoSupabaseClient=window.supabase.createClient('https://rliymfbbhqoejgfvsbuu.supabase.co','sb_publishable_E4go4X7yZ6d-aXnKAT-fWw_Y8uHIJT0',{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});return window.ZunoSupabaseClient}await new Promise(r=>setTimeout(r,75))}throw new Error('Supabase indisponível')}
async function loadFriends(){const uid=state.user.id;const{data,error}=await state.client.from('friendships').select('user_id,friend_id').or(`user_id.eq.${uid},friend_id.eq.${uid}`);if(error){console.warn('Pulso: amizades indisponíveis',error);state.friends=new Set();return}state.friends=new Set((data||[]).map(r=>r.user_id===uid?r.friend_id:r.user_id).filter(Boolean))}
async function load(){const c=state.client;const{data:{session}}=await c.auth.getSession();if(!session?.user){location.href='login.html';return}state.user=session.user;
const[pRes,postsRes]=await Promise.all([c.from('profiles').select('id,username,nickname,avatar_url').eq('id',state.user.id).maybeSingle(),c.from('moments_posts').select('*').order('created_at',{ascending:false}).limit(120),loadFriends()]);state.profile=pRes.data||{id:state.user.id,username:'ZunoPlayer'};state.posts=postsRes.data||[];setOwnAvatar();await hydrate();render()}
async function hydrate(){const c=state.client,ids=[...new Set(state.posts.map(p=>p.user_id))];if(ids.length){const{data}=await c.from('profiles').select('id,username,nickname,avatar_url,level').in('id',ids);(data||[]).forEach(p=>state.profiles.set(p.id,p))}
const postIds=state.posts.map(p=>p.id);if(!postIds.length){state.likes=[];state.comments=[];return}const[l,cms]=await Promise.all([c.from('moments_likes').select('post_id,user_id').in('post_id',postIds),c.from('moments_comments').select('id,post_id,user_id,content,created_at').in('post_id',postIds).order('created_at',{ascending:true})]);state.likes=l.data||[];state.comments=cms.data||[];const commenterIds=[...new Set(state.comments.map(x=>x.user_id).filter(x=>!state.profiles.has(x)))];if(commenterIds.length){const{data}=await c.from('profiles').select('id,username,nickname,avatar_url').in('id',commenterIds);(data||[]).forEach(p=>state.profiles.set(p.id,p))}}
function friendPosts(){return state.posts.filter(p=>p.user_id===state.user.id||state.friends.has(p.user_id)).sort((a,b)=>new Date(b.created_at)-new Date(a.created_at))}
function engagement(p){const likes=state.likes.filter(x=>x.post_id===p.id).length,comments=state.comments.filter(x=>x.post_id===p.id).length,hours=Math.max(0,(Date.now()-new Date(p.created_at).getTime())/36e5),fresh=Math.max(0,30-hours/4);return likes*4+comments*6+fresh+2}
function discoveryPosts(){const eligible=state.posts.filter(p=>p.user_id!==state.user.id&&!state.friends.has(p.user_id)&&p.visibility!=='friends'&&p.media_type==='image'&&p.media_path).map(p=>({...p,__score:engagement(p)})).sort((a,b)=>b.__score-a.__score||new Date(b.created_at)-new Date(a.created_at));const primary=[],overflow=[],seen=new Map();eligible.forEach(p=>{const n=seen.get(p.user_id)||0;(n<2?primary:overflow).push(p);seen.set(p.user_id,n+1)});return primary.concat(overflow)}
function visibleBase(){return state.view==='plaza'?discoveryPosts():friendPosts()}
function topics(){const counts=new Map();visibleBase().forEach(p=>(p.hashtags||[]).forEach(t=>counts.set(t,(counts.get(t)||0)+1)));return [...counts].sort((a,b)=>b[1]-a[1]).slice(0,12)}
function renderTopics(){const all=topics();const strip=$('#topicStrip');strip.innerHTML=`<button class="zm-topic ${!state.topic?'active':''}" data-topic=""># Para você</button>`+all.map(([t,n])=>`<button class="zm-topic ${state.topic===t?'active':''}" data-topic="${esc(t)}">#${esc(t)} · ${n}</button>`).join('');$$('[data-topic]',strip).forEach(b=>b.onclick=()=>{state.topic=b.dataset.topic;render()})}
function mediaUrl(p){if(!p.media_path)return'';return state.client.storage.from('moments').getPublicUrl(p.media_path).data.publicUrl}
function renderPost(p){const prof=state.profiles.get(p.user_id)||{username:'Zuno'};const likes=state.likes.filter(x=>x.post_id===p.id),comments=state.comments.filter(x=>x.post_id===p.id),liked=likes.some(x=>x.user_id===state.user.id),media=mediaUrl(p),mine=p.user_id===state.user.id,isDiscovery=state.view==='plaza';const mediaHtml=media?`<div class="zm-post-media">${p.media_type==='video'?`<video src="${esc(media)}" controls playsinline preload="metadata"></video>`:`<img src="${esc(media)}" loading="lazy" alt="Publicação">`}</div>`:'';const commentHtml=comments.slice(-3).map(x=>{const cp=state.profiles.get(x.user_id)||{username:'Zuno'};return`<div class="zm-comment"><div class="zm-comment-bubble"><strong>${esc(cp.nickname||cp.username||'Zuno')}</strong>${esc(x.content)}</div></div>`}).join('');return`<article class="zm-post" data-post="${p.id}"><div class="zm-post-head">${avatarMarkup(prof)}<div><div class="zm-post-name">${esc(prof.nickname||prof.username||'ZunoPlayer')}${isDiscovery?'<span class="zm-discovery-tag"> · Descobrir</span>':''}</div><div class="zm-post-meta">Nível ${prof.level||1} · ${timeAgo(p.created_at)}${isDiscovery?` · ${likes.length+comments.length} interações`:''}</div></div>${mine?`<button class="zm-more" data-delete="${p.id}" aria-label="Excluir publicação">×</button>`:`<button class="zm-more" aria-label="Mais opções">···</button>`}</div><div class="zm-post-copy">${linkify(p.content)}</div>${mediaHtml}<div class="zm-post-stats"><span>${likes.length} curtida${likes.length===1?'':'s'}</span><span>${comments.length} comentário${comments.length===1?'':'s'}</span></div><div class="zm-post-actions"><button class="zm-action ${liked?'liked':''}" data-like="${p.id}">${liked?'♥':'♡'} Curtir</button><button class="zm-action" data-comments="${p.id}">◯ Comentar</button><button class="zm-action" data-share="${p.id}">↗ Compartilhar</button></div><div class="zm-comments" data-comments-box="${p.id}" hidden><div class="zm-comment-list">${commentHtml||'<div class="zm-post-meta">Seja o primeiro a comentar.</div>'}</div><form class="zm-comment-form" data-comment-form="${p.id}"><input class="zm-comment-input" maxlength="600" placeholder="Escreva um comentário..."><button class="zm-comment-send">Enviar</button></form></div></article>`}
function render(){renderTopics();$$('.zm-tab').forEach(b=>b.classList.toggle('active',b.dataset.view===state.view));$('#composer').hidden=state.view==='plaza';$('#plazaIntro').hidden=state.view!=='plaza';let posts=visibleBase();if(state.topic)posts=posts.filter(p=>(p.hashtags||[]).includes(state.topic));$('#feed').innerHTML=posts.length?posts.map(renderPost).join(''):`<div class="zm-empty">${state.topic?'Ainda não há publicações nesse assunto.':state.view==='plaza'?'Ainda não há fotos públicas de outros perfis para descobrir.':'Seus amigos ainda não publicaram no Pulso.'}</div>`;bindFeed()}
function bindFeed(){$$('[data-like]').forEach(b=>b.onclick=()=>toggleLike(b.dataset.like));$$('[data-comments]').forEach(b=>b.onclick=()=>{const x=$(`[data-comments-box="${b.dataset.comments}"]`);x.hidden=!x.hidden;if(!x.hidden)x.querySelector('input')?.focus()});$$('[data-comment-form]').forEach(f=>f.onsubmit=e=>{e.preventDefault();addComment(f.dataset.commentForm,$('input',f).value)});$$('[data-share]').forEach(b=>b.onclick=()=>sharePost(b.dataset.share));$$('[data-delete]').forEach(b=>b.onclick=()=>deletePost(b.dataset.delete))}
async function toggleLike(id){const liked=state.likes.some(x=>x.post_id===id&&x.user_id===state.user.id);if(liked){await state.client.from('moments_likes').delete().eq('post_id',id).eq('user_id',state.user.id);state.likes=state.likes.filter(x=>!(x.post_id===id&&x.user_id===state.user.id))}else{const{error}=await state.client.from('moments_likes').insert({post_id:id,user_id:state.user.id});if(error)return toast('Não foi possível curtir.');state.likes.push({post_id:id,user_id:state.user.id})}render()}
async function addComment(id,text){text=String(text||'').trim();if(!text)return;const{data,error}=await state.client.from('moments_comments').insert({post_id:id,user_id:state.user.id,content:text}).select().single();if(error)return toast('Não foi possível comentar.');state.comments.push(data);state.profiles.set(state.user.id,state.profile);render();const box=$(`[data-comments-box="${id}"]`);if(box)box.hidden=false}
async function sharePost(id){const url=`${location.origin}${location.pathname}?post=${encodeURIComponent(id)}`;try{if(navigator.share)await navigator.share({title:'Pulso no ZunoPlay',url});else{await navigator.clipboard.writeText(url);toast('Link copiado.')}}catch(_){}}
async function deletePost(id){if(!confirm('Excluir esta publicação do Pulso?'))return;const post=state.posts.find(x=>x.id===id);const{error}=await state.client.from('moments_posts').delete().eq('id',id);if(error)return toast('Não foi possível excluir.');if(post?.media_path)state.client.storage.from('moments').remove([post.media_path]);state.posts=state.posts.filter(x=>x.id!==id);state.likes=state.likes.filter(x=>x.post_id!==id);state.comments=state.comments.filter(x=>x.post_id!==id);render();toast('Publicação excluída do Pulso.')}
async function publish(){const text=$('#postText').value.trim(),file=state.file;if(!text&&!file)return toast('Escreva algo ou adicione uma mídia.');const btn=$('#publishButton');btn.disabled=true;btn.textContent='Publicando...';let media_path=null,media_type=null;try{if(file){media_type=file.type.startsWith('video/')?'video':'image';const ext=(file.name.split('.').pop()||'bin').toLowerCase();media_path=`${state.user.id}/${Date.now()}-${crypto.randomUUID()}.${ext}`;const{error}=await state.client.storage.from('moments').upload(media_path,file,{contentType:file.type,upsert:false});if(error)throw error}const{data,error}=await state.client.from('moments_posts').insert({user_id:state.user.id,content:text,media_path,media_type,hashtags:extractTags(text)}).select().single();if(error)throw error;state.posts.unshift(data);state.profiles.set(state.user.id,state.profile);$('#postText').value='';$('#postMedia').value='';state.file=null;$('#mediaPreview').hidden=true;$('#mediaPreview').innerHTML='';await hydrate();state.view='moments';state.topic='';render();toast('Publicado no Pulso!')}catch(e){if(media_path)state.client.storage.from('moments').remove([media_path]);console.error(e);toast('Não foi possível publicar no Pulso.')}finally{btn.disabled=false;btn.textContent='Publicar'}}
function bind(){$$('.zm-tab').forEach(b=>b.onclick=()=>{state.view=b.dataset.view;state.topic='';render()});$('#publishButton').onclick=publish;$('#postMedia').onchange=e=>{const f=e.target.files?.[0];if(!f)return;if(f.size>15*1024*1024){e.target.value='';return toast('Mídia deve ter até 15 MB.')}state.file=f;const u=URL.createObjectURL(f),box=$('#mediaPreview');box.innerHTML=f.type.startsWith('video/')?`<video src="${u}" controls playsinline></video>`:`<img src="${u}" alt="Prévia">`;box.hidden=false}}
async function realtime(){state.client.channel('zuno-moments-feed').on('postgres_changes',{event:'*',schema:'public',table:'moments_posts'},async()=>{const{data}=await state.client.from('moments_posts').select('*').order('created_at',{ascending:false}).limit(120);state.posts=data||[];await hydrate();render()}).on('postgres_changes',{event:'*',schema:'public',table:'moments_likes'},async()=>{await hydrate();render()}).on('postgres_changes',{event:'*',schema:'public',table:'moments_comments'},async()=>{await hydrate();render()}).subscribe()}
async function start(){bind();try{state.client=await bootClient();await load();realtime()}catch(e){console.error(e);$('#feed').innerHTML='<div class="zm-empty">Não foi possível carregar o Pulso agora.</div>'}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start,{once:true});else start();
})();