(()=>{
if(window.__ZUNO_PULSE__)return;window.__ZUNO_PULSE__=true;
const $=id=>document.getElementById(id),sleep=ms=>new Promise(r=>setTimeout(r,ms)),q=new URLSearchParams(location.search),roomId=q.get('room')||sessionStorage.getItem('zunoplay_room_id')||'',fromRoom=q.get('from')==='sala'&&!!roomId;
const botNames=['Nova','Kiro','Lumi','Mako','Yara','Nox','Bibi'];
const roundOrder=['zones','signal','duo','memory','gravity','core'];
let sb=null,user=null,players=[],roundIndex=0,active=false,timer=0,raf=0,reduceMotion=false,reduceFlash=false,playerName='Você',stats=null,runToken=0;
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[c]));
const rand=(min,max)=>Math.random()*(max-min)+min,clamp=(v,min,max)=>Math.max(min,Math.min(max,v));
function announce(t){$('live').textContent=t}function vibrate(ms=20){if(!reduceMotion&&navigator.vibrate)navigator.vibrate(ms)}
function clearAsync(){if(timer){clearTimeout(timer);timer=0}if(raf){cancelAnimationFrame(raf);raf=0}}
function me(){return players[0]}function sorted(){return [...players].sort((a,b)=>b.score-a.score||b.aura-a.aura)}function myRank(){return Math.max(1,sorted().findIndex(p=>p.id==='me')+1)}
function renderHud(){const p=me()||{score:0,aura:0};$('rank').textContent=myRank()+'º';$('score').textContent=Math.round(p.score);$('aura').textContent=Math.round(p.aura)+'%';$('auraFill').style.width=clamp(p.aura,0,100)+'%';$('pulseNo').textContent=Math.min(roundIndex+1,6)+'/6';$('progress').style.width=(Math.min(roundIndex,6)/6*100)+'%'}
function renderPlayers(){const order=sorted();$('players').innerHTML=order.map((p,i)=>`<div class="player ${p.id==='me'?'me':''} ${p.echo?'echo':''}"><div class="avatar">${p.echo?'👻':p.id==='me'?'⚡':['🤖','🧑','👾','🦊','🐺'][i%5]}</div><b>${esc(p.name)}</b><span>${Math.round(p.score)} pts · ${Math.round(p.aura)} Aura</span></div>`).join('');renderHud()}
function simulateBots(base,successBias=.72){players.slice(1).forEach((p,i)=>{const success=Math.random()<successBias;const gain=Math.round(base*(success?rand(.68,1.03):rand(.2,.55))+rand(0,110));p.score+=Math.max(40,gain);p.aura=clamp(p.aura+(success?rand(10,21):rand(3,9)),0,100);p.echo=!success&&Math.random()<.45;if(i===roundIndex%7&&Math.random()>.68)p.score+=120})}
function addResult(points,aura,success,{help=false}={}){const p=me();p.score+=Math.round(points);p.aura=clamp(p.aura+aura+(help?6:0),0,100);p.echo=!success;stats.completed+=success?1:0;stats.echoes+=success?0:1;stats.helped+=help?1:0;simulateBots(Math.max(points,300),success?.78:.68);renderPlayers()}
function banner(text){const b=$('pulseBanner');b.textContent=text;b.classList.add('show');timer=setTimeout(()=>b.classList.remove('show'),1100)}
function setRound(title,kicker){$('roundTitle').textContent=title;$('kicker').textContent=kicker;$('pulseNo').textContent=(roundIndex+1)+'/6';$('progress').style.width=(roundIndex/6*100)+'%';banner('PULSE '+(roundIndex+1)+' · '+title.toUpperCase());announce('Pulse '+(roundIndex+1)+': '+title)}
function feedback(text,good){const f=$('feedback');if(!f)return;f.textContent=text;f.className='feedback '+(good===true?'good':good===false?'bad':'')}
function finishRound(points,aura,success,msg,opt={}){if(!active)return;active=false;clearAsync();addResult(points,aura,success,opt);feedback(msg,success);announce(msg);vibrate(success?22:48);timer=setTimeout(()=>{roundIndex++;if(roundIndex>=6)finishMatch();else startRound()},900)}
function startMatch(){runToken++;clearAsync();players=[{id:'me',name:playerName,score:0,aura:0,echo:false},...botNames.map((name,i)=>({id:'b'+i,name,score:0,aura:0,echo:false}))];stats={completed:0,echoes:0,helped:0,reaction:null,orbs:0};roundIndex=0;active=false;$('overlay').classList.add('hide');$('results').classList.remove('show');$('award').classList.remove('show');$('features').style.display='grid';$('saving').textContent='';renderPlayers();startRound()}
function startRound(){clearAsync();renderPlayers();if(me().echo&&roundIndex<5){echoInterlude();return}const type=roundOrder[roundIndex];if(type==='zones')zonesRound();else if(type==='signal')signalRound();else if(type==='duo')duoRound();else if(type==='memory')memoryRound();else if(type==='gravity')gravityRound();else coreRound()}
function echoInterlude(){setRound('Modo Echo','RECUPERAÇÃO · VOCÊ CONTINUA');active=true;const c=$('challenge');c.innerHTML='<div class="challenge-icon">👻</div><h2>Modo Echo</h2><p>Você não foi eliminado. Colete 3 partículas para voltar com energia antes do próximo Pulse.</p><div class="timer">PARTÍCULAS: <b id="echoCount">0/3</b></div><div class="playzone"><div class="echo-panel"><b>Eco de Zuno</b><div class="echo-orbs">'+[0,1,2,3].map(i=>'<button class="echo-orb" data-e="'+i+'">✦</button>').join('')+'</div></div></div><div id="feedback" class="feedback">Colete pelo menos 3.</div>';
let got=0;c.querySelectorAll('[data-e]').forEach(b=>b.onclick=()=>{if(!active||b.classList.contains('got'))return;b.classList.add('got');got++;$('echoCount').textContent=got+'/3';me().aura=clamp(me().aura+4,0,100);me().score+=80;renderPlayers();if(got>=3){active=false;clearAsync();me().echo=false;feedback('✨ Echo completo. Você voltou ao Núcleo!',true);timer=setTimeout(startRound,700)}});timer=setTimeout(()=>{if(!active)return;active=false;me().echo=false;feedback('O Núcleo puxou você de volta. Continue!',true);timer=setTimeout(startRound,650)},4200)}
function zonesRound(){setRound('Zona Segura','PULSE 1 · MOVIMENTO');active=true;const zones=[['NORTE','⬆'],['LESTE','➡'],['SUL','⬇'],['OESTE','⬅']],safe=Math.floor(Math.random()*4),c=$('challenge');c.innerHTML=`<div class="challenge-icon">🏃</div><h2>Corra para a Zona</h2><p>Escolha uma direção antes do impacto. Texto e símbolo aparecem juntos para não depender apenas de cor.</p><div class="timer">PULSE EM <b id="count">3</b></div><div class="playzone"><div class="zones">${zones.map((z,i)=>`<button class="zone" data-z="${i}"><strong>${z[1]}</strong>${z[0]}</button>`).join('')}</div></div><div id="feedback" class="feedback">Escolha uma zona.</div>`;
let choice=-1,count=3;c.querySelectorAll('[data-z]').forEach(b=>b.onclick=()=>{if(!active)return;choice=Number(b.dataset.z);c.querySelectorAll('[data-z]').forEach(x=>x.style.outline='');b.style.outline='2px solid #b76cff';feedback('Zona escolhida. Aguarde o Pulse.')});const tick=()=>{if(!active)return;$('count').textContent=count;if(count--<=0){const ok=choice===safe;c.querySelectorAll('[data-z]').forEach((b,i)=>b.classList.add(i===safe?'safe':'danger'));finishRound(ok?1250:280,ok?18:5,ok,ok?'✓ Zona segura! Você atravessou o primeiro Pulse.':'💥 O impacto pegou você. Entrando no Echo, mas a partida continua.');return}timer=setTimeout(tick,reduceMotion?520:700)};tick()}
function signalRound(){setRound('Pare ou Pulse','PULSE 2 · REFLEXO');active=true;const c=$('challenge');c.innerHTML='<div class="challenge-icon">🚦</div><h2>Espere o PULSE</h2><p>Não toque durante PARE. Quando aparecer PULSE, pressione o botão o mais rápido possível.</p><div class="timer">STATUS: <b id="signalText">PARE</b></div><div class="playzone"><div><div id="signal" class="signal stop">■ PARE</div><button id="tap" class="big-action">PULSE</button></div></div><div id="feedback" class="feedback">Espere o sinal.</div>';const startDelay=Math.round(rand(1100,2300)),sig=$('signal'),tap=$('tap');let go=false,goAt=0;const hit=()=>{if(!active)return;document.removeEventListener('keydown',key);if(!go){finishRound(180,4,false,'Muito cedo! Você entrou no Echo, mas volta no próximo Pulse.');return}const rt=performance.now()-goAt;stats.reaction=Math.round(rt);const points=clamp(1500-rt*1.15,450,1450),ok=rt<850;finishRound(points,ok?22:10,ok,(ok?'⚡ Reflexo perfeito! ':'Você reagiu, mas o Pulse foi rápido. ')+Math.round(rt)+' ms.')};tap.onclick=hit;const key=e=>{if((e.code==='Space'||e.key==='Enter')&&active){e.preventDefault();hit()}};document.addEventListener('keydown',key);timer=setTimeout(()=>{if(!active)return;go=true;goAt=performance.now();sig.className='signal go';sig.textContent='⚡ PULSE';$('signalText').textContent='PULSE!';if(!reduceFlash)document.body.animate([{filter:'brightness(1)'},{filter:'brightness(1.22)'},{filter:'brightness(1)'}],{duration:180});announce('PULSE!');timer=setTimeout(()=>{document.removeEventListener('keydown',key);if(active)finishRound(250,6,false,'O Pulse passou. Você continua pelo Echo.')},1800)},startDelay);window.addEventListener('pagehide',()=>document.removeEventListener('keydown',key),{once:true})}
function duoRound(){setRound('Conexão Zuno','PULSE 3 · SOCIAL');active=true;const c=$('challenge'),candidates=players.slice(1,5);c.innerHTML=`<div class="challenge-icon">🤝</div><h2>Forme uma Dupla</h2><p>Escolha alguém antes do tempo acabar. Ajudar outro jogador aumenta sua Aura além da pontuação.</p><div class="timer">CONEXÃO: <b id="duoTime">4.0s</b></div><div class="playzone"><div class="partners">${candidates.map(p=>`<button class="partner" data-p="${p.id}"><b>⚡ ${esc(p.name)}</b><span>${Math.round(p.aura)} Aura · precisa de dupla</span></button>`).join('')}</div></div><div id="feedback" class="feedback">Escolha um parceiro.</div>`;const start=performance.now();let chosen=false;const update=()=>{if(!active)return;const left=Math.max(0,4000-(performance.now()-start));$('duoTime').textContent=(left/1000).toFixed(1)+'s';raf=requestAnimationFrame(update)};raf=requestAnimationFrame(update);c.querySelectorAll('[data-p]').forEach(b=>b.onclick=()=>{if(!active||chosen)return;chosen=true;b.classList.add('selected');const elapsed=performance.now()-start,pts=clamp(1250-elapsed*.14,650,1250);finishRound(pts,24,true,'🤝 Dupla formada! +Aura por cooperação.',{help:true})});timer=setTimeout(()=>{if(active)finishRound(220,5,false,'Você ficou sem dupla neste Pulse. Echo ativado.')},4000)}
function memoryRound(){setRound('Memória do Núcleo','PULSE 4 · MEMÓRIA');active=true;const symbols=['◆','●','▲','✦'],seq=[0,0,0].map(()=>Math.floor(Math.random()*4)),c=$('challenge');c.innerHTML=`<div class="challenge-icon">🧠</div><h2>Repita o Pulso</h2><p>Memorize três sinais do Núcleo e repita na mesma ordem.</p><div class="timer"><b id="memStatus">MEMORIZE</b></div><div class="playzone"><div><div class="memory">${symbols.map((s,i)=>`<button class="mem" data-m="${i}" disabled>${s}</button>`).join('')}</div></div></div><div id="feedback" class="feedback">Observe a sequência.</div>`;const buttons=[...c.querySelectorAll('[data-m]')];let answer=[];const flash=async()=>{for(const idx of seq){if(!active)return;buttons[idx].classList.add('flash');if(!reduceFlash)vibrate(12);await sleep(reduceMotion?360:520);buttons[idx].classList.remove('flash');await sleep(reduceMotion?120:180)}if(!active)return;$('memStatus').textContent='SUA VEZ';buttons.forEach(b=>{b.disabled=false;b.onclick=()=>{if(!active)return;answer.push(Number(b.dataset.m));b.classList.add('flash');setTimeout(()=>b.classList.remove('flash'),120);const idx=answer.length-1;if(answer[idx]!==seq[idx]){finishRound(230,6,false,'Sequência incorreta. O Echo salva sua continuidade.');return}if(answer.length===seq.length)finishRound(1350,24,true,'🧠 Sequência perfeita! Memória sincronizada.');else feedback('Certo. Falta '+(seq.length-answer.length)+'.')}});feedback('Repita os 3 sinais.')};timer=setTimeout(flash,500)}
function gravityRound(){setRound('Zero Gravity','PULSE 5 · CAOS');active=true;const c=$('challenge');c.innerHTML='<div class="challenge-icon">🌌</div><h2>Zero Gravity</h2><p>Colete cinco partículas que aparecem pela arena antes do tempo terminar.</p><div class="timer">COLETADAS: <b id="orbCount">0/5</b></div><div class="playzone"><div id="orbs" class="orbs"></div></div><div id="feedback" class="feedback">Toque nas partículas.</div>';const box=$('orbs');let got=0;for(let i=0;i<7;i++){const b=document.createElement('button');b.className='orb';b.setAttribute('aria-label','Partícula Zuno');b.style.left=rand(7,88)+'%';b.style.top=rand(8,76)+'%';b.onclick=()=>{if(!active||b.classList.contains('hit'))return;b.classList.add('hit');got++;stats.orbs=got;$('orbCount').textContent=got+'/5';me().score+=110;me().aura=clamp(me().aura+3,0,100);renderPlayers();vibrate(12);if(got>=5)finishRound(900,18,true,'🌌 Cinco partículas coletadas! Você dominou a gravidade.')};box.appendChild(b)}timer=setTimeout(()=>{if(active)finishRound(got*130,got*3,got>=3,(got>=3?'Você segurou o caos com '+got+' partículas.':'A gravidade venceu este Pulse. Echo ativado.'))},5000)}
function coreRound(){setRound('Capture o Núcleo','PULSE FINAL · TIMING');active=true;me().echo=false;const c=$('challenge');c.innerHTML='<div class="challenge-icon">👑</div><h2>Pulse Final</h2><p>Capture o Núcleo quando ele atravessar a zona central. Quanto mais perto do centro, maior a pontuação final.</p><div class="timer">ÚLTIMA CHANCE</div><div class="playzone"><div style="width:100%"><div class="core-track"><div class="core-zone"></div><div id="core" class="core"></div></div><button id="capture" class="big-action">CAPTURAR NÚCLEO</button></div></div><div id="feedback" class="feedback">Espere o centro.</div>';let started=performance.now(),pos=0;const core=$('core');const animate=t=>{if(!active)return;const p=((t-started)*.00062)%2;pos=p<=1?p:2-p;core.style.left=(pos*100)+'%';raf=requestAnimationFrame(animate)};raf=requestAnimationFrame(animate);const capture=()=>{if(!active)return;document.removeEventListener('keydown',key);const left=parseFloat(core.style.left||'0'),dist=Math.abs(50-left),perfect=dist<=8,ok=dist<=18,pts=clamp(2200-dist*45,350,2200);finishRound(pts,perfect?30:ok?20:8,ok,(perfect?'👑 NÚCLEO PERFEITO! ':ok?'⚡ Núcleo capturado! ':'O Núcleo escapou por pouco. ')+dist.toFixed(1)+'% do centro.')};$('capture').onclick=capture;const key=e=>{if((e.code==='Space'||e.key==='Enter')&&active){e.preventDefault();capture()}};document.addEventListener('keydown',key);timer=setTimeout(()=>{document.removeEventListener('keydown',key);if(active)finishRound(300,5,false,'O Núcleo passou. Partida concluída sem eliminação.')},7000)}
function awardTitle(rank,p){if(rank===1)return['👑 ZUNO MASTER','Melhor desempenho da partida'];if(stats.helped>0&&p.aura>=70)return['🤝 ZUNO HEART','Aura social e ajuda em destaque'];if(stats.reaction!==null&&stats.reaction<350)return['⚡ ZUNO SPEED','Reflexo mais marcante'];if(stats.completed>=5)return['🎯 ZUNO PERFECT','Consistência nos Pulses'];return['🌀 ZUNO CHAOS','Você atravessou o caos até o fim']}
async function persistResult(rank,p){$('saving').textContent='Salvando resultado...';if(!sb||!user){$('saving').textContent='Resultado salvo apenas neste dispositivo.';return}try{const{data,error}=await sb.rpc('submit_zuno_pulse_result',{p_score:Math.round(p.score),p_aura:Math.round(p.aura),p_completed:stats.completed,p_placement:rank});if(error)throw error;const r=data?.[0]||{};$('saving').textContent='✓ Resultado registrado · Nível de Jogos '+(r.game_level||'—')+' · '+(r.game_xp||0)+' XP total';window.dispatchEvent(new CustomEvent('zuno:game-complete',{detail:{game:'zuno-pulse',score:Math.round(p.score),aura:Math.round(p.aura),completed:stats.completed,placement:rank}}))}catch(e){console.warn('Zuno Pulse save',e);$('saving').textContent='Não foi possível registrar agora; seu recorde local foi mantido.'}}
function finishMatch(){clearAsync();active=false;$('progress').style.width='100%';renderPlayers();const rank=myRank(),p=me(),best=Number(localStorage.getItem('zunoplay_zuno_pulse_best')||0),score=Math.round(p.score);if(score>best)localStorage.setItem('zunoplay_zuno_pulse_best',String(score));const [title,subtitle]=awardTitle(rank,p);$('overlayIcon').textContent=rank===1?'👑⚡':'⚡🌀';$('overlayTitle').textContent=rank===1?'Zuno Master!':'Pulse concluído!';$('overlayText').textContent='Você atravessou todos os Pulses. Mesmo quando falhou, o Modo Echo manteve você na partida.';$('features').style.display='none';const grid=$('results');grid.classList.add('show');grid.innerHTML=`<div class="result"><small>POSIÇÃO</small><b>${rank}º/8</b></div><div class="result"><small>PONTOS</small><b>${score}</b></div><div class="result"><small>AURA</small><b>${Math.round(p.aura)}%</b></div><div class="result"><small>PULSES</small><b>${stats.completed}/6</b></div><div class="result"><small>ECHO</small><b>${stats.echoes}x</b></div><div class="result"><small>RECORDE</small><b>${Math.max(best,score)}</b></div>`;$('award').textContent=title+' · '+subtitle;$('award').classList.add('show');$('start').textContent='Jogar novamente';$('start').onclick=startMatch;$('overlay').classList.remove('hide');announce('Zuno Pulse concluído. Você ficou em '+rank+'º lugar.');persistResult(rank,p)}
async function waitClient(){for(let i=0;i<50;i++){if(window.ZunoSupabaseClient)return window.ZunoSupabaseClient;await sleep(100)}return null}
$('back').onclick=()=>location.href=fromRoom?'sala.html?room='+encodeURIComponent(roomId):'jogos.html';$('exit').onclick=$('back').onclick;$('start').onclick=startMatch;$('reduceMotion').onchange=e=>{reduceMotion=e.target.checked};$('reduceFlash').onchange=e=>{reduceFlash=e.target.checked};if(roomId)$('room').classList.add('show');
(async()=>{sb=await waitClient();if(!sb){renderPlayers();return}const{data}=await sb.auth.getSession();user=data?.session?.user||null;if(user){const{data:p}=await sb.from('profiles').select('username').eq('id',user.id).maybeSingle();playerName=p?.username||user.email?.split('@')[0]||'Você'}renderPlayers()})().catch(console.warn);
window.addEventListener('pagehide',clearAsync);
})();
