(()=>{
if(window.__ZUNO_RUSH__)return;window.__ZUNO_RUSH__=true;
const $=id=>document.getElementById(id),sleep=ms=>new Promise(r=>setTimeout(r,ms)),q=new URLSearchParams(location.search),roomId=q.get('room')||sessionStorage.getItem('zunoplay_room_id')||'',fromRoom=q.get('from')==='sala'&&!!roomId;
const bots=['Nova','Kiro','Lumi','Mako','Yara','Nox','Bibi'];
let sb=null,user=null,players=[],roundIndex=0,active=false,raf=0,timer=0,chaos=null,reduceMotion=false,playerName='Você';
const rounds=['run','color','pulse','boom'];
function escapeHtml(v){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function announce(t){$('live').textContent=t}
function vibrate(ms=20){if(!reduceMotion&&navigator.vibrate)navigator.vibrate(ms)}
function rand(min,max){return Math.random()*(max-min)+min}
function clamp(v,min,max){return Math.max(min,Math.min(max,v))}
function clearAsync(){if(timer){clearTimeout(timer);timer=0}if(raf){cancelAnimationFrame(raf);raf=0}}
function me(){return players[0]}
function sorted(){return [...players].sort((a,b)=>b.score-a.score||b.aura-a.aura)}
function myRank(){return Math.max(1,sorted().findIndex(p=>p.id==='me')+1)}
function renderHud(){const p=me()||{score:0,aura:0};$('score').textContent=Math.round(p.score);$('aura').textContent=Math.round(p.aura)+'%';$('auraFill').style.width=clamp(p.aura,0,100)+'%';$('rank').textContent=myRank()+'º';$('progress').style.width=(roundIndex/rounds.length*100)+'%'}
function renderPlayers(){const order=sorted();$('leaderboard').innerHTML=order.map((p,i)=>`<div class="player ${p.id==='me'?'me':''}"><div class="avatar">${p.id==='me'?'🙂':['🤖','🧑','👾','🦊'][i%4]}</div><b>${escapeHtml(p.name)}</b><span>${Math.round(p.score)} pts</span></div>`).join('');renderHud()}
function addResult(points,aura=0){const p=me();const multi=chaos?.type==='double'?1.25:1;p.score+=Math.round(points*multi);p.aura=clamp(p.aura+aura+(chaos?.type==='aura'?10:0),0,100);simulateBots(points);renderPlayers()}
function simulateBots(base){players.slice(1).forEach((p,i)=>{const skill=.55+Math.random()*.45;p.score+=Math.round(clamp(base*skill+rand(-110,190),90,1500));p.aura=clamp(p.aura+Math.round(rand(7,24)),0,100);if(i===roundIndex&&Math.random()>.55)p.score+=120})}
function chooseChaos(){if(Math.random()>.34)return null;const options=[{type:'double',label:'⚠ EVENTO DE CAOS: Pontuação ×1,25 nesta rodada!'},{type:'aura',label:'✨ EVENTO DE CAOS: Super Aura +10 em qualquer resultado!'},{type:'fast',label:'⚡ EVENTO DE CAOS: Ritmo acelerado!'}];return options[Math.floor(Math.random()*options.length)]}
function showChaos(){chaos=chooseChaos();$('chaos').classList.toggle('show',!!chaos);$('chaos').textContent=chaos?.label||''}
function setRound(title,kicker){$('roundTitle').textContent=title;$('roundKicker').textContent=kicker;$('progress').style.width=((roundIndex)/rounds.length*100)+'%';showChaos();announce(title)}
function feedback(text,good){const f=$('feedback');if(!f)return;f.textContent=text;f.className='feedback '+(good===true?'good':good===false?'bad':'')}
function endRound(points,aura,msg,good=true){if(!active)return;active=false;clearAsync();addResult(points,aura);feedback(msg,good);announce(msg);vibrate(good?24:50);timer=setTimeout(()=>{roundIndex++;if(roundIndex>=rounds.length)finishMatch();else startRound()},850)}
function startMatch(){clearAsync();players=[{id:'me',name:playerName,score:0,aura:0},...bots.map((name,i)=>({id:'b'+i,name,score:0,aura:0}))];roundIndex=0;active=false;$('overlay').classList.add('hide');$('resultGrid').hidden=true;$('featureGrid').hidden=false;renderPlayers();startRound()}
function startRound(){clearAsync();renderPlayers();const type=rounds[roundIndex];if(type==='run')runRound();else if(type==='color')colorRound();else if(type==='pulse')pulseRound();else boomRound()}
function runRound(){setRound('Zuno Run','RODADA 1/4 · MOVIMENTO');active=true;let lane=1,gates=0,score=0;const maxGates=5;const c=$('challenge');c.innerHTML='<div class="icon">🏃</div><h2>Zuno Run</h2><p>Mude de pista e evite os obstáculos. Use toque, ← → ou A/D.</p><div id="timer" class="timer">Portão 1 de 5</div><div class="playzone"><div id="lanes" class="lanes"></div><div class="lane-buttons"><button data-lane="0">← ESQ</button><button data-lane="1">CENTRO</button><button data-lane="2">DIR →</button></div></div><div id="feedback" class="feedback">Escolha uma pista.</div>';
const draw=(obstacle=-1)=>{$('lanes').innerHTML=[0,1,2].map(i=>`<div class="lane ${lane===i?'me':''}">${obstacle===i?'<div class="obstacle">🧱</div>':''}${lane===i?'<div class="runner">⚡</div>':''}</div>`).join('')};draw();
const choose=i=>{if(!active)return;lane=clamp(Number(i),0,2);draw(currentObstacle)};let currentObstacle=-1;$('challenge').querySelectorAll('[data-lane]').forEach(b=>b.onclick=()=>choose(b.dataset.lane));
const key=e=>{if(!active)return;if(e.key==='ArrowLeft'||e.key.toLowerCase()==='a')choose(lane-1);if(e.key==='ArrowRight'||e.key.toLowerCase()==='d')choose(lane+1)};document.addEventListener('keydown',key);
const gate=()=>{if(!active){document.removeEventListener('keydown',key);return}if(gates>=maxGates){document.removeEventListener('keydown',key);endRound(700+score*150,18+score*4,score>=4?'🏁 Corrida excelente! '+score+'/5 obstáculos evitados.':'Você chegou ao fim! '+score+'/5 obstáculos evitados.',score>=3);return}currentObstacle=Math.floor(Math.random()*3);draw(currentObstacle);$('timer').textContent='Portão '+(gates+1)+' de '+maxGates;const delay=chaos?.type==='fast'?700:950;timer=setTimeout(()=>{if(!active)return;if(lane!==currentObstacle){score++;feedback('✓ Desviou!',true)}else feedback('💥 Bateu, mas continua!',false);gates++;currentObstacle=-1;draw();timer=setTimeout(gate,260)},delay)};timer=setTimeout(gate,500)}
function colorRound(){setRound('Color Rush','RODADA 2/4 · PERCEPÇÃO');active=true;const colors=[{name:'ROXO',emoji:'🟣'},{name:'AZUL',emoji:'🔵'},{name:'VERDE',emoji:'🟢'},{name:'ROSA',emoji:'🌸'}],target=colors[Math.floor(Math.random()*colors.length)],start=performance.now();const c=$('challenge');c.innerHTML=`<div class="icon">🌈</div><h2>Color Rush</h2><p>Toque na opção indicada. O nome e o símbolo aparecem juntos para não depender só da cor.</p><div id="timer" class="timer">ALVO: <b>${target.emoji} ${target.name}</b></div><div class="playzone"><div class="choice-grid">${colors.map(x=>`<button class="choice" data-color="${x.name}"><strong>${x.emoji}</strong>${x.name}</button>`).join('')}</div></div><div id="feedback" class="feedback">Escolha rápido!</div>`;
const limit=chaos?.type==='fast'?2600:3600;$('challenge').querySelectorAll('[data-color]').forEach(b=>b.onclick=()=>{if(!active)return;const ok=b.dataset.color===target.name,elapsed=performance.now()-start;b.classList.add(ok?'correct':'wrong');const pts=ok?clamp(1500-elapsed*.22,650,1450):220;endRound(pts,ok?24:8,ok?'🌈 Perfeito! '+Math.round(elapsed)+' ms.':'Quase! O alvo era '+target.name+'.',ok)});timer=setTimeout(()=>endRound(180,6,'⏱ Tempo esgotado. Você continua na partida.',false),limit)}
function pulseRound(){setRound('Zuno Pulse','RODADA 3/4 · TIMING');active=true;const c=$('challenge');c.innerHTML='<div class="icon">⚡</div><h2>Zuno Pulse</h2><p>Pressione PULAR quando o pulso estiver dentro da zona central. Um botão grande basta.</p><div id="timer" class="timer">Aproxime o pulso do centro</div><div class="playzone"><div class="pulse-track"><div class="pulse-center"></div><div id="pulseDot" class="pulse-dot"></div></div><button id="jump" class="big-action">PULAR</button></div><div id="feedback" class="feedback">Você tem uma tentativa.</div>';
let started=performance.now(),pos=0,speed=chaos?.type==='fast'?.00095:.00072;const dot=$('pulseDot');const animate=t=>{if(!active)return;const dt=t-started;pos=(dt*speed)%2;let p=pos<=1?pos:2-pos;dot.style.left=(p*100)+'%';raf=requestAnimationFrame(animate)};raf=requestAnimationFrame(animate);
const key=e=>{if((e.code==='Space'||e.key==='Enter')&&active){e.preventDefault();jump()}};const jump=()=>{if(!active)return;document.removeEventListener('keydown',key);const left=parseFloat(dot.style.left||'0'),distance=Math.abs(50-left),pts=clamp(1500-distance*32,250,1500),good=distance<=12;endRound(pts,good?30:10,good?'⚡ PULSE PERFEITO! Distância '+distance.toFixed(1)+'%.':'Pulou fora do centro, mas segue no Rush. Distância '+distance.toFixed(1)+'%.',good)};$('jump').onclick=jump;document.addEventListener('keydown',key);timer=setTimeout(()=>{document.removeEventListener('keydown',key);endRound(200,6,'⏱ O pulso passou. Você continua.',false)},chaos?.type==='fast'?4200:5600)}
function boomRound(){setRound('Boom Room','RODADA 4/4 · MEMÓRIA');active=true;const safe=Math.floor(Math.random()*4),letters=['A','B','C','D'],c=$('challenge');c.innerHTML=`<div class="icon">💥</div><h2>Boom Room</h2><p>Memorize a plataforma segura. Ela vai piscar e depois todas ficarão iguais.</p><div id="timer" class="timer">MEMORIZE!</div><div class="playzone"><div class="platform-grid">${letters.map((l,i)=>`<button class="platform ${i===safe?'peek':''}" data-p="${i}" disabled>${l}</button>`).join('')}</div></div><div id="feedback" class="feedback">A plataforma segura está marcada agora.</div>`;
const peek=chaos?.type==='fast'?650:1050;timer=setTimeout(()=>{$('timer').textContent='ESCOLHA!';const start=performance.now();$('challenge').querySelectorAll('[data-p]').forEach(b=>{b.classList.remove('peek');b.disabled=false;b.onclick=()=>{if(!active)return;const ok=Number(b.dataset.p)===safe,elapsed=performance.now()-start;if(!ok)b.classList.add('explode');const pts=ok?clamp(1500-elapsed*.3,650,1450):250;endRound(pts,ok?30:8,ok?'🛡 Plataforma segura! Boa memória.':'💥 Explodiu! A segura era '+letters[safe]+'. Mesmo assim você terminou o Rush.',ok)}});feedback('Agora escolha A, B, C ou D.')},peek);timer=setTimeout(()=>{if(active)endRound(180,5,'⏱ Tempo esgotado. A segura era '+letters[safe]+'.',false)},peek+(chaos?.type==='fast'?2500:3500))}
function finishMatch(){clearAsync();active=false;$('progress').style.width='100%';renderPlayers();const rank=myRank(),p=me(),best=Number(localStorage.getItem('zunoplay_zuno_rush_best')||0);if(p.score>best)localStorage.setItem('zunoplay_zuno_rush_best',String(Math.round(p.score)));const xp=Math.round(60+p.score/45+(rank===1?60:rank<=3?30:0));$('overlayIcon').textContent=rank===1?'🏆⚡':'⚡🏁';$('overlayTitle').textContent=rank===1?'Campeão do Rush!':'Rush concluído!';$('overlayText').textContent='Você participou das quatro provas sem eliminação. Esta versão beta registra o melhor placar no dispositivo; recompensas econômicas ficam desligadas até a validação competitiva no servidor.';$('featureGrid').hidden=true;const grid=$('resultGrid');grid.hidden=false;grid.innerHTML=`<div class="result-card"><small>POSIÇÃO</small><b>${rank}º/8</b></div><div class="result-card"><small>PONTOS</small><b>${Math.round(p.score)}</b></div><div class="result-card"><small>AURA</small><b>${Math.round(p.aura)}%</b></div><div class="result-card"><small>XP BETA</small><b>+${xp}</b></div><div class="result-card"><small>MELHOR</small><b>${Math.max(best,Math.round(p.score))}</b></div><div class="result-card"><small>MOEDAS</small><b>🔒</b></div>`;$('start').textContent='Jogar novamente';$('start').onclick=startMatch;$('overlay').classList.remove('hide');announce('Zuno Rush concluído. Você ficou em '+rank+'º lugar.')}
async function waitClient(){for(let i=0;i<35;i++){if(window.ZunoSupabaseClient)return window.ZunoSupabaseClient;await sleep(100)}return null}
$('back').onclick=()=>location.href=fromRoom?'sala.html?room='+encodeURIComponent(roomId):'jogos.html';$('exit').onclick=$('back').onclick;$('start').onclick=startMatch;$('reduceMotion').onchange=e=>{reduceMotion=e.target.checked;document.documentElement.style.scrollBehavior=reduceMotion?'auto':''};if(roomId)$('room').textContent='● Sala ativa';
(async()=>{sb=await waitClient();if(!sb)return;const{data}=await sb.auth.getSession();user=data?.session?.user||null;if(user){playerName=user.user_metadata?.username||user.user_metadata?.name||user.email?.split('@')[0]||'Você'}renderPlayers()})().catch(console.warn);
window.addEventListener('pagehide',clearAsync);
})();
