(()=>{
if(window.__ZUNO_CORE__)return;window.__ZUNO_CORE__=true;
const $=id=>document.getElementById(id),canvas=$('arena'),ctx=canvas.getContext('2d'),W=canvas.width,H=canvas.height,CX=W/2,CY=H/2,R=398;
const q=new URLSearchParams(location.search),roomId=q.get('room')||sessionStorage.getItem('zunoplay_room_id')||'',fromRoom=q.get('from')==='sala'&&!!roomId;
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),rand=(a,b)=>Math.random()*(b-a)+a,dist=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y),now=()=>performance.now();
const botNames=['Nova','Kiro','Lumi','Mako','Yara','Nox','Bibi'],botColors=['#45dfff','#ff6dbd','#ffd166','#6cffb2','#8e6cff','#ff8c5a','#77a9ff'];
let sb=null,user=null,userName='Você',avatarUrl='',avatarImg=null,players=[],frags=[],portals=[],shockwaves=[],active=false,startedAt=0,last=0,raf=0,phase='collect',eventName='',eventUntil=0,finalStarted=false,matchEnded=false,linkTarget=null,linkUntil=0,linkCooldown=0,jumpingUntil=0,jumpCooldown=0,echoUntil=0,core=null,coreCarrier=null,controls={x:0,y:0,keys:new Set()},joyPointer=null,joyCenter={x:0,y:0},best=Number(localStorage.getItem('zunoplay_zuno_core_best')||0);
const stats={links:0,fragments:0,echoes:0,coreSeconds:0};
function announce(t){$('live').textContent=t}
function banner(t){$('banner').textContent=t;announce(t)}
function formatTime(ms){const s=Math.max(0,Math.ceil(ms/1000)),m=Math.floor(s/60),r=s%60;return String(m).padStart(2,'0')+':'+String(r).padStart(2,'0')}
function phaseText(){if(phase==='collect')return['FASE 1','Coleta'];if(phase==='converge')return['FASE 2','Convergência'];if(phase==='rupture')return['FASE 3','Ruptura'];return['CORE FINAL','Capture e defenda']}
function scoreOf(p){return Math.round((p.energy||0)+(p.coreTime||0)*42+(p.links||0)*70-(p.echoes||0)*45)}
function sorted(){return [...players].sort((a,b)=>scoreOf(b)-scoreOf(a))}
function me(){return players[0]}
function updateHud(){const p=me()||{energy:0};const rank=Math.max(1,sorted().findIndex(x=>x.id==='me')+1);$('rank').textContent=rank+'º/8';$('energyText').textContent=Math.round(p.energy||0);$('links').textContent=stats.links;$('coreTime').textContent=stats.coreSeconds.toFixed(1)+'s';$('energyBar').style.width=clamp((p.energy||0)/300*100,0,100)+'%';const pt=phaseText();$('phaseKicker').textContent=pt[0];$('phaseTitle').textContent=pt[1];$('timer').textContent=formatTime(85000-(now()-startedAt));$('link').classList.toggle('cool',linkCooldown>now())}
function createPlayer(id,name,x,y,color,isBot=false){return{id,name,x,y,vx:0,vy:0,r:22,color,isBot,energy:0,links:0,echoes:0,coreTime:0,aiAngle:rand(0,Math.PI*2),aiThink:0,target:null}}
function reset(){players=[createPlayer('me',userName,CX,CY+150,'#b85cff',false)];for(let i=0;i<7;i++){const a=i/7*Math.PI*2;players.push(createPlayer('b'+i,botNames[i],CX+Math.cos(a)*250,CY+Math.sin(a)*250,botColors[i],true))}frags=[];portals=[];shockwaves=[];phase='collect';eventName='';eventUntil=0;finalStarted=false;matchEnded=false;linkTarget=null;linkUntil=0;linkCooldown=0;jumpingUntil=0;jumpCooldown=0;echoUntil=0;core={x:CX,y:CY,r:30,vx:85,vy:60};coreCarrier=null;stats.links=0;stats.fragments=0;stats.echoes=0;stats.coreSeconds=0;for(let i=0;i<24;i++)spawnFrag();startedAt=now();last=startedAt;active=true;$('overlay').classList.add('hide');banner('💎 Colete Fragmentos Core. Aproxime-se de alguém e use LINK.');updateHud();cancelAnimationFrame(raf);raf=requestAnimationFrame(loop)}
function spawnFrag(){let a=rand(0,Math.PI*2),rr=rand(70,R-38);frags.push({x:CX+Math.cos(a)*rr,y:CY+Math.sin(a)*rr,r:10,value:Math.round(rand(9,18)),spin:rand(0,Math.PI*2)})}
function keepInArena(p){const dx=p.x-CX,dy=p.y-CY,d=Math.hypot(dx,dy),lim=R-p.r;if(d>lim){p.x=CX+dx/d*lim;p.y=CY+dy/d*lim;p.vx*=.3;p.vy*=.3}}
function setEcho(p,ms=3300){if(p.id==='me'){if(echoUntil>now())return;echoUntil=now()+ms;stats.echoes++;banner('👻 Echo Mode! Você continua jogando e volta em alguns segundos.')}p.echoes=(p.echoes||0)+1;p.echoUntil=now()+ms;if(coreCarrier===p.id){coreCarrier=null;core.x=p.x;core.y=p.y}}
function nearestLinkCandidate(){const p=me();let bestP=null,bestD=999;for(const other of players.slice(1)){if((other.echoUntil||0)>now())continue;const d=dist(p,other);if(d<bestD){bestD=d;bestP=other}}return bestD<=145?bestP:null}
function activateLink(){if(!active||matchEnded||linkCooldown>now()||echoUntil>now())return;const target=nearestLinkCandidate();if(!target){banner('🔗 Aproxime-se de outro jogador para criar o Pulse Link.');return}linkTarget=target.id;linkUntil=now()+6200;linkCooldown=now()+1800;stats.links++;me().links++;target.links++;banner('🔗 Pulse Link com '+target.name+'! Energia compartilhada por 6s.');navigator.vibrate?.(25)}
function jump(){if(!active||matchEnded||jumpCooldown>now()||echoUntil>now())return;jumpingUntil=now()+620;jumpCooldown=now()+1900;const p=me(),m=Math.hypot(controls.x,controls.y);if(m>.1){p.x+=controls.x/m*46;p.y+=controls.y/m*46;keepInArena(p)}navigator.vibrate?.(12)}
function collect(p,f,index){p.energy+=f.value*(p.id==='me'&&linkTarget&&linkUntil>now()?1.45:1);if(p.id==='me'){stats.fragments++;if(linkTarget&&linkUntil>now()){const mate=players.find(x=>x.id===linkTarget);if(mate)mate.energy+=f.value*.35}}frags.splice(index,1);spawnFrag();if(Math.random()<.22)spawnFrag()}
function portalTouch(p){if(eventName!=='rift'||!portals.length)return;for(let i=0;i<portals.length;i++){const po=portals[i];if(Math.hypot(p.x-po.x,p.y-po.y)<34){const other=portals[(i+1)%portals.length];p.x=other.x+(Math.random()-.5)*34;p.y=other.y+(Math.random()-.5)*34;if(p.id==='me')banner('🌀 Rift! Você atravessou a arena.');break}}
}
function updatePlayer(p,dt){const t=now(),echo=(p.echoUntil||0)>t;if(p.id==='me'){
 let x=controls.x,y=controls.y;if(controls.keys.has('arrowleft')||controls.keys.has('a'))x-=1;if(controls.keys.has('arrowright')||controls.keys.has('d'))x+=1;if(controls.keys.has('arrowup')||controls.keys.has('w'))y-=1;if(controls.keys.has('arrowdown')||controls.keys.has('s'))y+=1;let m=Math.hypot(x,y);if(m>1){x/=m;y/=m}let speed=echo?255:(eventName==='gravity'?230:205);if(coreCarrier==='me')speed*=linkTarget&&linkUntil>t?.86:.62;p.x+=x*speed*dt;p.y+=y*speed*dt;keepInArena(p);portalTouch(p)
 }else updateBot(p,dt);
 for(let i=frags.length-1;i>=0;i--){if(Math.hypot(p.x-frags[i].x,p.y-frags[i].y)<p.r+frags[i].r+4){collect(p,frags[i],i);break}}
 if(phase==='final')coreInteraction(p,dt);
}
function updateBot(p,dt){const t=now(),echo=(p.echoUntil||0)>t;if(t>p.aiThink){p.aiThink=t+rand(500,1100);if(phase==='final'){if(coreCarrier&&coreCarrier!==p.id){const c=players.find(x=>x.id===coreCarrier);p.target=c||core}else p.target=core}else{let nearest=null,bd=999;for(const f of frags){const d=Math.hypot(p.x-f.x,p.y-f.y);if(d<bd){bd=d;nearest=f}}p.target=nearest||{x:CX,y:CY}}}
 let tx=p.target?.x??CX,ty=p.target?.y??CY,dx=tx-p.x,dy=ty-p.y,m=Math.hypot(dx,dy)||1;let speed=echo?230:(eventName==='gravity'?205:175);if(coreCarrier===p.id)speed*=.67;p.x+=dx/m*speed*dt;p.y+=dy/m*speed*dt;keepInArena(p);portalTouch(p);
 if(Math.random()<.0015&&phase!=='final')p.energy+=8;
}
function coreInteraction(p,dt){const t=now();if((p.echoUntil||0)>t)return;if(coreCarrier===p.id){p.coreTime+=dt;if(p.id==='me')stats.coreSeconds+=dt;core.x=p.x;core.y=p.y-30;return}if(coreCarrier){const c=players.find(x=>x.id===coreCarrier);if(c&&dist(p,c)<p.r+c.r+10&&Math.random()<dt*(p.isBot?1.2:.45)){coreCarrier=p.id;banner(p.id==='me'?'👑 Você roubou o Core!':'⚡ '+p.name+' tomou o Core.')}}else if(Math.hypot(p.x-core.x,p.y-core.y)<p.r+core.r+6){coreCarrier=p.id;banner(p.id==='me'?'👑 CORE CAPTURADO! Segure até o final.':'⚡ '+p.name+' capturou o Core.')}
}
function updateCore(dt){if(phase!=='final'||coreCarrier)return;core.x+=core.vx*dt;core.y+=core.vy*dt;const d=Math.hypot(core.x-CX,core.y-CY);if(d>R-55){const nx=(core.x-CX)/d,ny=(core.y-CY)/d,dot=core.vx*nx+core.vy*ny;core.vx-=2*dot*nx;core.vy-=2*dot*ny;core.x=CX+nx*(R-56);core.y=CY+ny*(R-56)}}
function triggerShockwave(){eventName='shock';eventUntil=now()+7200;shockwaves=[];banner('🌊 RUPTURA: pule sobre as ondas de choque!');for(let i=0;i<5;i++)shockwaves.push({born:now()+i*1250,speed:150,hit:false})}
function triggerGravity(){eventName='gravity';eventUntil=now()+9200;banner('🌌 BAIXA GRAVIDADE: movimento acelerado e saltos mais seguros.');}
function triggerRifts(){eventName='rift';eventUntil=now()+9000;portals=[{x:CX-R+75,y:CY-80},{x:CX+R-75,y:CY+80}];banner('🌀 RIFTS ABERTOS: atravesse os portais para cruzar a arena.');}
function updateEvents(t,elapsed){if(!eventName){if(elapsed>18000&&elapsed<26000)triggerShockwave();else if(elapsed>34000&&elapsed<44000)triggerGravity();else if(elapsed>49000&&elapsed<58000)triggerRifts()}if(eventName&&t>eventUntil){eventName='';portals=[];shockwaves=[];banner(phase==='final'?'👑 Core Final em andamento.':'⚡ A arena estabilizou. Continue coletando.')}if(eventName==='shock')updateShockwaves(t)}
function updateShockwaves(t){const p=me();for(const w of shockwaves){if(t<w.born)continue;const radius=(t-w.born)/1000*w.speed;if(!w.hit&&echoUntil<t&&jumpingUntil<t){const d=Math.hypot(p.x-CX,p.y-CY);if(Math.abs(d-radius)<18){w.hit=true;setEcho(p)}}}}
function updatePhase(elapsed){if(elapsed<26000)phase='collect';else if(elapsed<49000)phase='converge';else if(elapsed<60000)phase='rupture';else if(!finalStarted){finalStarted=true;phase='final';eventName='';portals=[];shockwaves=[];frags.length=Math.min(frags.length,9);core.x=CX;core.y=CY;coreCarrier=null;banner('👑 CORE FINAL! Encoste no Núcleo e defenda a posse.')}if(finalStarted)phase='final'}
function drawArena(){ctx.clearRect(0,0,W,H);const g=ctx.createRadialGradient(CX,CY,30,CX,CY,R);g.addColorStop(0,'#24153f');g.addColorStop(.55,'#10152a');g.addColorStop(1,'#080b16');ctx.fillStyle=g;ctx.fillRect(0,0,W,H);ctx.save();ctx.beginPath();ctx.arc(CX,CY,R,0,Math.PI*2);ctx.clip();
 ctx.strokeStyle='rgba(126,87,193,.18)';ctx.lineWidth=2;for(let r=90;r<R;r+=82){ctx.beginPath();ctx.arc(CX,CY,r,0,Math.PI*2);ctx.stroke()}for(let a=0;a<Math.PI*2;a+=Math.PI/8){ctx.beginPath();ctx.moveTo(CX,CY);ctx.lineTo(CX+Math.cos(a)*R,CY+Math.sin(a)*R);ctx.stroke()}
 if(eventName==='rift')drawPortals();if(eventName==='shock')drawShockwaves();drawFragments();if(phase==='final')drawCore();drawLinks();drawPlayers();ctx.restore();ctx.strokeStyle='#6847a1';ctx.lineWidth=5;ctx.beginPath();ctx.arc(CX,CY,R,0,Math.PI*2);ctx.stroke();}
function drawFragments(){for(const f of frags){ctx.save();ctx.translate(f.x,f.y);ctx.rotate(f.spin+=.012);ctx.shadowColor='#63dcff';ctx.shadowBlur=15;ctx.fillStyle='#b9f4ff';ctx.beginPath();ctx.moveTo(0,-11);ctx.lineTo(8,0);ctx.lineTo(0,11);ctx.lineTo(-8,0);ctx.closePath();ctx.fill();ctx.restore()}}
function drawPortals(){for(const p of portals){ctx.save();ctx.translate(p.x,p.y);ctx.strokeStyle='#b35cff';ctx.shadowColor='#a84dff';ctx.shadowBlur=22;for(let i=0;i<3;i++){ctx.lineWidth=4-i;ctx.beginPath();ctx.ellipse(0,0,22+i*8,38-i*4,0,0,Math.PI*2);ctx.stroke()}ctx.restore()}}
function drawShockwaves(){const t=now();for(const w of shockwaves){if(t<w.born)continue;const r=(t-w.born)/1000*w.speed;if(r>R+40)continue;ctx.strokeStyle='rgba(93,222,255,.55)';ctx.lineWidth=10;ctx.beginPath();ctx.arc(CX,CY,r,0,Math.PI*2);ctx.stroke()}}
function drawCore(){ctx.save();ctx.translate(core.x,core.y);ctx.shadowColor='#c35cff';ctx.shadowBlur=34;const g=ctx.createRadialGradient(-8,-8,3,0,0,34);g.addColorStop(0,'#fff');g.addColorStop(.18,'#f3b5ff');g.addColorStop(.48,'#b04cff');g.addColorStop(1,'#3a1769');ctx.fillStyle=g;ctx.beginPath();ctx.arc(0,0,core.r,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#f3d3ff';ctx.lineWidth=2;ctx.stroke();ctx.restore()}
function drawLinks(){const t=now();if(linkTarget&&linkUntil>t){const a=me(),b=players.find(x=>x.id===linkTarget);if(b){ctx.save();ctx.strokeStyle='#55e5ff';ctx.lineWidth=8;ctx.shadowColor='#6ae7ff';ctx.shadowBlur=18;ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.stroke();ctx.strokeStyle='#d18cff';ctx.lineWidth=2;ctx.stroke();ctx.restore()}}else if(linkTarget&&linkUntil<=t)linkTarget=null}
function drawPlayers(){const t=now();for(const p of players){const echo=(p.echoUntil||0)>t,jumping=p.id==='me'&&jumpingUntil>t;ctx.save();ctx.translate(p.x,p.y);if(jumping)ctx.scale(1.14,1.14);ctx.globalAlpha=echo?.48:1;ctx.shadowColor=echo?'#6be6ff':p.color;ctx.shadowBlur=p.id==='me'?22:12;ctx.fillStyle=echo?'#76ddff':p.color;ctx.beginPath();ctx.arc(0,0,p.r,0,Math.PI*2);ctx.fill();ctx.lineWidth=p.id==='me'?4:2;ctx.strokeStyle=p.id==='me'?'#fff':'rgba(255,255,255,.55)';ctx.stroke();if(p.id==='me'&&avatarImg?.complete){ctx.save();ctx.beginPath();ctx.arc(0,0,p.r-3,0,Math.PI*2);ctx.clip();try{ctx.drawImage(avatarImg,-p.r+3,-p.r+3,(p.r-3)*2,(p.r-3)*2)}catch(_){}ctx.restore()}else{ctx.fillStyle='#fff';ctx.font='900 16px system-ui';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText((p.name||'?').charAt(0).toUpperCase(),0,1)}if(coreCarrier===p.id){ctx.font='20px system-ui';ctx.fillText('👑',0,-35)}ctx.globalAlpha=1;ctx.fillStyle='#fff';ctx.font='800 12px system-ui';ctx.textAlign='center';ctx.fillText(p.id==='me'?'VOCÊ':p.name,0,p.r+18);ctx.restore()}}
function update(dt,t){const elapsed=t-startedAt;updatePhase(elapsed);updateEvents(t,elapsed);if(linkTarget&&linkUntil>t){const mate=players.find(x=>x.id===linkTarget);if(!mate||dist(me(),mate)>190)linkUntil=t}for(const p of players)updatePlayer(p,dt);updateCore(dt);if(elapsed>=85000)finishMatch();updateHud()}
function loop(t){if(!active)return;const dt=clamp((t-last)/1000,0,.034);last=t;update(dt,t);drawArena();if(active)raf=requestAnimationFrame(loop)}
function finishMatch(){if(matchEnded)return;matchEnded=true;active=false;cancelAnimationFrame(raf);const order=sorted(),rank=Math.max(1,order.findIndex(x=>x.id==='me')+1),score=scoreOf(me());if(score>best){best=score;localStorage.setItem('zunoplay_zuno_core_best',String(score))}$('overlayTitle').textContent=rank===1?'Core Master!':'Protótipo concluído';$('overlayText').textContent='Você testou o loop central: coleta, Pulse Link, rupturas, Echo Mode e disputa pelo Core. O próximo passo é transformar os bots em jogadores reais via Realtime.';$('features').style.display='none';const grid=$('resultGrid');grid.classList.add('show');grid.innerHTML='<div class="result"><small>POSIÇÃO</small><b>'+rank+'º/8</b></div><div class="result"><small>PONTOS</small><b>'+score+'</b></div><div class="result"><small>ENERGIA</small><b>'+Math.round(me().energy)+'</b></div><div class="result"><small>LINKS</small><b>'+stats.links+'</b></div><div class="result"><small>CORE</small><b>'+stats.coreSeconds.toFixed(1)+'s</b></div><div class="result"><small>RECORDE</small><b>'+best+'</b></div>';$('start').textContent='Jogar novamente';$('overlay').classList.remove('hide');banner('🏁 Partida encerrada · '+rank+'º lugar · '+score+' pontos');announce('Zuno Core concluído')}
function setupInput(){const joy=$('joystick'),nub=$('joynub');function joyMove(e){if(joyPointer!==e.pointerId)return;const r=joy.getBoundingClientRect(),cx=r.left+r.width/2,cy=r.top+r.height/2,dx=e.clientX-cx,dy=e.clientY-cy,m=Math.hypot(dx,dy),lim=r.width*.33,k=m>lim?lim/m:1;controls.x=dx/lim*k;controls.y=dy/lim*k;nub.style.transform='translate(calc(-50% + '+(controls.x*31)+'px),calc(-50% + '+(controls.y*31)+'px))'}function joyEnd(e){if(joyPointer!==e.pointerId)return;joyPointer=null;controls.x=controls.y=0;nub.style.transform='translate(-50%,-50%)'}joy.onpointerdown=e=>{joyPointer=e.pointerId;joy.setPointerCapture?.(e.pointerId);joyMove(e)};joy.onpointermove=joyMove;joy.onpointerup=joyEnd;joy.onpointercancel=joyEnd;window.addEventListener('keydown',e=>{const k=e.key.toLowerCase();controls.keys.add(k);if(k===' '){e.preventDefault();jump()}if(k==='e'||k==='enter'){e.preventDefault();activateLink()}});window.addEventListener('keyup',e=>controls.keys.delete(e.key.toLowerCase()));$('jump').onclick=jump;$('link').onclick=activateLink}
async function loadProfile(){for(let i=0;i<40;i++){if(window.ZunoSupabaseClient){sb=window.ZunoSupabaseClient;break}await new Promise(r=>setTimeout(r,100))}if(!sb)return;const{data}=await sb.auth.getSession();user=data?.session?.user||null;if(!user)return;userName=user.user_metadata?.username||user.user_metadata?.name||user.email?.split('@')[0]||'Você';try{const{data:p}=await sb.from('profiles').select('username,avatar_url').eq('id',user.id).maybeSingle();if(p?.username)userName=p.username;if(p?.avatar_url)avatarUrl=p.avatar_url}catch(_){}if(avatarUrl){avatarImg=new Image();avatarImg.crossOrigin='anonymous';avatarImg.src=avatarUrl}}
$('back').onclick=()=>location.href=fromRoom?'sala.html?room='+encodeURIComponent(roomId):'jogos.html';$('exit').onclick=$('back').onclick;$('start').onclick=reset;if(roomId)$('room').classList.add('show');setupInput();loadProfile().catch(()=>{});drawArena();updateHud();window.addEventListener('pagehide',()=>{active=false;cancelAnimationFrame(raf)});
})();