(()=>{
if(window.__ZUNO_CORE_V03__)return;window.__ZUNO_CORE_V03__=true;
const $=id=>document.getElementById(id),canvas=$('arena'),ctx=canvas.getContext('2d',{alpha:false}),W=canvas.width,H=canvas.height,CX=W/2,CY=H/2,R=398;
const q=new URLSearchParams(location.search),roomId=q.get('room')||sessionStorage.getItem('zunoplay_room_id')||'',fromRoom=q.get('from')==='sala'&&!!roomId;
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),rand=(a,b)=>Math.random()*(b-a)+a,now=()=>performance.now(),dist=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y);
const names=['Nova','Kiro','Lumi','Mako','Yara','Nox','Bibi'],colors=['#45dfff','#ff6dbd','#ffd166','#6cffb2','#8e6cff','#ff8c5a','#77a9ff'],roles=['collector','hunter','support','chaos','collector','hunter','support'];
let sb=null,user=null,userName='Você',players=[],frags=[],particles=[],waves=[],active=false,ended=false,startedAt=0,last=0,raf=0,phase='collect',eventName='',eventUntil=0,core=null,coreCarrier=null,linkTarget=null,linkUntil=0,linkCooldown=0,jumpUntil=0,jumpCooldown=0,controls={x:0,y:0,keys:new Set()},joyPointer=null,best=Number(localStorage.getItem('zunoplay_zuno_core_best')||0),avatarConfig=null;
const stats={links:0,fragments:0,rare:0,echoes:0,coreSeconds:0,pads:0};
const padDefs=[
 {x:CX,y:CY-R+92,type:'boost',icon:'⇧',label:'IMPULSO'},
 {x:CX+235,y:CY-165,type:'shield',icon:'◇',label:'ESCUDO'},
 {x:CX+260,y:CY+105,type:'charge',icon:'⚡',label:'CARGA'},
 {x:CX+95,y:CY+270,type:'link',icon:'↔',label:'LINK+'},
 {x:CX-185,y:CY+215,type:'boost',icon:'⇧',label:'IMPULSO'},
 {x:CX-270,y:CY+55,type:'shield',icon:'◇',label:'ESCUDO'},
 {x:CX-230,y:CY-175,type:'charge',icon:'⚡',label:'CARGA'}
];
const fragKinds=[
 {kind:'common',value:12,color:'#8df5ff',size:9,weight:.72},
 {kind:'prism',value:26,color:'#c66cff',size:12,weight:.22},
 {kind:'gold',value:44,color:'#ffd56a',size:14,weight:.06}
];
function announce(t){if($('live'))$('live').textContent=t}
function banner(t){if($('banner'))$('banner').textContent=t;announce(t)}
function fmt(ms){const s=Math.max(0,Math.ceil(ms/1000));return String(Math.floor(s/60)).padStart(2,'0')+':'+String(s%60).padStart(2,'0')}
function me(){return players[0]}
function score(p){return Math.round((p.energy||0)+(p.coreTime||0)*45+(p.links||0)*70-(p.echoes||0)*40)}
function order(){return [...players].sort((a,b)=>score(b)-score(a))}
function phaseLabel(){if(phase==='collect')return['FASE 1','Coleta'];if(phase==='converge')return['FASE 2','Convergência'];if(phase==='rupture')return['FASE 3','Ruptura'];return['CORE FINAL','Capture e defenda']}
function pickKind(){let n=Math.random(),a=0;for(const k of fragKinds){a+=k.weight;if(n<=a)return k}return fragKinds[0]}
function arenaPoint(min=80,max=R-45){const a=rand(0,Math.PI*2),rr=rand(min,max);return{x:CX+Math.cos(a)*rr,y:CY+Math.sin(a)*rr}}
function burst(x,y,color,count=8){for(let i=0;i<count;i++)particles.push({x,y,vx:rand(-110,110),vy:rand(-110,110),life:rand(.35,.7),max:1,color,size:rand(2,5)})}
function tone(freq=420,d=.04,vol=.025){try{const AC=window.AudioContext||window.webkitAudioContext;if(!AC)return;const ac=window.__zunoAudio||(window.__zunoAudio=new AC()),o=ac.createOscillator(),g=ac.createGain();o.frequency.value=freq;g.gain.value=vol;o.connect(g);g.connect(ac.destination);o.start();g.gain.exponentialRampToValueAtTime(.001,ac.currentTime+d);o.stop(ac.currentTime+d)}catch(_){}}
function player(id,name,x,y,color,isBot=false,role='collector'){return{id,name,x,y,r:24,color,isBot,role,energy:0,links:0,echoes:0,coreTime:0,echoUntil:0,shieldUntil:0,speedUntil:0,linkBoostUntil:0,padUntil:0,aiThink:0,target:null,avatar:null,avatarReady:false}}
function spawnFrag(){const p=arenaPoint(),k=pickKind();frags.push({x:p.x,y:p.y,r:k.size,value:k.value,kind:k.kind,color:k.color,spin:rand(0,6.28)})}
function reset(){players=[player('me',userName,CX,CY+170,'#b85cff',false,'player')];for(let i=0;i<7;i++){const a=i/7*Math.PI*2;players.push(player('b'+i,names[i],CX+Math.cos(a)*260,CY+Math.sin(a)*260,colors[i],true,roles[i]))}frags=[];particles=[];waves=[];for(let i=0;i<16;i++)spawnFrag();phase='collect';eventName='';eventUntil=0;core={x:CX,y:CY,r:32,vx:95,vy:70,charge:0};coreCarrier=null;linkTarget=null;linkUntil=0;linkCooldown=0;jumpUntil=0;jumpCooldown=0;stats.links=stats.fragments=stats.rare=stats.echoes=stats.coreSeconds=stats.pads=0;active=true;ended=false;startedAt=last=now();$('overlay')?.classList.add('hide');banner('💎 Colete energia. Use as plataformas e conecte-se quando o LINK acender.');loadArenaAvatars();cancelAnimationFrame(raf);raf=requestAnimationFrame(loop)}
function keep(p){const dx=p.x-CX,dy=p.y-CY,d=Math.hypot(dx,dy),lim=R-p.r;if(d>lim){p.x=CX+dx/d*lim;p.y=CY+dy/d*lim}}
function candidate(){const p=me();if(!p)return null;let best=null,bd=999;const max=p.linkBoostUntil>now()?185:150;for(const o of players.slice(1)){if(o.echoUntil>now())continue;const d=dist(p,o);if(d<bd){bd=d;best=o}}return bd<max?best:null}
function activateLink(){if(!active||ended||linkCooldown>now()||me().echoUntil>now())return;const t=candidate();if(!t){banner('🔗 Aproxime-se de outro jogador. O botão acende quando houver alvo.');return}linkTarget=t.id;linkUntil=now()+6500;linkCooldown=now()+1700;stats.links++;me().links++;t.links++;burst(me().x,me().y,'#64eaff',14);burst(t.x,t.y,'#c66cff',14);tone(620,.08,.04);navigator.vibrate?.(22);banner('🔗 Pulse Link com '+t.name+' · coleta +50% por 6s.')}
function jump(){if(!active||ended||jumpCooldown>now()||me().echoUntil>now())return;jumpUntil=now()+620;jumpCooldown=now()+1800;const p=me(),m=Math.hypot(controls.x,controls.y);if(m>.08){p.x+=controls.x/m*58;p.y+=controls.y/m*58;keep(p)}burst(p.x,p.y,'#a86cff',8);tone(300,.04,.018);navigator.vibrate?.(10)}
function echo(p,ms=3000){if(p.shieldUntil>now()){p.shieldUntil=0;burst(p.x,p.y,'#75f8ff',12);return}if(p.echoUntil>now())return;p.echoUntil=now()+ms;p.echoes++;if(p.id==='me'){stats.echoes++;banner('👻 Echo Mode · você continua jogando e retorna em 3s.');navigator.vibrate?.([20,30,20])}if(coreCarrier===p.id){coreCarrier=null;core.x=p.x;core.y=p.y}burst(p.x,p.y,'#77eaff',16)}
function usePad(p,pad){const t=now();if(p.padUntil>t)return;p.padUntil=t+2200;if(pad.type==='boost'){p.speedUntil=t+3300;burst(p.x,p.y,'#6b8cff',10);if(p.id==='me')banner('⇧ Impulso ativado · velocidade aumentada.')}if(pad.type==='shield'){p.shieldUntil=t+4200;burst(p.x,p.y,'#63efff',10);if(p.id==='me')banner('◇ Escudo ativo por 4s.')}if(pad.type==='charge'){p.energy+=28;burst(p.x,p.y,'#ffd166',12);if(p.id==='me')banner('⚡ Plataforma de Carga · +28 Energia.')}if(pad.type==='link'){p.linkBoostUntil=t+5000;if(p.id==='me'){linkCooldown=Math.min(linkCooldown,t);banner('↔ LINK+ · alcance ampliado e recarga pronta.')}}if(p.id==='me')stats.pads++}
function pads(p){for(const pad of padDefs)if(Math.hypot(p.x-pad.x,p.y-pad.y)<42)usePad(p,pad)}
function collect(p,f,i){let mult=1;if(p.id==='me'&&linkTarget&&linkUntil>now())mult=1.5;p.energy+=f.value*mult;if(p.id==='me'){stats.fragments++;if(f.kind!=='common')stats.rare++;tone(f.kind==='gold'?760:f.kind==='prism'?600:480,.035,.018);if(f.kind!=='common')navigator.vibrate?.(8)}burst(f.x,f.y,f.color,f.kind==='common'?5:10);frags.splice(i,1);if(frags.length<16)spawnFrag();if(Math.random()<.10&&frags.length<18)spawnFrag()}
function moveHuman(p,dt){let x=controls.x,y=controls.y;if(controls.keys.has('a')||controls.keys.has('arrowleft'))x--;if(controls.keys.has('d')||controls.keys.has('arrowright'))x++;if(controls.keys.has('w')||controls.keys.has('arrowup'))y--;if(controls.keys.has('s')||controls.keys.has('arrowdown'))y++;const m=Math.hypot(x,y);if(m>1){x/=m;y/=m}let sp=p.echoUntil>now()?270:205;if(p.speedUntil>now())sp*=1.38;if(coreCarrier==='me')sp*=linkTarget&&linkUntil>now()?.82:.62;p.x+=x*sp*dt;p.y+=y*sp*dt;keep(p)}
function botTarget(p){if(phase==='final'){if(coreCarrier&&coreCarrier!==p.id){const c=players.find(v=>v.id===coreCarrier);return c||core}return core}if(p.role==='hunter'){const target=order()[0];if(target&&target.id!==p.id&&Math.random()<.55)return target}if(p.role==='support'){let closest=null,bd=999;for(const o of players){if(o.id===p.id)continue;const d=dist(p,o);if(d<bd){bd=d;closest=o}}if(closest&&bd<180&&Math.random()<.45){p.links++;closest.links++;p.botLink={id:closest.id,until:now()+3200}}}if(p.role==='chaos'&&Math.random()<.3)return arenaPoint(50,R-40);let best=null,bd=999;for(const f of frags){let d=dist(p,f);if(f.kind==='gold')d*=.58;else if(f.kind==='prism')d*=.76;if(d<bd){bd=d;best=f}}return best||arenaPoint()}
function moveBot(p,dt){const t=now();if(t>p.aiThink){p.aiThink=t+rand(450,950);p.target=botTarget(p)}const tx=p.target?.x??CX,ty=p.target?.y??CY,dx=tx-p.x,dy=ty-p.y,m=Math.hypot(dx,dy)||1;let sp=p.echoUntil>t?235:170;if(p.speedUntil>t)sp*=1.3;if(coreCarrier===p.id)sp*=.65;p.x+=dx/m*sp*dt;p.y+=dy/m*sp*dt;keep(p)}
function corePlay(p,dt){if(phase!=='final'||p.echoUntil>now())return;if(coreCarrier===p.id){p.coreTime+=dt;if(p.id==='me')stats.coreSeconds+=dt;core.x=p.x;core.y=p.y-32;return}if(coreCarrier){const c=players.find(v=>v.id===coreCarrier);if(c&&dist(p,c)<48&&Math.random()<dt*(p.isBot?1.0:.55)){coreCarrier=p.id;burst(p.x,p.y,'#ffda7a',16);if(p.id==='me')banner('👑 Você roubou o Core! Defenda a posse.');else if(c.id==='me')banner('⚠️ '+p.name+' roubou o Core.')}}else if(Math.hypot(p.x-core.x,p.y-core.y)<55){coreCarrier=p.id;burst(core.x,core.y,'#d269ff',22);if(p.id==='me')banner('👑 CORE CAPTURADO! Segure até o final.')}}
function stepPlayer(p,dt){p.id==='me'?moveHuman(p,dt):moveBot(p,dt);pads(p);for(let i=frags.length-1;i>=0;i--){if(dist(p,frags[i])<p.r+frags[i].r+3){collect(p,frags[i],i);break}}corePlay(p,dt)}
function updateParticles(dt){for(let i=particles.length-1;i>=0;i--){const p=particles[i];p.life-=dt;p.x+=p.vx*dt;p.y+=p.vy*dt;p.vx*=.95;p.vy*=.95;if(p.life<=0)particles.splice(i,1)}}
function updateWaves(t){const p=me();for(const w of waves){if(t<w.born)continue;const rr=(t-w.born)/1000*w.speed;if(!w.hit&&p.echoUntil<t&&jumpUntil<t&&Math.abs(dist(p,{x:CX,y:CY})-rr)<18){w.hit=true;echo(p)}}}
function events(t,e){if(!eventName&&e>18000&&e<26000){eventName='shock';eventUntil=t+7200;waves=[0,1300,2600,3900].map(d=>({born:t+d,speed:155,hit:false}));banner('🌊 RUPTURA · pule sobre as ondas de choque.')}else if(!eventName&&e>35000&&e<44000){eventName='surge';eventUntil=t+7800;banner('⚡ SURGE · plataformas de Carga e Impulso estão fortalecidas.')}else if(!eventName&&e>50000&&e<59000){eventName='gravity';eventUntil=t+7800;banner('🌌 BAIXA GRAVIDADE · movimento acelerado.')}if(eventName==='shock')updateWaves(t);if(eventName&&t>eventUntil){eventName='';waves=[];banner(phase==='final'?'👑 Core Final em andamento.':'⚡ Arena estabilizada. Continue acumulando energia.')}}
function updatePhase(e){const next=e<26000?'collect':e<50000?'converge':e<60000?'rupture':'final';if(next!==phase){phase=next;if(phase==='final'){eventName='';waves=[];frags.length=Math.min(frags.length,8);core.x=CX;core.y=CY;coreCarrier=null;burst(CX,CY,'#d269ff',30);banner('👑 CORE FINAL · capture, roube e defenda o Núcleo!');tone(220,.18,.05)}}core.charge=clamp(players.reduce((a,p)=>a+p.energy,0)/1300,0,1)}
function updateHud(t){const p=me()||{energy:0};const elapsed=t-startedAt,rank=score(p)<=0?'—':String(order().findIndex(v=>v.id==='me')+1);$('rank').textContent=rank+'/8';$('energyText').textContent=Math.round(p.energy);$('links').textContent=stats.links;$('coreTime').textContent=stats.coreSeconds.toFixed(1)+'s';$('energyBar').style.width=clamp(p.energy/360*100,0,100)+'%';const ph=phaseLabel();$('phaseKicker').textContent=ph[0];$('phaseTitle').textContent=ph[1];$('timer').textContent=fmt(80000-elapsed);const c=candidate(),ready=c&&linkCooldown<=t&&p.echoUntil<=t&&!linkTarget,activeLink=linkTarget&&linkUntil>t,btn=$('link'),label=$('linkLabel'),hint=$('linkHint');btn.classList.toggle('ready',!!ready);btn.classList.toggle('active',!!activeLink);btn.classList.toggle('cool',linkCooldown>t&&!activeLink);label.textContent=activeLink?'CONECTADO':ready?'LINK · '+c.name:'LINK';if(hint){hint.classList.toggle('show',!!ready);if(ready)hint.textContent='🔗 '+c.name+' está ao alcance'}}
function update(dt,t){const e=t-startedAt;updatePhase(e);events(t,e);if(linkTarget&&linkUntil<=t)linkTarget=null;for(const p of players)stepPlayer(p,dt);if(eventName==='gravity')me().speedUntil=Math.max(me().speedUntil,t+120);if(coreCarrier==null&&phase==='final'){core.x+=core.vx*dt;core.y+=core.vy*dt;const d=Math.hypot(core.x-CX,core.y-CY);if(d>R-55){const nx=(core.x-CX)/d,ny=(core.y-CY)/d,dot=core.vx*nx+core.vy*ny;core.vx-=2*dot*nx;core.vy-=2*dot*ny;core.x=CX+nx*(R-56);core.y=CY+ny*(R-56)}}updateParticles(dt);updateHud(t);if(e>=80000)finish()}
function circle(x,y,r,fill,stroke,w=1){ctx.beginPath();ctx.arc(x,y,r,0,Math.PI*2);if(fill){ctx.fillStyle=fill;ctx.fill()}if(stroke){ctx.lineWidth=w;ctx.strokeStyle=stroke;ctx.stroke()}}
function drawFloor(){const g=ctx.createRadialGradient(CX,CY,30,CX,CY,R);g.addColorStop(0,'#24153f');g.addColorStop(.48,'#10182f');g.addColorStop(1,'#070a14');ctx.fillStyle=g;ctx.fillRect(0,0,W,H);ctx.save();ctx.beginPath();ctx.arc(CX,CY,R,0,6.29);ctx.clip();ctx.strokeStyle='rgba(125,88,195,.16)';ctx.lineWidth=2;for(let r=85;r<R;r+=74){ctx.beginPath();ctx.arc(CX,CY,r,0,6.29);ctx.stroke()}for(let a=0;a<6.29;a+=Math.PI/8){ctx.beginPath();ctx.moveTo(CX,CY);ctx.lineTo(CX+Math.cos(a)*R,CY+Math.sin(a)*R);ctx.stroke()}const coreGlow=ctx.createRadialGradient(CX,CY,8,CX,CY,105);coreGlow.addColorStop(0,`rgba(190,82,255,${.08+core.charge*.28})`);coreGlow.addColorStop(1,'rgba(90,40,150,0)');ctx.fillStyle=coreGlow;ctx.fillRect(CX-115,CY-115,230,230);ctx.restore();circle(CX,CY,R,null,'#714caf',5)}
function drawPads(){for(const p of padDefs){const active=dist(me(),p)<52;ctx.save();ctx.translate(p.x,p.y);ctx.shadowColor=active?'#77efff':'#8a56d6';ctx.shadowBlur=active?22:8;circle(0,0,36,'#10172a',active?'#78efff':'#4f426c',active?3:2);circle(0,0,27,'#121f35','#283b58',1);ctx.fillStyle=active?'#d8fbff':'#9aa4c7';ctx.font='900 22px system-ui';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(p.icon,0,0);ctx.shadowBlur=0;ctx.fillStyle='#727b98';ctx.font='800 7px system-ui';ctx.fillText(p.label,0,48);ctx.restore()}}
function drawFrags(){for(const f of frags){ctx.save();ctx.translate(f.x,f.y);ctx.rotate(f.spin+=.012);ctx.shadowColor=f.color;ctx.shadowBlur=f.kind==='common'?10:18;ctx.fillStyle=f.color;ctx.beginPath();ctx.moveTo(0,-f.r);ctx.lineTo(f.r*.72,0);ctx.lineTo(0,f.r);ctx.lineTo(-f.r*.72,0);ctx.closePath();ctx.fill();if(f.kind!=='common'){ctx.strokeStyle='#fff8';ctx.lineWidth=1;ctx.stroke()}ctx.restore()}}
function drawWaves(){if(eventName!=='shock')return;const t=now();for(const w of waves){if(t<w.born)continue;const rr=(t-w.born)/1000*w.speed;if(rr>R+30)continue;ctx.strokeStyle='rgba(91,226,255,.6)';ctx.lineWidth=10;ctx.beginPath();ctx.arc(CX,CY,rr,0,6.29);ctx.stroke()}}
function drawCore(){if(phase!=='final'){ctx.save();ctx.globalAlpha=.35+core.charge*.45;ctx.shadowColor='#c05cff';ctx.shadowBlur=20+core.charge*28;circle(CX,CY,20+core.charge*9,'#5e2a8f','#d39aff',2);ctx.restore();return}ctx.save();ctx.shadowColor='#cf66ff';ctx.shadowBlur=38;const g=ctx.createRadialGradient(core.x-7,core.y-8,3,core.x,core.y,35);g.addColorStop(0,'#fff');g.addColorStop(.2,'#ffc9ff');g.addColorStop(.55,'#b54cff');g.addColorStop(1,'#3d176e');circle(core.x,core.y,core.r,g,'#ffe1ff',2);ctx.restore()}
function drawGuide(){const t=now(),p=me();if(linkTarget&&linkUntil>t){const b=players.find(v=>v.id===linkTarget);if(!b)return;ctx.save();ctx.strokeStyle='#65eaff';ctx.lineWidth=8;ctx.shadowColor='#65eaff';ctx.shadowBlur=18;ctx.beginPath();ctx.moveTo(p.x,p.y);ctx.lineTo(b.x,b.y);ctx.stroke();ctx.strokeStyle='#e2c7ff';ctx.lineWidth=2;ctx.setLineDash([7,8]);ctx.lineDashOffset=-(t/35)%30;ctx.stroke();ctx.restore();return}const c=candidate();if(!c)return;ctx.save();ctx.setLineDash([7,10]);ctx.lineDashOffset=-(t/40)%34;ctx.strokeStyle='rgba(100,232,255,.6)';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(p.x,p.y);ctx.lineTo(c.x,c.y);ctx.stroke();ctx.restore();ctx.save();ctx.strokeStyle='#76efff';ctx.lineWidth=3;ctx.shadowColor='#65eaff';ctx.shadowBlur=14;circle(c.x,c.y,c.r+8,null,'#76efff',3);ctx.restore()}
function drawAvatar(p){const t=now(),echoing=p.echoUntil>t,c=candidate(),selected=(c?.id===p.id)||linkTarget===p.id||coreCarrier===p.id||p.id==='me';ctx.save();ctx.translate(p.x,p.y);const jumping=p.id==='me'&&jumpUntil>t;if(jumping){ctx.translate(0,-8);ctx.scale(1.1,1.1)}ctx.globalAlpha=echoing?.45:1;ctx.shadowColor=echoing?'#78eaff':p.color;ctx.shadowBlur=selected?22:10;circle(0,5,p.r+3,'#0d1423',selected?'#fff':p.color,selected?3:2);if(p.avatarReady&&p.avatar?.complete&&p.avatar.naturalWidth){ctx.save();ctx.beginPath();ctx.arc(0,4,p.r,0,6.29);ctx.clip();try{ctx.drawImage(p.avatar,-p.r,-p.r-10,p.r*2,p.r*2.55)}catch(_){}ctx.restore()}else{circle(0,4,p.r-2,p.color,null);ctx.fillStyle='#fff';ctx.font='900 16px system-ui';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(p.name.charAt(0).toUpperCase(),0,5)}if(p.shieldUntil>t){ctx.globalAlpha=.75;circle(0,4,p.r+9,null,'#72f3ff',3)}if(coreCarrier===p.id){ctx.font='22px system-ui';ctx.textAlign='center';ctx.fillText('👑',0,-34)}ctx.globalAlpha=1;const showName=p.id==='me'||selected||dist(p,me())<85;if(showName){ctx.fillStyle='#f7f7ff';ctx.font='800 11px system-ui';ctx.textAlign='center';ctx.fillText(p.id==='me'?'VOCÊ':p.name,0,p.r+20)}ctx.restore()}
function drawParticles(){for(const p of particles){ctx.globalAlpha=clamp(p.life/.65,0,1);circle(p.x,p.y,p.size,p.color,null)}ctx.globalAlpha=1}
function draw(){ctx.clearRect(0,0,W,H);drawFloor();ctx.save();ctx.beginPath();ctx.arc(CX,CY,R,0,6.29);ctx.clip();drawPads();drawWaves();drawFrags();drawCore();drawGuide();for(const p of players)drawAvatar(p);drawParticles();ctx.restore()}
function loop(t){if(!active)return;const dt=clamp((t-last)/1000,0,.034);last=t;update(dt,t);draw();if(active)raf=requestAnimationFrame(loop)}
function finish(){if(ended)return;ended=true;active=false;cancelAnimationFrame(raf);const rank=order().findIndex(v=>v.id==='me')+1,pts=score(me());best=Math.max(best,pts);localStorage.setItem('zunoplay_zuno_core_best',String(best));$('overlayTitle').textContent=rank===1?'Core Master!':'Partida concluída';$('overlayText').textContent='Alpha 0.3 testada: avatares, plataformas funcionais, Pulse Link e Core Final.';$('features').style.display='none';const g=$('resultGrid');g.classList.add('show');g.innerHTML='<div class="result"><small>POSIÇÃO</small><b>'+rank+'º/8</b></div><div class="result"><small>PONTOS</small><b>'+pts+'</b></div><div class="result"><small>ENERGIA</small><b>'+Math.round(me().energy)+'</b></div><div class="result"><small>LINKS</small><b>'+stats.links+'</b></div><div class="result"><small>PLATAFORMAS</small><b>'+stats.pads+'</b></div><div class="result"><small>RECORDE</small><b>'+best+'</b></div>';$('start').textContent='Jogar novamente';$('overlay').classList.remove('hide');banner('🏁 '+rank+'º lugar · '+pts+' pontos')}
function setupInput(){const joy=$('joystick'),nub=$('joynub');const end=e=>{if(e.pointerId!==joyPointer)return;joyPointer=null;controls.x=controls.y=0;nub.style.transform='translate(-50%,-50%)'};const move=e=>{if(e.pointerId!==joyPointer)return;const r=joy.getBoundingClientRect(),dx=e.clientX-(r.left+r.width/2),dy=e.clientY-(r.top+r.height/2),lim=r.width*.34,m=Math.hypot(dx,dy)||1,k=Math.min(1,lim/m);controls.x=dx/lim*k;controls.y=dy/lim*k;nub.style.transform='translate(calc(-50% + '+controls.x*34+'px),calc(-50% + '+controls.y*34+'px))'};joy.onpointerdown=e=>{joyPointer=e.pointerId;joy.setPointerCapture?.(e.pointerId);move(e)};joy.onpointermove=move;joy.onpointerup=end;joy.onpointercancel=end;$('jump').onclick=jump;$('link').onclick=activateLink;window.addEventListener('keydown',e=>{controls.keys.add(e.key.toLowerCase());if(e.key===' ')jump();if(e.key.toLowerCase()==='e')activateLink()});window.addEventListener('keyup',e=>controls.keys.delete(e.key.toLowerCase()))}
async function loadProfile(){for(let i=0;i<40;i++){if(window.ZunoSupabaseClient){sb=window.ZunoSupabaseClient;break}await new Promise(r=>setTimeout(r,100))}try{if(sb){const{data:{session}}=await sb.auth.getSession();user=session?.user||null;if(user){const{data}=await sb.from('profiles').select('username,display_name,avatar_config').eq('id',user.id).maybeSingle();userName=data?.display_name||data?.username||user.user_metadata?.username||'Você';avatarConfig=data?.avatar_config||null}}}catch(_){}if(!avatarConfig)try{avatarConfig=JSON.parse(localStorage.getItem('zunoAvatarPreset')||'null')}catch(_){}}
async function imageFromConfig(cfg){for(let i=0;i<60&&!window.ZunoAvatarRenderer;i++)await new Promise(r=>setTimeout(r,100));const r=window.ZunoAvatarRenderer;if(!r)return null;let c=r.normalize?.(cfg)||cfg;if(!c)return null;c=JSON.parse(JSON.stringify(c));c.mode='Sala de voz';c.selections={...(c.selections||{}),Mascote:0,Efeitos:0};c=r.normalize?.(c)||c;try{const raw=await r.officialImage(c.model),src=r.officialComposite(c,raw),img=new Image();return await new Promise(res=>{img.onload=()=>res(img);img.onerror=()=>res(null);img.src=src})}catch(_){return null}}
async function loadArenaAvatars(){const r=window.ZunoAvatarRenderer;if(!r){setTimeout(loadArenaAvatars,500);return}const base=avatarConfig||r.defaults,meImg=await imageFromConfig(base);if(players[0]&&meImg){players[0].avatar=meImg;players[0].avatarReady=true}for(let i=1;i<players.length;i++){const cfg=JSON.parse(JSON.stringify(i%2?r.official?.feminino||r.defaults:r.official?.masculino||r.defaults));cfg.selections={...(cfg.selections||{}),Base:i%4,Acessórios:i%3};const img=await imageFromConfig(cfg);if(players[i]&&img){players[i].avatar=img;players[i].avatarReady=true}}}
function navBack(){if(fromRoom)location.href='sala.html?room='+encodeURIComponent(roomId);else location.href='jogos.html'}
async function init(){document.querySelector('.title span')&&(document.querySelector('.title span').textContent='jogo carro-chefe · Alpha 0.3');if($('room')&&roomId)$('room').classList.add('show');$('back').onclick=navBack;$('exit').onclick=navBack;$('start').onclick=reset;setupInput();await loadProfile();$('overlayText').textContent='Colete energia, use plataformas, conecte-se pelo Pulse Link e dispute o Core Final com seu avatar ZunoPlay.';banner('⚡ Alpha 0.3 pronta · plataformas agora fazem parte da estratégia.')}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>init().catch(console.warn),{once:true});else init().catch(console.warn)
})();