(()=>{
if(window.__ZUNOPLAY_HOME_V2__)return;window.__ZUNOPLAY_HOME_V2__=true;
const page=(location.pathname.split('/').pop()||'index.html').toLowerCase();if(page!=='index.html')return;
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const reduceMotion=()=>window.matchMedia?.('(prefers-reduced-motion: reduce)')?.matches===true;
let revealObserver=null,scrollFxRaf=0,lastScrollY=0,lastScrollAt=performance.now(),worldLoadInFlight=false,worldLoadedAt=0;
function esc(v){const d=document.createElement('div');d.textContent=v==null?'':String(v);return d.innerHTML}
function titleOf(card){return ($('h2',card)?.textContent||'').trim().toLowerCase()}
function cardBy(name){return $$('#homeScreen .menu-card').find(c=>titleOf(c).includes(name))}
function removeRedundantNav(){const grid=$('#homeScreen .menu-grid');if(!grid)return;$$('.menu-card',grid).forEach(card=>{const t=titleOf(card);if(t.includes('salas de voz')||t==='jogos'||t.includes('histórico')||t.includes('conversa')||t.includes('comun'))card.remove()});grid.dataset.homeV2='1'}
function renameFeaturedCard(){const stack=cardBy('zuno stack');if(stack){stack.dataset.homeRole='featured';$('p',stack).textContent='Seu jogo em destaque · Jogar agora'}}
function makeSection(cls,title,sub){const s=document.createElement('section');s.className='zhome-v2-section '+cls;s.innerHTML=`<div class="zhome-v2-kicker">${sub}</div><div class="zhome-v2-title">${title}</div>`;return s}
function mountNow(){const grid=$('#homeScreen .menu-grid');if(!grid||$('#zhomeNow'))return;const s=makeSection('zhome-v2-now','Para você agora','Zuno recomenda');s.id='zhomeNow';s.innerHTML+=`<div class="zhome-v2-rail zhome-v2-recommend-rail"><button class="zhome-v2-mission" type="button" onclick="location.href='jogos.html'"><span class="zhome-v2-mission-copy"><b>Desafio Zuno</b><small>Continue evoluindo sua Aura<br>e desbloqueie novas conquistas.</small></span><span class="zhome-v2-arrow" aria-hidden="true">›</span></button></div>`;grid.parentNode.insertBefore(s,grid)}
function mountWorldRooms(){const grid=$('#homeScreen .menu-grid');if(!grid||$('#zhomeWorld'))return;const section=document.createElement('section');section.className='zhome-v2-section zhome-v2-world';section.id='zhomeWorld';section.innerHTML=`<div class="zhome-world-block"><div class="zhome-world-head"><span>Salas que você entrou</span><small>Recentes</small></div><div id="zhomeVisitedRooms" class="zhome-v2-rail zhome-v2-world-rail"><div class="zhome-world-empty">Suas salas visitadas aparecerão aqui.</div></div></div><div class="zhome-world-block"><div class="zhome-world-head"><span>Populares agora</span><small>Ao vivo</small></div><div id="zhomePopularRooms" class="zhome-v2-rail zhome-v2-world-rail"><div class="zhome-world-empty">Buscando salas populares...</div></div></div>`;grid.parentNode.insertBefore(section,grid)}
function mountPopularGames(){const stack=cardBy('zuno stack');const world=$('#zhomeWorld');if(!stack||!world)return;let section=$('#zhomePopularGames');if(!section){section=makeSection('zhome-v2-popular','Jogos populares','Jogue agora');section.id='zhomePopularGames';const rail=document.createElement('div');rail.className='zhome-v2-rail zhome-v2-games-rail';section.appendChild(rail);world.parentNode.insertBefore(section,world)}const rail=$('.zhome-v2-games-rail',section);if(stack.parentElement!==rail)rail.appendChild(stack);const realItems=[...rail.children].filter(el=>el.matches('.menu-card,.zhome-game-card'));if(realItems.length>1)section.dataset.items=String(realItems.length);else delete section.dataset.items}
function hideEmptyMenuGrid(){const grid=$('#homeScreen .menu-grid');if(!grid)return;const cards=$$('.menu-card',grid);grid.hidden=cards.length===0}
function compactFriends(){const friends=$('#friendsStrip');const section=friends?.closest('.section');if(!section)return;section.classList.add('zhome-v2-friends');const count=Number(($('#onlineCount')?.textContent||'0').replace(/\D/g,''))||0;section.dataset.empty=count<1?'1':'0';const empty=$('.empty-friends',friends)||$('.empty-inline',friends);if(count<1&&empty)empty.textContent='Encontre pessoas para começar seu mundo social.'}
function hideLegacyActiveRooms(){const rooms=$('#activeRooms');const section=rooms?.closest('.section');if(!section)return;section.hidden=true;section.dataset.worldLegacy='1'}
function orderFriendsAfterWorld(){const friends=$('#friendsStrip')?.closest('.section');const world=$('#zhomeWorld');if(friends&&world&&world.nextElementSibling!==friends)world.insertAdjacentElement('afterend',friends)}
async function getClient(){for(let i=0;i<20;i++){const client=window.ZunoSupabaseClient||window.__zunoSupabaseClient;if(client)return client;await new Promise(r=>setTimeout(r,80))}return null}
function roomCount(room){return Number(room?.room_members?.[0]?.count||0)}
function worldRoomCard(room,visited=false){const count=roomCount(room),b=document.createElement('button');b.type='button';b.className='zhome-world-room-card';b.dataset.roomId=String(room.id);b.innerHTML=`<span class="zhome-world-room-live">${count>0?'AO VIVO':'VISITADA'}</span><strong>${esc(room.name||'Sala Zuno')}</strong><span class="zhome-world-room-meta">${visited?'Você já entrou nesta sala':count+' participante'+(count===1?'':'s')+' agora'}</span><span class="zhome-world-room-count">${count>0?'👥 '+count:'↺ Voltar'}</span>`;b.addEventListener('click',()=>enterWorldRoom(room.id));return b}
async function enterWorldRoom(roomId){const client=await getClient();if(!client||!roomId){location.href='salas.html';return}try{const{error}=await client.rpc('join_room_session',{p_room_id:roomId});if(error){const msg=String(error.message||'');if(msg.includes('room_full'))alert('Esta sala está lotada. Os 8 assentos estão ocupados.');else alert('Não foi possível entrar na sala agora.');return}location.href='sala.html?room='+encodeURIComponent(roomId)}catch{alert('Não foi possível entrar na sala agora.') }}
function renderWorldRail(rail,rooms,{visited=false,emptyText='' }={}){if(!rail)return;rail.innerHTML='';if(!rooms.length){const empty=document.createElement('div');empty.className='zhome-world-empty';empty.textContent=emptyText;rail.appendChild(empty);return}rooms.forEach(room=>rail.appendChild(worldRoomCard(room,visited)));enhanceRail(rail);updateRailFocus(rail)}
async function loadWorldRooms(force=false){if(worldLoadInFlight)return;if(!force&&Date.now()-worldLoadedAt<12000)return;const visitedRail=$('#zhomeVisitedRooms'),popularRail=$('#zhomePopularRooms');if(!visitedRail||!popularRail)return;worldLoadInFlight=true;try{const client=await getClient();if(!client)return;const{data:userData}=await client.auth.getUser();const user=userData?.user||null;const popularRes=await client.from('rooms').select('id,name,created_at,room_members(count)').order('created_at',{ascending:false}).limit(40);const popular=(popularRes.data||[]).filter(room=>roomCount(room)>0).sort((a,b)=>roomCount(b)-roomCount(a)||String(b.created_at||'').localeCompare(String(a.created_at||''))).slice(0,10);renderWorldRail(popularRail,popular,{emptyText:'Nenhuma sala popular no momento.'});let visited=[];if(user){const history=window.ZunoRoomHistory?.read?.(user.id)||[];const ids=history.map(item=>item.id).filter(Boolean).slice(0,10);if(ids.length){const recentRes=await client.from('rooms').select('id,name,room_members(count)').in('id',ids);const map=new Map((recentRes.data||[]).map(room=>[String(room.id),room]));visited=ids.map(id=>map.get(String(id))).filter(Boolean)}}renderWorldRail(visitedRail,visited,{visited:true,emptyText:'As salas que você visitar aparecerão aqui.'});worldLoadedAt=Date.now();setupRevealMotion()}catch(error){console.error('Salas da Home:',error);renderWorldRail(popularRail,[],{emptyText:'Não foi possível carregar as salas agora.'})}finally{worldLoadInFlight=false}}
function syncNavReserve(){const nav=$('.zuno-canonical-nav');if(!nav)return;const rect=nav.getBoundingClientRect();const reserve=Math.max(96,Math.ceil(window.innerHeight-rect.top+18));document.documentElement.style.setProperty('--znav-reserved-space',reserve+'px')}
function ensureBottomSafeSpacer(){const home=$('#homeScreen');if(!home)return;let spacer=$('#zhomeBottomSafeSpacer');if(!spacer){spacer=document.createElement('div');spacer.id='zhomeBottomSafeSpacer';spacer.className='zhome-v2-bottom-spacer';spacer.setAttribute('aria-hidden','true');home.appendChild(spacer)}else if(spacer.parentElement!==home){home.appendChild(spacer)}syncNavReserve()}
function railItems(rail){return [...rail.children].filter(el=>!el.classList.contains('zhome-v2-bottom-spacer')&&!el.classList.contains('zhome-world-empty'))}
function updateRailFocus(rail){if(!rail||reduceMotion())return;const rr=rail.getBoundingClientRect(),center=rr.left+rr.width/2,max=Math.max(rr.width*.64,1);railItems(rail).forEach(el=>{const r=el.getBoundingClientRect(),ec=r.left+r.width/2,offset=Math.max(-1,Math.min(1,(ec-center)/max)),focus=Math.max(0,1-Math.abs(offset));el.style.setProperty('--zrail-focus',focus.toFixed(3));el.style.setProperty('--zrail-offset',offset.toFixed(3));el.classList.toggle('zhome-v2-rail-focus',focus>.76)})}
function settleRail(rail){if(!rail||reduceMotion()||rail.dataset.dragging==='1'||rail.dataset.settling==='1'||rail.scrollWidth<=rail.clientWidth+4)return;const items=railItems(rail);if(items.length<2)return;const rr=rail.getBoundingClientRect(),center=rr.left+rr.width/2;let best=null,bestDistance=Infinity;items.forEach(el=>{const r=el.getBoundingClientRect(),d=Math.abs((r.left+r.width/2)-center);if(d<bestDistance){bestDistance=d;best=el}});if(!best)return;const r=best.getBoundingClientRect(),delta=(r.left+r.width/2)-center;if(Math.abs(delta)<2)return;rail.dataset.settling='1';rail.scrollTo({left:rail.scrollLeft+delta,behavior:'smooth'});window.setTimeout(()=>{delete rail.dataset.settling;updateRailFocus(rail)},240)}
function enhanceRail(rail){if(!rail||rail.dataset.motionBound==='1')return;rail.dataset.motionBound='1';let raf=0,settleTimer=0;const update=()=>{if(raf)return;raf=requestAnimationFrame(()=>{raf=0;updateRailFocus(rail)})};const scheduleSettle=()=>{clearTimeout(settleTimer);settleTimer=window.setTimeout(()=>settleRail(rail),110)};rail.addEventListener('scroll',()=>{update();if(rail.dataset.dragging!=='1'&&rail.dataset.settling!=='1')scheduleSettle()},{passive:true});rail.addEventListener('pointerdown',()=>{rail.dataset.dragging='1';clearTimeout(settleTimer)},{passive:true});const release=()=>{delete rail.dataset.dragging;update();scheduleSettle()};rail.addEventListener('pointerup',release,{passive:true});rail.addEventListener('pointercancel',release,{passive:true});rail.addEventListener('touchmove',update,{passive:true});if('onscrollend' in rail)rail.addEventListener('scrollend',()=>{if(rail.dataset.dragging!=='1'&&rail.dataset.settling!=='1')settleRail(rail)},{passive:true});update()}
function setupRevealMotion(){const home=$('#homeScreen');if(!home)return;if(reduceMotion()){home.dataset.homeMotion='reduced';$$('.zhome-v2-reveal',home).forEach(el=>el.classList.add('zhome-v2-inview'));return}home.dataset.homeMotion='1';if(!revealObserver)revealObserver=new IntersectionObserver(entries=>{entries.forEach(entry=>{if(entry.isIntersecting)entry.target.classList.add('zhome-v2-inview');else if(entry.boundingClientRect.top>window.innerHeight*.92)entry.target.classList.remove('zhome-v2-inview')})},{root:null,rootMargin:'0px 0px -8% 0px',threshold:.08});const targets=[$('#zhomeNow'),$('#zhomePopularGames'),$('#zhomeWorld'),$('#friendsStrip')?.closest('.section')].filter(Boolean);targets.forEach(el=>{if(el.dataset.revealBound==='1')return;el.dataset.revealBound='1';el.classList.add('zhome-v2-reveal');revealObserver.observe(el)})}
function getScrollY(){const home=$('#homeScreen'),app=$('#app');return Math.max(window.scrollY||0,document.documentElement.scrollTop||0,document.body?.scrollTop||0,home?.scrollTop||0,app?.scrollTop||0)}
function updateVerticalFx(){scrollFxRaf=0;if(reduceMotion())return;const hero=$('#homeScreen .hero'),avatar=$('#homeScreen .hero-avatar-zone');if(!hero)return;const rect=hero.getBoundingClientRect(),progress=Math.max(0,Math.min(1,-rect.top/Math.max(rect.height,1))),now=performance.now(),y=getScrollY(),dt=Math.max(16,now-lastScrollAt),velocity=Math.min(1,Math.abs(y-lastScrollY)/dt*.9);lastScrollY=y;lastScrollAt=now;document.documentElement.style.setProperty('--zhome-scroll-progress',progress.toFixed(3));document.documentElement.style.setProperty('--zhome-scroll-energy',velocity.toFixed(3));if(avatar)avatar.style.setProperty('--zhome-avatar-shift',(progress*10).toFixed(2)+'px')}
function bindVerticalFx(){const home=$('#homeScreen');if(!home||home.dataset.verticalFxBound==='1')return;home.dataset.verticalFxBound='1';lastScrollY=getScrollY();const onScroll=()=>{if(scrollFxRaf)return;scrollFxRaf=requestAnimationFrame(updateVerticalFx)};window.addEventListener('scroll',onScroll,{passive:true});home.addEventListener('scroll',onScroll,{passive:true});$('#app')?.addEventListener('scroll',onScroll,{passive:true});updateVerticalFx()}
function setupMotion(){const home=$('#homeScreen');if(!home)return;$$('.zhome-v2-rail',home).forEach(enhanceRail);setupRevealMotion();bindVerticalFx()}
function removePermanentGuide(){document.querySelectorAll('#homeScreen .zuno-home-guide').forEach(el=>el.remove())}
function mount(){const home=$('#homeScreen');if(!home)return;home.dataset.homeExperience='v2';removePermanentGuide();removeRedundantNav();renameFeaturedCard();mountNow();mountWorldRooms();mountPopularGames();hideEmptyMenuGrid();hideLegacyActiveRooms();compactFriends();orderFriendsAfterWorld();ensureBottomSafeSpacer();setupMotion();loadWorldRooms()}
let raf=0;const schedule=()=>{if(raf)return;raf=requestAnimationFrame(()=>{raf=0;mount()})};function bindObserver(){const home=$('#homeScreen');if(!home||home.dataset.homeObserverBound==='1')return;home.dataset.homeObserverBound='1';new MutationObserver(mutations=>{const relevant=mutations.some(m=>m.type==='childList'&&([...m.addedNodes,...m.removedNodes].some(n=>n.nodeType===1)));if(relevant)schedule()}).observe(home,{subtree:true,childList:true})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>{mount();bindObserver()},{once:true});else{mount();bindObserver()}['zuno:presence:sync','zuno:presence:join','zuno:presence:leave','zuno:brand-ready','zuno:home-current-ready','zuno:home-resumed'].forEach(e=>window.addEventListener(e,schedule));window.addEventListener('zuno:room-history-updated',()=>loadWorldRooms(true));window.addEventListener('resize',schedule,{passive:true});window.addEventListener('orientationchange',schedule,{passive:true});window.setInterval(()=>{if(document.visibilityState==='visible')loadWorldRooms(true)},30000);
})();