(()=>{
if(window.__ZUNOPLAY_HOME_V2__)return;window.__ZUNOPLAY_HOME_V2__=true;
const page=(location.pathname.split('/').pop()||'index.html').toLowerCase();if(page!=='index.html')return;
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
function titleOf(card){return ($('h2',card)?.textContent||'').trim().toLowerCase()}
function cardBy(name){return $$('.menu-card','#homeScreen'&&document).find(c=>titleOf(c).includes(name))}
function removeRedundantNav(){const grid=$('#homeScreen .menu-grid');if(!grid)return;$$('.menu-card',grid).forEach(card=>{const t=titleOf(card);if(t.includes('salas de voz')||t==='jogos'||t.includes('histórico'))card.remove()});grid.dataset.homeV2='1'}
function renameActivityCards(){const conversations=cardBy('conversa');if(conversations){$('h2',conversations).textContent='Conversas';$('p',conversations).textContent='Veja mensagens e novidades';conversations.dataset.homeRole='activity'}const communities=cardBy('comun');if(communities){$('h2',communities).textContent='Comunidades';$('p',communities).textContent='Descubra o que está movimentando seus grupos';communities.dataset.homeRole='activity'}const stack=cardBy('zuno stack');if(stack){stack.dataset.homeRole='featured';$('p',stack).textContent='Seu jogo em destaque · Jogar agora'}}
function makeSection(cls,title,sub){const s=document.createElement('section');s.className='zhome-v2-section '+cls;s.innerHTML=`<div class="zhome-v2-kicker">${sub}</div><div class="zhome-v2-title">${title}</div>`;return s}
function mountNow(){const grid=$('#homeScreen .menu-grid');if(!grid||$('#zhomeNow'))return;const s=makeSection('zhome-v2-now','Para você agora','Zuno recomenda');s.id='zhomeNow';s.innerHTML+=`<button class="zhome-v2-mission" type="button" onclick="location.href='desafio.html'"><span class="zhome-v2-mission-copy"><b>Desafio Zuno</b><small>Continue evoluindo sua Aura e desbloqueie novas conquistas.</small></span><span class="zhome-v2-arrow">›</span></button>`;grid.parentNode.insertBefore(s,grid)}
function mountWorldLabel(){const grid=$('#homeScreen .menu-grid');if(!grid||$('#zhomeWorldLabel'))return;const h=document.createElement('div');h.id='zhomeWorldLabel';h.className='zhome-v2-world-label';h.innerHTML='<span>Seu mundo</span><small>Atividade, descoberta e experiências</small>';grid.parentNode.insertBefore(h,grid)}
function compactFriends(){const friends=$('#friendsStrip');const section=friends?.closest('.section');if(!section)return;section.classList.add('zhome-v2-friends');const count=Number(($('#onlineCount')?.textContent||'0').replace(/\D/g,''))||0;section.dataset.empty=count<1?'1':'0';const empty=$('.empty-inline',friends);if(count<1&&empty){empty.textContent='Encontre pessoas para começar seu mundo social.'}}
function activeRoomsAsLiveContent(){const rooms=$('#activeRooms');const section=rooms?.closest('.section');if(!section)return;section.classList.add('zhome-v2-live');const title=$('.section-title',section);if(title)title.innerHTML='<span class="dot-online"></span> Acontecendo agora';const link=$('.section-link',section);if(link)link.textContent='Explorar';const empty=$('.empty-inline',rooms);if(empty&&/carregando|nenhuma|não há/i.test(empty.textContent||''))empty.textContent='Quando houver uma sala ou atividade ao vivo, ela aparece aqui.'}
function removePermanentGuide(){document.querySelectorAll('#homeScreen .zuno-home-guide').forEach(el=>el.remove())}
function mount(){const home=$('#homeScreen');if(!home)return;home.dataset.homeExperience='v2';removePermanentGuide();removeRedundantNav();renameActivityCards();mountNow();mountWorldLabel();compactFriends();activeRoomsAsLiveContent()}
let raf=0;const schedule=()=>{if(raf)return;raf=requestAnimationFrame(()=>{raf=0;mount()})};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',mount,{once:true});else mount();new MutationObserver(schedule).observe(document.documentElement,{subtree:true,childList:true,characterData:true});['zuno:presence:sync','zuno:presence:join','zuno:presence:leave','zuno:brand-ready','zuno:home-current-ready'].forEach(e=>window.addEventListener(e,schedule));
})();