(()=>{
if(window.__ZUNO_STACK__)return;window.__ZUNO_STACK__=true;
const $=id=>document.getElementById(id),sleep=ms=>new Promise(r=>setTimeout(r,ms)),q=new URLSearchParams(location.search),roomId=q.get('room')||sessionStorage.getItem('zunoplay_room_id')||'',fromRoom=q.get('from')==='sala'&&!!roomId;
const TRAY_LIMIT=7,RISK_AT=6,FAMILIES_PER_MATCH=10,PIECES_PER_FAMILY=9,TOTAL_TILES=90,LAYER_COUNTS=[36,24,15,10,5],TARGET_MIN_MS=240000,TARGET_MAX_MS=360000,BOT_TICK_MS=4800,COMBO_WINDOW_MS=12000;
const FALLBACK=[{id:'bolt',label:'Bolt',a:'#ffd85d',b:'#9a5605',border:'#ffe990',icon:'ϟ'},{id:'gem',label:'Core',a:'#20dcff',b:'#0752a8',border:'#8cf4ff',icon:'◆'},{id:'star',label:'Nova',a:'#ff66b2',b:'#8d194d',border:'#ffabd1',icon:'✦'},{id:'moon',label:'Prism',a:'#b65cff',b:'#4b1a89',border:'#dfa6ff',icon:'△'},{id:'orb',label:'Orb',a:'#24e8f2',b:'#08728c',border:'#8ef9ff',icon:'◉'},{id:'leaf',label:'Echo',a:'#62e77c',b:'#116b37',border:'#9af6ac',icon:'◈'}];
const LIB=Array.isArray(window.__ZUNO_STACK_LIBRARY__)?window.__ZUNO_STACK_LIBRARY__:[],TYPES=LIB.length>=FAMILIES_PER_MATCH?LIB:FALLBACK,typeById=Object.fromEntries(TYPES.map(x=>[x.id,x]));
let sb=null,user=null,playerName='Você',tiles=[],tray=[],relay=[null,null,null],team=[],matchTypes=[],score=0,matches=0,energy=0,active=false,lastMove=null,undoLeft=1,hintsLeft=2,botTimer=0,pulseEventCount=0,doubleNext=false,startedAt=0,riskAnnounced=false,currentSeed=0,combo=0,bestCombo=0,lastMatchAt=0;
let gameChannel=null,presenceChannel=null,coopReady=false,coopPeers=new Map(),relayRev=0,presenceTimer=0;
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function seeded(seed){let a=seed>>>0;return()=>{a|=0;a=a+0x6D2B79F5|0;let t=Math.imul(a^a>>>15,1|a);t=t+Math.imul(t^t>>>7,61|t)^t;return((t^t>>>14)>>>0)/4294967296}}
function shuffleWith(a,rng){const x=[...a];for(let i=x.length-1;i>0;i--){const j=Math.floor(rng()*(i+1));[x[i],x[j]]=[x[j],x[i]]}return x}
function freshSeed(){try{const a=new Uint32Array(1);crypto.getRandomValues(a);return a[0]||Date.now()>>>0}catch(_){return(Date.now()^Math.floor(Math.random()*0xffffffff))>>>0}}
function elapsed(){return startedAt?Date.now()-startedAt:0}
function announce(t){$('live').textContent=t}function toast(t){const e=$('toast');e.textContent=t;e.classList.add('show');clearTimeout(e._t);e._t=setTimeout(()=>e.classList.remove('show'),1800)}
function clearTimers(){if(botTimer){clearInterval(botTimer);botTimer=0}if(presenceTimer){clearInterval(presenceTimer);presenceTimer=0}}
function authCommit(kind){try{window.ZunoStackAuthority?.commit?.(kind,fullState())}catch(_){}}
function art(m){return `<span class="zsp-art" style="--piece-a:${m.a||'#8b4dff'};--piece-b:${m.b||'#3b176f'};--piece-border:${m.border||'#d3a2ff'};--piece-icon:${JSON.stringify(m.icon||'✦')}" aria-hidden="true"></span>`}
function injectStyles(){if($('zunoStackStage4Styles'))return;const s=document.createElement('style');s.id='zunoStackStage4Styles';s.textContent=`.tray{grid-template-columns:repeat(${TRAY_LIMIT},1fr)!important}.tray.tray-risk{animation:zRisk .85s ease-in-out infinite alternate;filter:drop-shadow(0 0 9px rgba(255,86,112,.42))}.tray.tray-risk .slot{border-color:rgba(255,96,121,.62);background:#2b1019}.tray.tray-critical{filter:drop-shadow(0 0 13px rgba(255,64,94,.65))}.tray-risk-copy{color:#ff7182!important;font-weight:950!important}@keyframes zRisk{to{transform:scale(1.008)}}@media(prefers-reduced-motion:reduce){.tray.tray-risk{animation:none}}`;document.head.appendChild(s)}
function syncCopy(){const h=document.querySelector('.tray-area .area-head b');if(h)h.textContent=`Bandeja · máximo ${TRAY_LIMIT}`;const help=document.querySelector('.help');if(help)help.textContent=roomId?`Forme 3 iguais. Em sala, o Relay e a vitória são compartilhados em tempo real entre até 3 jogadores. RISCO em ${RISK_AT}/${TRAY_LIMIT}.`:`Forme 3 iguais. Cada partida tem 90 peças em 5 camadas, tabuleiro variável e ritmo de aproximadamente 4–6 minutos. RISCO em ${RISK_AT}/${TRAY_LIMIT}.`;const f=$('features')?.querySelectorAll('.feature');if(f?.[0])f[0].textContent='🧩 90 peças · 5 camadas';if(f?.[1])f[1].textContent=roomId?'🤝 coop real · até 3 jogadores':'⏱ alvo de 4–6 minutos';if($('tilesLeft'))$('tilesLeft').textContent=TOTAL_TILES}
function makePositions(rng){const cells=[];for(let y=0;y<6;y++)for(let x=0;x<6;x++)cells.push({x,y});let pool=shuffleWith(cells,rng),positions=[];for(let layer=0;layer<LAYER_COUNTS.length;layer++){const count=LAYER_COUNTS[layer],chosen=layer===0?pool:shuffleWith(pool,rng).slice(0,count);chosen.forEach(c=>positions.push({x:c.x,y:c.y,layer}));pool=chosen}return positions}
function topVisibleTypes(candidate){const visible=[];for(const t of candidate)if(!candidate.some(o=>o.x===t.x&&o.y===t.y&&o.layer>t.layer))visible.push(t.type);return visible}
function fairOpening(candidate){const c={};for(const t of topVisibleTypes(candidate))c[t]=(c[t]||0)+1;const n=Object.values(c);return n.some(x=>x>=3)&&n.filter(x=>x>=2).length>=3}
function buildTiles(seedOverride=null){currentSeed=Number.isFinite(Number(seedOverride))?Number(seedOverride)>>>0:freshSeed();let candidate=[];for(let attempt=0;attempt<12;attempt++){const rng=seeded((currentSeed+attempt*2654435761)>>>0);matchTypes=shuffleWith(TYPES,rng).slice(0,FAMILIES_PER_MATCH);const ids=shuffleWith(matchTypes.flatMap(t=>Array(PIECES_PER_FAMILY).fill(t.id)),rng),positions=makePositions(rng);candidate=positions.map((v,i)=>({id:'t'+i,type:ids[i],...v,removed:false}));if(candidate.length===TOTAL_TILES&&fairOpening(candidate)){currentSeed=(currentSeed+attempt*2654435761)>>>0;break}}tiles=candidate;localStorage.setItem('zunoplay_zuno_stack_last_seed',String(currentSeed))}
function isActiveTile(t){return !t.removed&&!tiles.some(o=>!o.removed&&o.x===t.x&&o.y===t.y&&o.layer>t.layer)}
function mountBoard(){const b=$('board');b.innerHTML=tiles.map(t=>{const m=typeById[t.type]||FALLBACK[0];return `<button class="tile" data-tile="${t.id}" style="--x:${t.x};--y:${t.y};--layer:${t.layer}" aria-label="${m.label}"><span class="piece-shell">${art(m)}<span class="label">${m.label}</span></span></button>`}).join('');b.querySelectorAll('[data-tile]').forEach(x=>x.onclick=()=>pickTile(x.dataset.tile));b.dataset.zunoMounted='1'}
function syncBoard(){const b=$('board');if(b.dataset.zunoMounted!=='1'||b.children.length!==tiles.length)mountBoard();for(const t of tiles){const e=b.querySelector(`[data-tile="${t.id}"]`);if(!e)continue;const ok=isActiveTile(t);e.classList.toggle('active',ok);e.classList.toggle('removed',t.removed);e.disabled=t.removed||!ok}}
function renderTray(){const b=$('tray'),risk=tray.length>=RISK_AT,critical=tray.length>=TRAY_LIMIT;b.classList.toggle('tray-risk',risk&&!critical);b.classList.toggle('tray-critical',critical);const h=document.querySelector('.tray-area .area-head b');if(h){h.textContent=risk?`⚠ RISCO · ${tray.length}/${TRAY_LIMIT}`:`Bandeja · máximo ${TRAY_LIMIT}`;h.classList.toggle('tray-risk-copy',risk)}b.innerHTML=Array.from({length:TRAY_LIMIT},(_,i)=>{const t=tray[i];if(!t)return `<div class="slot ${risk?'danger':''}"></div>`;const m=typeById[t]||FALLBACK[0];return `<div class="slot filled ${risk?'danger':''}"><button data-tray="${i}"><span class="piece-shell">${art(m)}<span class="tiny">${m.label}</span></span></button></div>`}).join('');b.querySelectorAll('[data-tray]').forEach(x=>x.onclick=()=>sendToRelay(+x.dataset.tray));if(risk&&!riskAnnounced){riskAnnounced=true;toast(`⚠ RISCO: ${RISK_AT}/${TRAY_LIMIT} espaços ocupados.`);announce('Bandeja em risco.')}else if(!risk)riskAnnounced=false}
function renderRelay(){const b=$('relaySlots');b.innerHTML=relay.map((t,i)=>{if(!t)return `<button class="relay-slot" data-relay="${i}" disabled>VAZIO</button>`;const m=typeById[t]||FALLBACK[0];return `<button class="relay-slot filled" data-relay="${i}"><span class="zsp-relay-piece">${art(m)}<small>${m.label}</small></span></button>`}).join('');b.querySelectorAll('[data-relay]').forEach(x=>x.onclick=()=>takeRelay(+x.dataset.relay))}
function renderTeam(){const b=$('team');b.innerHTML=team.map((p,i)=>`<div class="mate ${i===0?'me':''}"><div class="mate-head"><div class="mate-icon">${i===0?'⚡':'🤝'}</div><div class="mate-copy"><b>${esc(p.name)}</b><small>${i===0?'seu tabuleiro':p.status}</small></div></div><div class="mini-bar"><i style="width:${clamp(p.progress,0,100)}%"></i></div></div>`).join('')}
function tilesLeft(){return tiles.reduce((n,t)=>n+!t.removed,0)}
function phase(){const p=(TOTAL_TILES-tilesLeft())/TOTAL_TILES;if(p<.3)return'ABERTURA';if(p<.75)return'PRESSÃO';return'FINAL'}
function riskLevel(){return tray.length>=RISK_AT?'ALTO':tray.length>=3?'MÉDIO':'BAIXO'}
function localProgress(){return Math.round((TOTAL_TILES-tilesLeft())/TOTAL_TILES*100)}
function rebuildTeam(){const me={name:playerName,progress:active?localProgress():0,status:active?'jogando':'pronto'},peers=[...coopPeers.values()].sort((a,b)=>(a.joinedAt||0)-(b.joinedAt||0)).slice(0,2);team=[me,...peers];renderTeam()}
function renderHud(){const left=tilesLeft();$('score').textContent=Math.round(score);$('matches').textContent=matches;$('tilesLeft').textContent=left;$('energyText').textContent=energy+'/5';$('energy').style.width=energy*20+'%';$('pulse').disabled=energy<5||!active;$('undo').disabled=!active||undoLeft<=0||!lastMove;$('undo').textContent='↩ DESFAZER · '+undoLeft;$('hint').disabled=!active||hintsLeft<=0;$('hint').textContent='✦ DICA · '+hintsLeft;$('missionMeter').textContent=active?`${riskLevel()} · x${Math.max(1,combo)}`:energy+'/5';if(active&&$('missionText'))$('missionText').textContent=`${phase()} · risco ${riskLevel()} · combo x${Math.max(1,combo)} · ${Math.floor(elapsed()/60000)}:${String(Math.floor(elapsed()/1000)%60).padStart(2,'0')}`;if(team[0])team[0].progress=localProgress();renderTeam()}
function renderAll(){syncBoard();renderTray();renderRelay();renderHud()}
function trayHasMatch(){const c={};for(const t of tray){c[t]=(c[t]||0)+1;if(c[t]>=3)return true}return false}
function snapshot(){return{tray:[...tray],relay:[...relay],score,matches,energy,pulseEventCount,doubleNext,combo,bestCombo,lastMatchAt}}
function restore(s){tray=[...(s.tray||[])];relay=[...(s.relay||[null,null,null])];score=Number(s.score)||0;matches=Number(s.matches)||0;energy=clamp(Number(s.energy)||0,0,5);pulseEventCount=Number(s.pulseEventCount)||0;doubleNext=!!s.doubleNext;combo=Number(s.combo)||0;bestCombo=Number(s.bestCombo)||0;lastMatchAt=Number(s.lastMatchAt)||0}
function fullState(){return{version:2,active,seed:currentSeed,startedAt,tiles:tiles.map(t=>({id:t.id,type:t.type,x:t.x,y:t.y,layer:t.layer,removed:!!t.removed})),tray:[...tray],relay:[...relay],score,matches,energy,pulseEventCount,doubleNext,combo,bestCombo,lastMatchAt,undoLeft,hintsLeft,relayRev}}
function applyFullState(s){if(!s||!Array.isArray(s.tiles))return false;clearTimers();currentSeed=Number(s.seed)||0;startedAt=Number(s.startedAt)||Date.now();tiles=s.tiles.map(t=>({id:String(t.id),type:String(t.type),x:Number(t.x)||0,y:Number(t.y)||0,layer:Number(t.layer)||0,removed:!!t.removed}));matchTypes=[...new Set(tiles.map(t=>t.type))].map(id=>typeById[id]).filter(Boolean);tray=Array.isArray(s.tray)?s.tray.slice(0,TRAY_LIMIT):[];relay=Array.isArray(s.relay)?s.relay.slice(0,3):[null,null,null];while(relay.length<3)relay.push(null);score=Number(s.score)||0;matches=Number(s.matches)||0;energy=clamp(Number(s.energy)||0,0,5);pulseEventCount=Number(s.pulseEventCount)||0;doubleNext=!!s.doubleNext;combo=Number(s.combo)||0;bestCombo=Number(s.bestCombo)||0;lastMatchAt=Number(s.lastMatchAt)||0;undoLeft=Number.isFinite(Number(s.undoLeft))?Number(s.undoLeft):1;hintsLeft=Number.isFinite(Number(s.hintsLeft))?Number(s.hintsLeft):2;relayRev=Number(s.relayRev)||relayRev;lastMove=null;active=!!s.active;riskAnnounced=false;const b=$('board');if(b){b.dataset.zunoMounted='0';b.replaceChildren()}if(active){$('overlay')?.classList.add('hide');if($('resultGrid'))$('resultGrid').hidden=true;if($('features'))$('features').style.display='grid'}renderAll();if(!roomId&&active)botTimer=setInterval(botStep,BOT_TICK_MS);return true}
function checkMatch(type){const a=[];tray.forEach((t,i)=>t===type&&a.push(i));if(a.length<3)return false;for(let i=a.length-1;i>=a.length-3;i--)tray.splice(a[i],1);const now=Date.now();combo=lastMatchAt&&now-lastMatchAt<=COMBO_WINDOW_MS?combo+1:1;lastMatchAt=now;bestCombo=Math.max(bestCombo,combo);matches++;const base=doubleNext?620:310,double=doubleNext;doubleNext=false;const comboBonus=(combo-1)*55,g=base+comboBonus;score+=g;energy=clamp(energy+1,0,5);toast(`Trio ${typeById[type]?.label||type}! +${g}${combo>1?' · combo x'+combo:''}${double?' · DOBRO':''}`);if(matches%5===0)triggerPulseEvent();return true}
function pickTile(id){if(!active)return;const t=tiles.find(x=>x.id===id);if(!t||!isActiveTile(t))return;if(tray.length>=TRAY_LIMIT)return lose('Bandeja cheia.');const before=snapshot();t.removed=true;tray.push(t.type);lastMove={tileId:t.id,type:t.type,before};score+=25;checkMatch(t.type);renderAll();publishState();authCommit('tile');if(!tilesLeft())return win('Você limpou as 90 peças!');if(tray.length>=TRAY_LIMIT&&!trayHasMatch())lose(`A bandeja chegou a ${TRAY_LIMIT} peças sem um trio.`)}
function firstRelayEmpty(){return relay.findIndex(x=>!x)}
function broadcastRelay(){if(!coopReady||!gameChannel)return;relayRev=Date.now();gameChannel.send({type:'broadcast',event:'stack_relay',payload:{relay:[...relay],rev:relayRev,actor:user?.id||''}}).catch(()=>{})}
function sendToRelay(i){if(!active||i<0||i>=tray.length)return;const s=firstRelayEmpty();if(s<0)return toast('O Relay está cheio.');relay[s]=tray.splice(i,1)[0];score+=20;lastMove=null;renderAll();broadcastRelay();publishState();authCommit('relay_send')}
function takeRelay(i){if(!active||!relay[i])return;if(tray.length>=TRAY_LIMIT)return toast('Libere espaço primeiro.');const t=relay[i];relay[i]=null;tray.push(t);checkMatch(t);score+=10;lastMove=null;renderAll();broadcastRelay();publishState();authCommit('relay_take');if(tray.length>=TRAY_LIMIT&&!trayHasMatch())lose('A bandeja ficou cheia.')}
function undo(){if(!active||undoLeft<=0||!lastMove)return;const t=tiles.find(x=>x.id===lastMove.tileId);if(!t)return;restore(lastMove.before);t.removed=false;undoLeft--;lastMove=null;toast('Jogada restaurada por completo.');renderAll();broadcastRelay();publishState();authCommit('undo')}
function hint(){if(!active||hintsLeft<=0)return;const c={};tray.forEach(t=>c[t]=(c[t]||0)+1);const activeTiles=tiles.filter(isActiveTile);const scoreMove=t=>{const n=c[t.type]||0;let s=n===2?100:n===1?50:0;if(tray.length>=TRAY_LIMIT-2&&n===0)s-=40;const opens=tiles.filter(o=>!o.removed&&o.x===t.x&&o.y===t.y&&o.layer<t.layer).length;s+=opens*4;return s};const t=activeTiles.sort((a,b)=>scoreMove(b)-scoreMove(a))[0];if(!t)return;hintsLeft--;renderHud();document.querySelector(`[data-tile="${t.id}"]`)?.animate([{outline:'0 solid #ffd16600'},{outline:'3px solid #ffd166'},{outline:'0 solid #ffd16600'}],{duration:700});const n=c[t.type]||0;toast(n===2?'Dica: esta peça fecha um trio.':n===1?'Dica: esta peça fortalece seu par.':'Dica: melhor abertura disponível.');authCommit('hint')}
function pulseShift(){if(!active||energy<5)return;const critical=tray.length>=RISK_AT,c={};tray.forEach(t=>c[t]=(c[t]||0)+1);const removeCount=critical?3:2;tray.map((t,i)=>({i,c:c[t]})).sort((a,b)=>a.c-b.c||b.i-a.i).slice(0,removeCount).sort((a,b)=>b.i-a.i).forEach(x=>tray.splice(x.i,1));energy=0;score+=critical?260:160;combo=0;lastMatchAt=0;lastMove=null;toast(critical?'Pulse Shift crítico: 3 riscos removidos!':'Pulse Shift: 2 riscos removidos!');renderAll();broadcastRelay();publishState();authCommit('pulse_shift');if(coopReady)sendGame('stack_pulse',{by:playerName,critical})}
function triggerPulseEvent(){pulseEventCount++;if(pulseEventCount%3===1){doubleNext=true;toast('⚡ Próximo trio vale o dobro!')}else if(pulseEventCount%3===2){const s=firstRelayEmpty(),t=Object.entries(tray.reduce((c,x)=>(c[x]=(c[x]||0)+1,c),{})).sort((a,b)=>b[1]-a[1])[0]?.[0]||matchTypes[0]?.id;if(s>=0&&t){relay[s]=t;broadcastRelay()}toast('✦ Peça útil enviada ao Relay.')}else{toast(coopReady?'🤝 Impulso de equipe enviado!':'🤝 Impulso de equipe!');if(coopReady)sendGame('stack_boost',{by:playerName});else team.slice(1).forEach(p=>p.progress=clamp(p.progress+5,0,100))}renderAll()}
function botStep(){if(!active||document.hidden||roomId)return;const ms=elapsed(),late=ms>TARGET_MAX_MS;team.slice(1).forEach(p=>{const inc=late?2:1+(Math.random()>.7?1:0);p.progress=clamp(p.progress+inc,0,ms<TARGET_MIN_MS?96:100);p.status=ms<TARGET_MIN_MS?'organizando com calma':late?'acelerando o final':Math.random()>.5?'formando trio':'organizando peças'});renderTeam();if(ms>=TARGET_MIN_MS&&team.slice(1).some(p=>p.progress>=100))win('Um parceiro limpou o tabuleiro. Vitória da equipe!')}
function rememberDuration(won){const seconds=Math.max(1,Math.round(elapsed()/1000)),key='zunoplay_zuno_stack_duration_samples';let a=[];try{a=JSON.parse(localStorage.getItem(key)||'[]')}catch(_){}a=Array.isArray(a)?a.slice(-9):[];a.push({seconds,won,seed:currentSeed,bestCombo,coop:coopReady,at:Date.now()});localStorage.setItem(key,JSON.stringify(a));return seconds}
async function startGame(){if(roomId&&window.ZunoStackAuthority?.prepareStart){try{if(await window.ZunoStackAuthority.prepareStart())return}catch(_){}}clearTimers();buildTiles();tray=[];relay=[null,null,null];relayRev=0;score=matches=energy=pulseEventCount=combo=bestCombo=lastMatchAt=0;lastMove=null;undoLeft=1;hintsLeft=2;doubleNext=riskAnnounced=false;startedAt=Date.now();active=true;team=roomId?[{name:playerName,progress:0,status:'jogando'}]:[{name:playerName,progress:0,status:'jogando'},{name:'Nova',progress:0,status:'organizando peças'},{name:'Kiro',progress:0,status:'organizando peças'}];if(coopReady)rebuildTeam();const b=$('board');b.dataset.zunoMounted='0';b.replaceChildren();$('overlay').classList.add('hide');$('resultGrid').hidden=true;$('features').style.display='grid';$('saving').textContent='';renderAll();if(!roomId)botTimer=setInterval(botStep,BOT_TICK_MS);if(coopReady){publishState(true);broadcastRelay()}authCommit('start');announce(`Zuno Stack iniciado. Tabuleiro ${currentSeed}.${coopReady?' Cooperação em tempo real ativa.':' Ritmo calibrado para 4 a 6 minutos.'}`)}
function finish(won,reason,broadcast=true){if(!active)return;active=false;if(botTimer){clearInterval(botTimer);botTimer=0}const left=tilesLeft(),cleared=TOTAL_TILES-left,seconds=rememberDuration(won),best=Number(localStorage.getItem('zunoplay_zuno_stack_best')||0);if(score>best)localStorage.setItem('zunoplay_zuno_stack_best',String(Math.round(score)));$('overlayIcon').textContent=won?'🏆🧩':'🌀🧩';$('overlayTitle').textContent=won?'Stack concluído!':'Stack encerrado';const pace=seconds<240?'rápida':seconds<=360?'ritmo ideal':'longa';$('overlayText').textContent=`${reason} · ${pace} · Tabuleiro ${currentSeed}`;$('features').style.display='none';const g=$('resultGrid');g.hidden=false;g.innerHTML=`<div class="result"><small>RESULTADO</small><b>${won?'VITÓRIA':'FIM'}</b></div><div class="result"><small>PONTOS</small><b>${Math.round(score)}</b></div><div class="result"><small>TRIOS</small><b>${matches}</b></div><div class="result"><small>COMBO</small><b>x${Math.max(1,bestCombo)}</b></div><div class="result"><small>PEÇAS</small><b>${cleared}/${TOTAL_TILES}</b></div><div class="result"><small>TEMPO</small><b>${Math.floor(seconds/60)}:${String(seconds%60).padStart(2,'0')}</b></div>`;$('start').textContent='Jogar novamente';$('start').onclick=startGame;$('overlay').classList.remove('hide');authCommit(won?'win':'finish');if(won&&broadcast&&coopReady)sendGame('stack_win',{by:playerName,userId:user?.id||''});saveResult(won,cleared).catch(console.warn)}
function win(r,broadcast=true){finish(true,r,broadcast)}function lose(r){finish(false,r+` Use o Relay e os poderes para controlar os ${TRAY_LIMIT} espaços.`)}
async function waitClient(){for(let i=0;i<50;i++){if(window.ZunoSupabaseClient)return window.ZunoSupabaseClient;await sleep(100)}return null}
async function saveResult(won,cleared){const b=$('saving');if(!sb||!user){b.textContent='Resultado local salvo.';return}b.textContent='Salvando resultado...';const {data,error}=await sb.rpc('submit_zuno_stack_result',{p_score:Math.round(score),p_matches:matches,p_tiles_cleared:cleared,p_won:won});if(error){b.textContent='Resultado local salvo; XP não pôde ser registrado.';return}const r=data?.[0];b.textContent=r?.recorded?'✓ Resultado registrado · Nível de Jogos '+(r.game_level||1):'Resultado concluído.'}
function sendGame(event,payload){if(!coopReady||!gameChannel)return Promise.resolve();return gameChannel.send({type:'broadcast',event,payload:{...payload,from:user?.id||'',at:Date.now()}}).catch(()=>{})}
function publishState(force=false){if(!coopReady||!active)return;const payload={name:playerName,progress:localProgress(),status:phase().toLowerCase(),score:Math.round(score),matches,seed:currentSeed};sendGame('stack_state',payload);if(force&&presenceChannel)presenceChannel.track({userId:user.id,name:playerName,game:'zuno-stack',progress:payload.progress,joinedAt:Date.now()}).catch(()=>{})}
function handlePresence(){if(!presenceChannel||!user)return;const state=presenceChannel.presenceState(),next=new Map();for(const list of Object.values(state))for(const p of list||[]){if(p?.game!=='zuno-stack'||!p.userId||p.userId===user.id)continue;next.set(p.userId,{name:p.name||'Jogador',progress:Number(p.progress)||0,status:'conectado',joinedAt:p.joinedAt||0})}coopPeers=next;rebuildTeam()}
async function initCoop(){if(!sb||!user||!roomId)return;const gameTopic=`room:${roomId}:games`,presenceTopic=`zunoplay-presence-${roomId}`;try{await sb.realtime.setAuth?.()}catch(_){}
gameChannel=sb.channel(gameTopic,{config:{private:true,broadcast:{self:false}}})
.on('broadcast',{event:'stack_state'},({payload})=>{if(!payload?.from||payload.from===user.id)return;const cur=coopPeers.get(payload.from)||{name:payload.name||'Jogador',joinedAt:payload.at||Date.now()};coopPeers.set(payload.from,{...cur,name:payload.name||cur.name,progress:clamp(Number(payload.progress)||0,0,100),status:payload.status||'jogando'});rebuildTeam()})
.on('broadcast',{event:'stack_relay'},({payload})=>{if(!active||!payload||payload.actor===user.id||!Array.isArray(payload.relay))return;const rev=Number(payload.rev)||0;if(rev<=relayRev)return;relayRev=rev;relay=payload.relay.slice(0,3);while(relay.length<3)relay.push(null);renderRelay();toast('🤝 Relay atualizado por um parceiro.')})
.on('broadcast',{event:'stack_win'},({payload})=>{if(active&&payload?.from!==user.id)win(`${payload?.by||'Um parceiro'} limpou o tabuleiro. Vitória da equipe!`,false)})
.on('broadcast',{event:'stack_pulse'},({payload})=>{if(payload?.from!==user.id)toast(`⚡ ${payload?.by||'Parceiro'} ativou Pulse Shift.`)})
.on('broadcast',{event:'stack_boost'},({payload})=>{if(payload?.from!==user.id){score+=60;toast(`🤝 Impulso de ${payload?.by||'parceiro'}: +60.`);renderHud();authCommit('team_boost')}})
.subscribe(status=>{if(status==='SUBSCRIBED'){coopReady=true;$('room').textContent='● Coop conectado';if(active)publishState(true)}else if(status==='CHANNEL_ERROR'||status==='TIMED_OUT'){$('room').textContent='● Coop reconectando'}});
presenceChannel=sb.channel(presenceTopic,{config:{private:true,presence:{key:user.id}}})
.on('presence',{event:'sync'},handlePresence).on('presence',{event:'join'},handlePresence).on('presence',{event:'leave'},handlePresence)
.subscribe(async status=>{if(status==='SUBSCRIBED'){await presenceChannel.track({userId:user.id,name:playerName,game:'zuno-stack',progress:active?localProgress():0,joinedAt:Date.now()});handlePresence();if(!presenceTimer)presenceTimer=setInterval(()=>{if(presenceChannel&&user)presenceChannel.track({userId:user.id,name:playerName,game:'zuno-stack',progress:active?localProgress():0,joinedAt:Date.now()}).catch(()=>{})},20000)}})}
async function closeCoop(){try{if(presenceChannel)await presenceChannel.untrack()}catch(_){}try{if(gameChannel)await sb.removeChannel(gameChannel)}catch(_){}try{if(presenceChannel)await sb.removeChannel(presenceChannel)}catch(_){}gameChannel=presenceChannel=null;coopReady=false}
window.ZunoStackCore={version:2,getState:fullState,applyState:applyFullState,startWithSeed:seed=>{buildTiles(seed);active=true;startedAt=Date.now();renderAll();return fullState()},isActive:()=>active,getRoomId:()=>roomId};
document.dispatchEvent(new CustomEvent('zuno:stack-core-ready'));
injectStyles();syncCopy();$('undo').onclick=undo;$('hint').onclick=hint;$('pulse').onclick=pulseShift;$('start').onclick=startGame;$('back').onclick=()=>location.href=fromRoom?'sala.html?room='+encodeURIComponent(roomId):'jogos.html';$('exit').onclick=$('back').onclick;if(roomId)$('room').textContent='● Conectando coop';
(async()=>{sb=await waitClient();if(sb){const {data}=await sb.auth.getSession();user=data?.session?.user||null;if(user){const {data:p}=await sb.from('profiles').select('username').eq('id',user.id).maybeSingle();playerName=p?.username||user.email?.split('@')[0]||'Você'}}team=roomId?[{name:playerName,progress:0,status:'pronto'}]:[{name:playerName,progress:0,status:'pronto'},{name:'Nova',progress:0,status:'pronto'},{name:'Kiro',progress:0,status:'pronto'}];renderTeam();renderTray();renderRelay();renderHud();if(roomId&&user)await initCoop()})().catch(console.warn);
document.addEventListener('visibilitychange',()=>{if(!document.hidden&&active){renderHud();publishState()}});window.addEventListener('pagehide',()=>{clearTimers();closeCoop()},{once:true});
})();