import {PICK_TILE,USE_POWER,createCommand,createDomainEvent,createGameState,createPlayerState,dispatch,generateBoard,getAvailableTileIds} from '../core/index.mjs';
import {DEFAULT_SOLO_BOARD,DEFAULT_SOLO_RESOURCES,SOLO_MODE,SOLO_POWER,SOLO_RULESET_VERSION,SOLO_STATUS,chooseSoloHint,createSoloBoard,createSoloRulesContext,evaluateSoloStatus,rescueSoloPlayer} from './solo-rules.mjs';
import {SOLO_POWERS,chooseLayout,choosePowerKit,createFinalBoardConfig,difficultyForProgress} from './solo-expansion.mjs';
const MAX_HISTORY=3;
const terminalEvent=status=>createDomainEvent(status===SOLO_STATUS.WON?'SOLO_WON':'SOLO_LOST');
const withPlayer=(state,player)=>({...state,players:state.players.map((candidate,index)=>index===0?player:candidate)});
const rejectSession=(session,code,details=null)=>({...session,events:[],rejection:{code,details}});
const finalize=(session,state,events,history=session.history)=>{const status=evaluateSoloStatus(state),terminal=status===SOLO_STATUS.PLAYING?[]:[terminalEvent(status)];return {...session,state:{...state,status},events:[...events,...terminal],history,rejection:null}};
const powerDef=id=>SOLO_POWERS.find(power=>power.id===id);
const resourceKey=id=>id==='shift'?'powerShift':id;
const equipped=(session,id)=>session.powerKit?.includes(id);
function spend(session,id,mutate){if(!equipped(session,id))return rejectSession(session,'SOLO_POWER_NOT_EQUIPPED');const key=resourceKey(id),player=session.state.players[0];if((player.resources?.[key]??0)<=0)return rejectSession(session,'SOLO_POWER_EMPTY');const changed=mutate(player);if(!changed)return rejectSession(session,'SOLO_POWER_UNAVAILABLE');const next={...changed,resources:{...changed.resources,[key]:changed.resources[key]-1}};return finalize(session,withPlayer(session.state,next),[createDomainEvent('SOLO_POWER_USED',{powerId:id,remaining:next.resources[key]})])}
function restoreTrayAt(player,index){const tileId=player.tray[index];if(!tileId)return null;return {...player,board:{...player.board,tiles:player.board.tiles.map(tile=>tile.id===tileId?{...tile,removed:false}:tile)},tray:player.tray.filter((_,i)=>i!==index)};}

export function createSoloSession({seed='solo-seed',boardConfig=null,playerId='solo-player',progress=0,recentLayouts=[]}={}){
  const layout=chooseLayout(seed,recentLayouts),config=boardConfig??createFinalBoardConfig(layout),board=boardConfig?generateBoard(boardConfig,seed):createSoloBoard(config,seed),powerKit=choosePowerKit(seed,progress);
  const player=createPlayerState({playerId,board,resources:{...DEFAULT_SOLO_RESOURCES}}),state=createGameState({mode:SOLO_MODE,seed,rulesetVersion:SOLO_RULESET_VERSION,status:SOLO_STATUS.CREATED,players:[player],shared:{logicalTurn:0,layoutId:layout.id,difficulty:difficultyForProgress(progress),powerKit:[...powerKit]}});
  return {state,context:createSoloRulesContext(),events:[],history:[],rejection:null,powerKit:[...powerKit],layout,progress};
}
export function startSoloSession(session){if(session.state.status!==SOLO_STATUS.CREATED)return rejectSession(session,'SOLO_ALREADY_STARTED');return {...session,state:{...session.state,status:SOLO_STATUS.PLAYING,startedAtLogical:0},events:[createDomainEvent('SOLO_STARTED',{layoutId:session.layout?.id,powerKit:session.powerKit})],rejection:null}}
export function soloPickTile(session,tileId){if(session.state.status!==SOLO_STATUS.PLAYING)return rejectSession(session,'SOLO_NOT_PLAYING');const actorId=session.state.players[0].playerId,result=dispatch(session.state,createCommand({type:PICK_TILE,actorId,payload:{tileId}}),session.context);if(!result.accepted)return {...session,events:result.events,rejection:result.rejection};const nextState={...result.state,shared:{...result.state.shared,logicalTurn:(result.state.shared.logicalTurn??0)+1}},history=[...session.history.slice(-(MAX_HISTORY-1)),session.state];return finalize(session,nextState,result.events,history)}
export function soloUndo(session){if(session.state.status!==SOLO_STATUS.PLAYING)return rejectSession(session,'SOLO_NOT_PLAYING');if(!equipped(session,'undo'))return rejectSession(session,'SOLO_POWER_NOT_EQUIPPED');const player=session.state.players[0];if((player.resources?.undo??0)<=0)return rejectSession(session,'SOLO_UNDO_EMPTY');if(!session.history.length)return rejectSession(session,'SOLO_UNDO_UNAVAILABLE');const previous=session.history.at(-1),restored=previous.players[0],nextPlayer={...restored,resources:{...restored.resources,undo:player.resources.undo-1,hint:player.resources.hint,rescue:player.resources.rescue,powerShift:player.resources.powerShift,scanner:player.resources.scanner,swap:player.resources.swap,magnet:player.resources.magnet,cleanse:player.resources.cleanse,freeze:player.resources.freeze}};return {...session,state:withPlayer({...previous,status:SOLO_STATUS.PLAYING},nextPlayer),history:session.history.slice(0,-1),events:[createDomainEvent('SOLO_UNDONE',{remaining:nextPlayer.resources.undo})],rejection:null}}
export function soloHint(session){if(session.state.status!==SOLO_STATUS.PLAYING)return rejectSession(session,'SOLO_NOT_PLAYING');if(!equipped(session,'hint'))return rejectSession(session,'SOLO_POWER_NOT_EQUIPPED');const player=session.state.players[0];if((player.resources?.hint??0)<=0)return rejectSession(session,'SOLO_HINT_EMPTY');const tileId=chooseSoloHint(session.state);if(!tileId)return rejectSession(session,'SOLO_HINT_UNAVAILABLE');const nextPlayer={...player,resources:{...player.resources,hint:player.resources.hint-1}};return {...session,state:withPlayer(session.state,nextPlayer),events:[createDomainEvent('SOLO_HINTED',{tileId,remaining:nextPlayer.resources.hint})],rejection:null}}
export function soloRescue(session){if(session.state.status!==SOLO_STATUS.PLAYING)return rejectSession(session,'SOLO_NOT_PLAYING');if(!equipped(session,'rescue'))return rejectSession(session,'SOLO_POWER_NOT_EQUIPPED');const player=session.state.players[0];if((player.resources?.rescue??0)<=0)return rejectSession(session,'SOLO_RESCUE_EMPTY');if(player.tray.length<6)return rejectSession(session,'SOLO_RESCUE_NOT_NEEDED');const restoredTileId=player.tray.at(-1),restored=rescueSoloPlayer(player);if(!restored)return rejectSession(session,'SOLO_RESCUE_UNAVAILABLE');const nextPlayer={...restored,resources:{...restored.resources,rescue:restored.resources.rescue-1}};return finalize(session,withPlayer(session.state,nextPlayer),[createDomainEvent('SOLO_RESCUED',{restoredTileId,remaining:nextPlayer.resources.rescue})])}
export function soloUsePower(session,powerId=SOLO_POWER.SHIFT){if(session.state.status!==SOLO_STATUS.PLAYING)return rejectSession(session,'SOLO_NOT_PLAYING');if(!equipped(session,powerId))return rejectSession(session,'SOLO_POWER_NOT_EQUIPPED');const actorId=session.state.players[0].playerId,result=dispatch(session.state,createCommand({type:USE_POWER,actorId,payload:{powerId}}),session.context);if(!result.accepted)return {...session,events:result.events,rejection:result.rejection};return finalize(session,result.state,result.events)}
export function soloUseNamedPower(session,id){
  if(session.state.status!==SOLO_STATUS.PLAYING)return rejectSession(session,'SOLO_NOT_PLAYING');
  if(id==='undo')return soloUndo(session);if(id==='hint')return soloHint(session);if(id==='rescue')return soloRescue(session);if(id==='shift')return soloUsePower(session,'shift');
  if(id==='scanner'){return spend(session,id,player=>{const ids=getAvailableTileIds(player.board).slice(0,6);return ids.length?{...player,meta:{...(player.meta??{}),scannerIds:ids}}:null})}
  if(id==='cleanse'){return spend(session,id,player=>player.tray.length?restoreTrayAt(player,0):null)}
  if(id==='freeze'){return spend(session,id,player=>player.tray.length>=5?restoreTrayAt(player,player.tray.length-1):null)}
  if(id==='swap'){return spend(session,id,player=>{if(!player.tray.length)return null;const restored=restoreTrayAt(player,player.tray.length-1);return restored?{...restored,meta:{...(restored.meta??{}),swapReady:true}}:null})}
  if(id==='magnet'){return spend(session,id,player=>{if(player.tray.length<2)return null;const families=new Map();for(const tileId of player.tray){const tile=player.board.tiles.find(t=>t.id===tileId);if(tile)families.set(tile.family,(families.get(tile.family)??0)+1)}const target=[...families.entries()].sort((a,b)=>b[1]-a[1])[0];if(!target)return null;const available=new Set(getAvailableTileIds(player.board)),tile=player.board.tiles.find(t=>!t.removed&&available.has(t.id)&&t.family===target[0]);return tile?{...player,meta:{...(player.meta??{}),magnetTileId:tile.id}}:null})}
  return rejectSession(session,'SOLO_POWER_UNKNOWN');
}
export {powerDef};
