import assert from 'node:assert/strict';
import fs from 'node:fs';

const policy=fs.readFileSync('zuno-navigation-policy-v1.js','utf8');
const nav=fs.readFileSync('zuno-global-navigation-v1.js','utf8');
const chrome=fs.readFileSync('zuno-global-chrome.js','utf8');
const chromeCss=fs.readFileSync('zuno-global-chrome.css','utf8');
const fluidCss=fs.readFileSync('zuno-fluid-ui.css','utf8');
const notificationsCss=fs.readFileSync('zuno-notifications.css','utf8');
const xpCss=fs.readFileSync('zuno-my-xp-v1.css','utf8');
const modernCss=fs.readFileSync('zuno-modernization-v1.css','utf8');
const messages=fs.readFileSync('zuno-messages-stable.js','utf8');
const shellJs=fs.readFileSync('zuno-shell-experience-v1.js','utf8');
const shellCss=fs.readFileSync('zuno-shell-experience-v1.css','utf8');
const runtime=fs.readFileSync('nav.js','utf8');

assert.match(policy,/\['pushState','replaceState'\]/,'navigation policy must resync after same-document route changes');
assert.match(policy,/window\.addEventListener\('popstate',\(\)=>apply\(\)\)/,'navigation policy must resync on browser history navigation');
assert.match(policy,/function goBack\(/,'navigation policy must own contextual back behavior');
assert.match(policy,/origin-with-fallback/,'navigation policy must preserve safe origin-aware fallback behavior');
assert.match(nav,/if\(!current\.bottomNav\)\{teardown\(\);return\}/,'bottom navigation must fail closed outside global routes');
assert.match(nav,/active==='central'/,'Central must expose its active state');
assert.match(nav,/maybeOpenCentral\(\)/,'a Central deep link must wait until the authenticated root shell exists');
assert.match(chrome,/if\(current\.header!=='global'\)\{teardown\(\);return\}/,'global header must fail closed on contextual and immersive routes');
assert.match(chromeCss,/data-zuno-navigation-mode="global"/,'bottom spacing must depend on the navigation mode');
assert.match(chromeCss,/height:calc\(48px \+ var\(--zuno-safe-top/,'mobile global header must stay compact while protecting its content');
assert.match(fluidCss,/data-zuno-page="pulso"[^}]*\.zm-header\{min-height:calc\(64px \+ var\(--zuno-safe-top\)\)!important;padding-top:var\(--zuno-safe-top\)!important\}/,'Pulso must paint edge-to-edge and position controls with one shared safe area');
assert.match(modernCss,/data-zuno-navigation-view="thread"[^}]*100dvh/,'private conversations must own the full viewport');
assert.match(messages,/top\.classList\.add\('zm-context-top'\)/,'the conversation inbox must retain a context header');
assert.doesNotMatch(messages,/top\.remove\(\)/,'the inbox context header must not be discarded');
assert.match(notificationsCss,/\.zn-app\{[^}]*overflow-x:hidden/,'notifications must contain horizontal overflow');
assert.match(notificationsCss,/\.zn-heading\{[^}]*min-width:0/,'notification heading must be shrinkable on narrow screens');
assert.match(xpCss,/\.zmx-shell\{[^}]*max-width:100%[^}]*overflow-x:hidden/,'Meu XP shell must contain lateral overflow');
assert.match(xpCss,/\.zmx-amount\{[^}]*max-width:45%[^}]*overflow-wrap:anywhere/,'Meu XP amounts must not cut the page horizontally');
assert.match(shellJs,/Sem conexão\. Alguns recursos/,'global shell must expose an offline state');
assert.match(shellJs,/data-zuno-generated-context-back/,'contextual screens without a local control must receive a canonical back control');
assert.match(shellCss,/:focus-visible/,'keyboard focus must remain visible');
assert.match(shellCss,/min-width:44px!important;min-height:44px!important/,'canonical contextual back target must meet the 44px touch contract');
assert.match(runtime,/zuno-shell-experience-v1\.css/,'shell accessibility layer must be loaded by the canonical runtime');
assert.match(runtime,/zuno-shell-experience-v1\.js/,'shell state layer must be loaded by the canonical runtime');
