import test from 'node:test';
import assert from 'node:assert/strict';
import {createSoloSession,startSoloSession,soloHint,soloPickTile,soloUndo,soloRescue,soloUsePower} from '../src/zuno-stack-v2/solo/solo-session.mjs';
import {projectSoloView} from '../src/zuno-stack-v2/solo/solo-view.mjs';
import {getAvailableTileIds} from '../src/zuno-stack-v2/core/index.mjs';
import {createAuthoritativeTrioMatch,disconnectAuthoritativeTrioPlayer,reconnectAuthoritativeTrioPlayer,reconcileAuthoritativeTrioClient,advanceAuthoritativeTrioLifecycle} from '../src/zuno-stack-v2/trio/trio-authority.mjs';
import {projectTrioSession} from '../src/zuno-stack-v2/trio/trio-session.mjs';
import {TRIO_CONNECTION_STATUS} from '../src/zuno-stack-v2/trio/trio-lifecycle.mjs';
import {createAuthoritativePvpMatch,prepareAuthoritativePvpMatch,openAuthoritativePvpReadyCheck,setAuthoritativePvpReady,tickAuthoritativePvpCountdown} from '../src/zuno-stack-v2/pvp/pvp-authority.mjs';
import {markPvpDisconnected,reconnectPvpPlayer,reconcilePvpClient,advancePvpServerTick,PVP_CONNECTION_STATUS} from '../src/zuno-stack-v2/pvp/pvp-lifecycle.mjs';
import {projectPvpSession} from '../src/zuno-stack-v2/pvp/pvp-session.mjs';
import {PVP_STATUS} from '../src/zuno-stack-v2/pvp/pvp-rules.mjs';
import {createAuraPresentation} from '../src/zuno-stack-v2/aura/aura-presentation-adapter.mjs';

const semanticStatus=status=>({text:String(status),role:'status','aria-live':['WON','LOST','RESOLVING','resolving','finished'].includes(status)?'polite':'off'});
const traySemantic=view=>view.trayCount>=7?{text:'Bandeja cheia 7 de 7',severity:'critical'}:view.trayCount>=6?{text:'Risco: bandeja 6 de 7',severity:'warning'}:{text:`Bandeja ${view.trayCount} de ${view.trayCapacity}`,severity:'normal'};
const actionSemantic=(name,enabled)=>({name,enabled,'aria-disabled':String(!enabled),minTouchTargetPx:44});
const presentSolo=view=>({status:semanticStatus(view.status),tray:traySemantic(view),actions:{undo:actionSemantic('Desfazer',view.canUndo),hint:actionSemantic('Dica',view.canHint),rescue:actionSemantic('Resgate',view.canRescue),shift:actionSemantic('Shift',view.canUseShift)},scoreText:`Pontuação ${view.score}`,comboText:`Combo ${view.combo}`,pulseText:`Pulso ${view.pulse} de ${view.pulseMax}`});
const presentTrio=(projection,lifecycle)=>({status:semanticStatus(projection.status),relayText:`Relay ${projection.shared.relay.filter(Boolean).length} de ${projection.shared.relay.length}`,pulseText:`Pulso compartilhado ${projection.shared.pulse.value} de ${projection.shared.pulse.max}`,connections:lifecycle.connections.map(c=>({playerId:c.playerId,text:c.status,afk:c.afkWarning??false})),supportText:lifecycle.support?.status??'inactive',lastStackText:lifecycle.lastStack?.status??'inactive'});
const presentPvp=(projection,lifecycle)=>({status:semanticStatus(projection.status),countdownText:`Contagem ${projection.shared.lifecycle.countdownRemaining}`,pressureText:`Pressão pendente ${projection.shared.pendingPressure[projection.viewerId]??0}`,connections:lifecycle.connections.map(c=>({playerId:c.playerId,text:c.status,afk:c.afkWarning})),winnerText:projection.shared.lifecycle.winnerId?`Vencedor ${projection.shared.lifecycle.winnerId}`:'Sem vencedor'});
function soloWithTray(count){const session=startSoloSession(createSoloSession({seed:`tray-${count}`}));const player=session.state.players[0];return {...session,state:{...session.state,players:[{...player,tray:Array.from({length:count},(_,i)=>`synthetic-${i}`)}]}};}

test('Solo integrated presentation exposes non-color terminal, tray risk and accessible controls',()=>{const session=startSoloSession(createSoloSession({seed:'presentation-solo'}));const view=projectSoloView(session.state,session.events);const ui=presentSolo(view);assert.equal(ui.actions.undo.name,'Desfazer');assert.equal(ui.actions.undo.minTouchTargetPx,44);assert.equal(ui.actions.rescue['aria-disabled'],String(!view.canRescue));assert.match(ui.scoreText,/Pontuação/);assert.match(ui.comboText,/Combo/);assert.match(ui.pulseText,/Pulso/);const risk=presentSolo(projectSoloView(soloWithTray(6).state,[]));assert.equal(risk.tray.severity,'warning');assert.match(risk.tray.text,/6 de 7/);const full=presentSolo(projectSoloView(soloWithTray(7).state,[]));assert.equal(full.tray.severity,'critical');assert.match(full.tray.text,/7 de 7/);for(const status of ['WON','LOST']){const terminal=presentSolo({...view,status});assert.equal(terminal.status.text,status);assert.equal(terminal.status.role,'status');}});

test('Solo presentation follows Hint, pick, Undo and unavailable Rescue/Shift without changing frozen rules',()=>{const session=startSoloSession(createSoloSession({seed:'presentation-actions'}));const initial=presentSolo(projectSoloView(session.state,[]));assert.equal(initial.actions.rescue.enabled,false);assert.equal(initial.actions.shift.enabled,false);const hinted=soloHint(session);assert.equal(hinted.rejection,null);const tileId=getAvailableTileIds(session.state.players[0].board)[0];const picked=soloPickTile(session,tileId);assert.equal(picked.rejection,null);const undone=soloUndo(picked);assert.equal(undone.rejection,null);const rescue=soloRescue(session);assert.ok(rescue.rejection);const shift=soloUsePower(session);assert.ok(shift.rejection);});

test('Trio integrated presentation covers Relay/shared Pulse plus reconnect, desync, Support and Last Stack semantics',()=>{let match=createAuthoritativeTrioMatch({matchId:'trio-ui',playerIds:['p1','p2','p3'],seed:'trio-ui'});let projection=projectTrioSession({state:match.state,events:[]},'p1');let ui=presentTrio(projection,match.lifecycle);assert.match(ui.relayText,/0 de 3/);assert.match(ui.pulseText,/Pulso compartilhado/);assert.equal(ui.connections.length,3);match=disconnectAuthoritativeTrioPlayer(match,'p2',{authenticatedActorId:'p2'});ui=presentTrio(projection,match.lifecycle);assert.equal(ui.connections.find(c=>c.playerId==='p2').text,TRIO_CONNECTION_STATUS.RECONNECTING);const desync=reconcileAuthoritativeTrioClient(match,{authenticatedActorId:'p1',revision:-1});assert.equal(desync.inSync,false);assert.ok(desync.snapshot);const reconnected=reconnectAuthoritativeTrioPlayer(match,'p2',{authenticatedActorId:'p2',clientRevision:-1});assert.equal(reconnected.match.lifecycle.connections.find(c=>c.playerId==='p2').status,TRIO_CONNECTION_STATUS.CONNECTED);const completedPlayers=reconnected.match.state.players.map((p,i)=>i<2?{...p,board:{...p.board,tiles:p.board.tiles.map(t=>({...t,removed:true}))},tray:[]}:p);match=advanceAuthoritativeTrioLifecycle({...reconnected.match,state:{...reconnected.match.state,players:completedPlayers}});assert.equal(match.lifecycle.support.status,'active');assert.equal(match.lifecycle.lastStack.status,'active');});

test('Trio AFK/reconnect timeout is textually representable and deterministic',()=>{let match=createAuthoritativeTrioMatch({matchId:'trio-timeout',playerIds:['p1','p2','p3'],seed:'trio-timeout',reconnectWindowTicks:2});match=disconnectAuthoritativeTrioPlayer(match,'p3',{authenticatedActorId:'p3'});match=advanceAuthoritativeTrioLifecycle(match,{revision:match.revision+2});assert.equal(match.lifecycle.connections.find(c=>c.playerId==='p3').status,TRIO_CONNECTION_STATUS.TIMED_OUT);const ui=presentTrio(projectTrioSession({state:match.state,events:[]},'p1'),match.lifecycle);assert.equal(ui.connections.find(c=>c.playerId==='p3').text,'timed_out');});

test('PvP integrated presentation covers ready/countdown, reconnect/desync, AFK and timeout resolving result',()=>{let match=createAuthoritativePvpMatch({matchId:'pvp-ui',playerIds:['p1','p2'],seed:'pvp-ui',reconnectWindowTicks:2,afkWarningTicks:1});match=prepareAuthoritativePvpMatch(match).match;match=openAuthoritativePvpReadyCheck(match).match;match=setAuthoritativePvpReady(match,'p1',{authenticatedActorId:'p1'}).match;match=setAuthoritativePvpReady(match,'p2',{authenticatedActorId:'p2'}).match;let projection=projectPvpSession({state:match.state,events:[]},'p1');assert.equal(projection.status,PVP_STATUS.COUNTDOWN);assert.match(presentPvp(projection,match.pvpLifecycle).countdownText,/Contagem/);while(match.state.status===PVP_STATUS.COUNTDOWN)match=tickAuthoritativePvpCountdown(match).match;projection=projectPvpSession({state:match.state,events:[]},'p1');assert.equal(projection.status,PVP_STATUS.PLAYING);assert.match(presentPvp(projection,match.pvpLifecycle).pressureText,/Pressão/);match=markPvpDisconnected(match,'p2');const desync=reconcilePvpClient(match,{playerId:'p1',revision:-1});assert.equal(desync.inSync,false);assert.ok(desync.snapshot);const reconnect=reconnectPvpPlayer(match,'p2',{clientRevision:-1});assert.equal(reconnect.match.pvpLifecycle.connections.find(c=>c.playerId==='p2').status,PVP_CONNECTION_STATUS.CONNECTED);match=markPvpDisconnected(reconnect.match,'p2');match=advancePvpServerTick(match,{ticks:2});assert.equal(match.state.status,PVP_STATUS.RESOLVING);const resolving=presentPvp(projectPvpSession({state:match.state,events:[]},'p1'),match.pvpLifecycle);assert.equal(resolving.status.text,PVP_STATUS.RESOLVING);assert.match(resolving.winnerText,/p1/);});

test('Aura standard, reduced-motion and low-end remain pointer/focus transparent and never carry critical gameplay information',()=>{const authority={playerId:'p1',authority:350,matches:100,byMode:{solo:10,trio:20,pvp:30},tier:'nexus',level:5,progress:0,progressRequired:0,nextAuthority:null};for(const profile of ['standard','reduced-motion','low-end']){const aura=createAuraPresentation(authority,{profile});assert.equal(aura.render.pointerEvents,'none');assert.equal(aura.render.layoutAffecting,false);assert.deepEqual(aura.render.properties,['transform','opacity']);assert.equal(Object.hasOwn(aura.render,'tabIndex'),false);assert.equal(Object.hasOwn(aura.render,'role'),false);if(profile!=='standard')assert.equal(aura.render.pulse.enabled,false);}const critical=presentSolo({...projectSoloView(startSoloSession(createSoloSession({seed:'critical'})).state,[]),status:'LOST'});assert.equal(critical.status.text,'LOST');assert.ok(!JSON.stringify(critical).includes('glow'));});

test('Android physical measurements remain explicitly external instead of being fabricated by CI',()=>{const deviceGate={status:'DEVICE_VALIDATION_REQUIRED',required:['entry-android','mid-tier-android'],measurements:['touch-p95','local-action-p95','main-thread-freeze','frame-pacing','memory','thermal','reconnect-visible-freeze','low-end-aura','reduced-motion']};assert.equal(deviceGate.status,'DEVICE_VALIDATION_REQUIRED');assert.equal(deviceGate.measurements.length,9);});
