import test from'node:test';import assert from'node:assert/strict';import{PICK_TILE,USE_POWER,createCommand,createCoreTransitions,createGameState,createModeRules,createPlayerState,createPowerCatalog,createRulesContext,createTile,createValidatedBoardState,dispatch,usePowerTransition,TRAY_CAPACITY,validateTrayState}from'../src/zuno-stack-v2/core/index.mjs';
function boardFor(seed,count=90){const tiles=Array.from({length:count},(_,i)=>createTile({id:`${seed}-t${i}`,family:`f${Math.floor(i/3)}`,position:{x:i,y:0},layer:0}));return createValidatedBoardState({tiles,layerCount:1})}
function context(extra={}){return createRulesContext({rules:createModeRules({modeId:'core-test',playerSlots:1,transitions:{...createCoreTransitions(),[USE_POWER]:usePowerTransition},progression:{scorePerTrio:5,pulsePerTrio:1,pulseMax:20,...extra.progression},powerCatalog:extra.powerCatalog??null})})}
function stateFor(seed,count=90,extra={}){return createGameState({mode:'core-test',seed,rulesetVersion:'freeze-r1',players:[createPlayerState({playerId:'p1',board:boardFor(seed,count),...extra})]})}
function pick(state,id,ctx){return dispatch(state,createCommand({type:PICK_TILE,actorId:'p1',payload:{tileId:id}}),ctx)}
function run(seed,count=90){const ctx=context();let state=stateFor(seed,count),events=[];for(let i=0;i<count;i++){const id=`${seed}-t${i}`,r=pick(state,id,ctx);assert.equal(r.accepted,true);events.push(...r.events);state=r.state;assert.ok(state.players[0].tray.length<=TRAY_CAPACITY);validateTrayState(state.players[0].board,state.players[0].tray)}return{state,events}}
test('property: multiple seeds are deterministic, serializable and conserve tile identity',()=>{for(let seed=0;seed<40;seed++){const a=run(seed,90),b=run(seed,90);assert.deepEqual(a,b);assert.doesNotThrow(()=>JSON.stringify(a));const p=a.state.players[0];assert.equal(new Set(p.board.tiles.map(t=>t.id)).size,p.board.tiles.length);assert.ok(p.pulse.value>=0&&p.pulse.value<=20);assert.ok(p.score>=0);assert.ok(p.combo.count>=0);assert.deepEqual(p.tray,[])}});
test('property: removed, missing and blocked picks reject atomically',()=>{const ctx=context();let state=stateFor('atomic',6);const first=pick(state,'atomic-t0',ctx);state=first.state;for(const id of['atomic-t0','missing']){const before=JSON.stringify(state),r=pick(state,id,ctx);assert.equal(r.accepted,false);assert.strictEqual(r.state,state);assert.equal(JSON.stringify(state),before);assert.deepEqual(r.events,[])}});
test('property: malicious power callback cannot mutate previous nested state',()=>{const catalog=createPowerCatalog([{id:'mutator',cost:0,apply:({player,state})=>{player.resources.deep.value=999;state.shared.hacked=true;return{player,events:[]}}}]);const ctx=context({powerCatalog:catalog});const state=createGameState({mode:'core-test',seed:'power',rulesetVersion:'freeze-r1',shared:{hacked:false},players:[createPlayerState({playerId:'p1',board:boardFor('power',3),resources:{deep:{value:1}}})]});const before=JSON.stringify(state);const r=dispatch(state,createCommand({type:USE_POWER,actorId:'p1',payload:{powerId:'mutator'}}),ctx);assert.equal(r.accepted,true);assert.equal(JSON.stringify(state),before);assert.equal(state.shared.hacked,false);assert.equal(state.players[0].resources.deep.value,1);assert.equal(r.state.players[0].resources.deep.value,999)});
test('property: invalid power pulse result is rejected atomically',()=>{const catalog=createPowerCatalog([{id:'badpulse',cost:0,apply:({player})=>({player:{...player,pulse:{value:999}},events:[]})}]);const ctx=context({powerCatalog:catalog});const state=stateFor('bad',3);const before=JSON.stringify(state),r=dispatch(state,createCommand({type:USE_POWER,actorId:'p1',payload:{powerId:'badpulse'}}),ctx);assert.equal(r.accepted,false);assert.equal(r.rejection.code,'POWER_INVALID_RESULT');assert.strictEqual(r.state,state);assert.equal(JSON.stringify(state),before)});
test('benchmark: 3000 accepted PICK_TILE transitions stay bounded',()=>{const count=3000,ctx=context({progression:{pulseMax:50}});let state=stateFor('bench',count);const initial=JSON.stringify(state).length,start=process.hrtime.bigint();for(let i=0;i<count;i++){const r=pick(state,`bench-t${i}`,ctx);assert.equal(r.accepted,true);state=r.state}const ms=Number(process.hrtime.bigint()-start)/1e6,final=JSON.stringify(state).length;assert.ok(ms<12000,`3000 transitions too slow: ${ms.toFixed(1)}ms`);assert.ok(final<=initial*1.05);assert.ok(state.players[0].pulse.value<=50)});
