import test from'node:test';import assert from'node:assert/strict';
import{SOLO_STATUS,createSoloSession,startSoloSession,soloPickTile,projectSoloView}from'../src/zuno-stack-v2/solo/index.mjs';
function playAll(seed='play'){let s=startSoloSession(createSoloSession({seed}));while(s.state.status===SOLO_STATUS.PLAYING){const v=projectSoloView(s.state);const tile=v.tiles.find(t=>t.available);assert.ok(tile);s=soloPickTile(s,tile.id)}return s}
test('solo creates exactly one deterministic serializable player in CREATED',()=>{const a=createSoloSession({seed:'same'}),b=createSoloSession({seed:'same'});assert.equal(a.state.players.length,1);assert.equal(a.state.status,SOLO_STATUS.CREATED);assert.deepEqual(a.state,b.state);assert.doesNotThrow(()=>JSON.stringify(a.state))});
test('solo starts and valid pick flows through core into tray/view',()=>{let s=startSoloSession(createSoloSession({seed:'pick'}));assert.equal(s.state.status,SOLO_STATUS.PLAYING);const v=projectSoloView(s.state,s.events),tile=v.tiles.find(t=>t.available);const before=JSON.stringify(s.state);s=soloPickTile(s,tile.id);assert.notEqual(JSON.stringify(s.state),before);assert.ok(s.events.some(e=>e.type==='TILE_PICKED'));assert.ok(s.state.players[0].tray.length<=7)});
test('blocked pick rejects atomically',()=>{let s=startSoloSession(createSoloSession({seed:'blocked',boardConfig:{layerCounts:[1,1],columns:1,rows:1,families:['a','b']}}));const blocked=s.state.players[0].board.tiles.find(t=>t.layer===0),before=s.state;s=soloPickTile(s,blocked.id);assert.strictEqual(s.state,before);assert.ok(s.rejection)});
test('complete basic sequence reaches WON and terminal commands do nothing',()=>{let s=playAll('win');assert.equal(s.state.status,SOLO_STATUS.WON);assert.deepEqual(s.state.players[0].tray,[]);const before=s.state;s=soloPickTile(s,'anything');assert.strictEqual(s.state,before)});
test('tray terminal condition reaches LOST',()=>{const boardConfig={layerCounts:[7],columns:7,rows:1,families:['a','b','c','d','e','f','g']};let s=startSoloSession(createSoloSession({seed:'loss',boardConfig}));for(let i=0;i<7;i++){const tile=projectSoloView(s.state).tiles.find(t=>t.available);s=soloPickTile(s,tile.id)}assert.equal(s.state.status,SOLO_STATUS.LOST)});
test('same seed and same selections produce identical states/events',()=>{const run=()=>{let s=startSoloSession(createSoloSession({seed:'det'})),all=[];while(s.state.status===SOLO_STATUS.PLAYING){const tile=projectSoloView(s.state).tiles.find(t=>t.available);s=soloPickTile(s,tile.id);all.push(...s.events)}return{state:s.state,events:all}};assert.deepEqual(run(),run())});
test('presentation projection cannot mutate source state',()=>{const s=startSoloSession(createSoloSession({seed:'view'})),before=JSON.stringify(s.state),v=projectSoloView(s.state);v.tiles[0].available=false;assert.equal(JSON.stringify(s.state),before)});
test('benchmark: boot and full minimal session stay responsive',()=>{const start=process.hrtime.bigint();for(let i=0;i<100;i++){const s=playAll(`bench-${i}`);assert.equal(s.state.status,SOLO_STATUS.WON)}const ms=Number(process.hrtime.bigint()-start)/1e6;assert.ok(ms<5000,`solo benchmark ${ms.toFixed(1)}ms`)});
