import test from 'node:test';
import assert from 'node:assert/strict';
import {createCommand,dispatch,getAvailableTileIds} from '../src/zuno-stack-v2/core/index.mjs';
import {createSoloSession,startSoloSession} from '../src/zuno-stack-v2/solo/solo-session.mjs';
import {createAuthoritativeMatch,executeAuthoritativeCommand,reconcileAuthoritativeMatch,finalizeAuthoritativeMatch,createRewardsBridgePayload} from '../src/zuno-stack-v2/server/authoritative-match-engine.mjs';

const make=({maxReceipts=8,status='PLAYING'}={})=>{const solo=startSoloSession(createSoloSession({seed:'phase4-hardening'}));return createAuthoritativeMatch({matchId:'hardening',mode:'solo',players:['solo-player'],state:{...solo.state,status},context:solo.context,status,maxReceipts,startedAt:10})};
const tile=match=>getAvailableTileIds(match.state.players[0].board)[0];
const env=(match,actionId='a',extra={})=>({matchId:'hardening',mode:'solo',actorId:'solo-player',actionId,expectedRevision:match.revision,command:{type:'PICK_TILE',payload:{tileId:tile(match)}},...extra});
const run=(match,input)=>executeAuthoritativeCommand(match,input,{dispatch,createCommand});

test('recursive authoritative fields are rejected anywhere in payload',()=>{for(const key of ['score','result','reward','rewards','xp','finishedAt','winner','valid','antiFarmFlags']){const m=make();const input=env(m,`bad-${key}`,{command:{type:'PICK_TILE',payload:{tileId:tile(m),nested:{[key]:1}}}});const r=run(m,input);assert.equal(r.receipt.accepted,false);assert.equal(r.receipt.rejection.code,'INVALID_ENVELOPE');assert.equal(r.match.revision,0)}});
test('same actionId with altered payload is collision, not replay',()=>{const m=make();const firstInput=env(m,'same');const first=run(m,firstInput);assert.equal(first.receipt.accepted,true);const altered={...firstInput,command:{type:'PICK_TILE',payload:{tileId:'tampered'}}};const second=run(first.match,altered);assert.equal(second.receipt.accepted,false);assert.equal(second.receipt.rejection.code,'ACTION_ID_COLLISION');assert.equal(second.match.revision,1)});
test('same actionId exact request replays across later revision without mutation',()=>{let m=make();const input=env(m,'r1');const first=run(m,input);m=first.match;const next=run(m,env(m,'r2'));m=next.match;const replay=run(m,input);assert.equal(replay.receipt.replayed,true);assert.equal(replay.match.revision,m.revision);assert.deepEqual(replay.match,m)});
test('expired receipt no longer replays and stale revision still fails closed',()=>{let m=make({maxReceipts:2});const original=env(m,'old');m=run(m,original).match;m=run(m,env(m,'n1')).match;m=run(m,env(m,'n2')).match;assert.equal(m.receipts.some(r=>r.actionId==='old'),false);const replay=run(m,original);assert.equal(replay.receipt.accepted,false);assert.equal(replay.receipt.rejection.code,'STALE_REVISION');assert.equal(replay.match.revision,m.revision)});
test('fuzz invalid actors modes matches and revisions are atomic',()=>{const variants=[];for(let i=0;i<100;i++){const m=make();variants.push(env(m,`x${i}`,i%4===0?{actorId:`bad-${i}`}:i%4===1?{mode:'bad'}:i%4===2?{matchId:'bad'}:{expectedRevision:99}))}for(const input of variants){const m=make();const before=JSON.stringify(m.state);const r=run(m,input);assert.equal(r.receipt.accepted,false);assert.equal(JSON.stringify(r.match.state),before);assert.equal(r.match.revision,0)}});
test('long mixed valid/invalid command sequence preserves monotonic revision',()=>{let m=make({maxReceipts:16});let accepted=0;for(let i=0;i<40&&!['WON','LOST'].includes(m.state.status);i++){if(i%3===0){const r=run(m,env(m,`bad-${i}`,{expectedRevision:m.revision+5}));assert.equal(r.receipt.accepted,false);assert.equal(r.match.revision,accepted)}else{const r=run(m,env(m,`ok-${i}`));if(r.receipt.accepted){accepted++;m=r.match;assert.equal(m.revision,accepted)}}}assert.ok(accepted>0)});
test('bootstrap/reconcile state copies cannot mutate authoritative match',()=>{const m=make();const desync=reconcileAuthoritativeMatch(m,{revision:999});desync.snapshot.state.players[0].score=999999;assert.notEqual(m.state.players[0].score,999999)});
test('terminal closure stays idempotent and rewards bridge remains disabled',()=>{const m=make({status:'WON'});const first=finalizeAuthoritativeMatch(m,{finishedAt:20});const second=finalizeAuthoritativeMatch(first.match,{finishedAt:999});assert.equal(second.replayed,true);assert.deepEqual(second.result,first.result);const bridge=createRewardsBridgePayload(first.match);assert.equal(bridge.rewardsEnabled,false);assert.equal(bridge.xpEnabled,false)});
test('benchmark: mixed authority operations remain bounded',()=>{const m=make();const start=performance.now();for(let i=0;i<1000;i++){run(m,env(m,`bad-${i}`,{expectedRevision:9}));reconcileAuthoritativeMatch(m,{revision:i%2});}assert.ok(performance.now()-start<2000)});
