import test from 'node:test';import assert from 'node:assert/strict';
import {getAvailableTileIds} from '../src/zuno-stack-v2/core/index.mjs';
import {createRewardsBridgePayload} from '../src/zuno-stack-v2/server/authoritative-match-engine.mjs';
import {createTrioSession,startTrioSession,trioPickTile,trioRelayPut,trioRelayTake,trioUseSharedPulse,projectTrioSession} from '../src/zuno-stack-v2/trio/trio-session.mjs';
import {createAuthoritativeTrioMatch,executeAuthoritativeTrioCommand} from '../src/zuno-stack-v2/trio/trio-authority.mjs';

const ids=['p1','p2','p3'];const make=()=>startTrioSession(createTrioSession({seed:'phase5',playerIds:ids}));const tile=(s,p='p1')=>getAvailableTileIds(s.state.players.find(x=>x.playerId===p).board)[0];
test('Trio requires exactly three unique stable slots',()=>{assert.throws(()=>createTrioSession({playerIds:['a','b']}));assert.throws(()=>createTrioSession({playerIds:['a','a','b']}));const s=make();assert.deepEqual(s.slots.map(x=>x.playerId),ids);assert.equal(s.state.players.length,3)});
test('players have independent boards and trays capped by Core contract',()=>{const s=make();assert.equal(s.state.players.every(p=>p.tray.length===0),true);assert.notStrictEqual(s.state.players[0].board,s.state.players[1].board);assert.notStrictEqual(s.state.players[1].board,s.state.players[2].board);assert.equal(s.state.players.every(p=>p.board.layerCount===12),true);const before=JSON.stringify(s.state.players[1].board);const next=trioPickTile(s,'p1',tile(s,'p1'));assert.equal(JSON.stringify(next.state.players[1].board),before)});
test('player can pick only from own board identity namespace',()=>{let s=make();const foreign=tile(s,'p2');const before=JSON.stringify(s.state);s=trioPickTile(s,'p1',foreign);assert.ok(s.rejection);assert.equal(JSON.stringify(s.state),before);const own=make();s=trioPickTile(own,'p1',tile(own,'p1'));assert.equal(s.rejection,null)});
test('relay has exactly three shared slots and moves without duplication',()=>{let s=make();for(let i=0;i<3;i++)s=trioPickTile(s,'p1',tile(s,'p1'));assert.ok(s.state.players[0].tray.length<=2);s=trioPickTile(s,'p1',tile(s,'p1'));const id=s.state.players[0].tray[0];s=trioRelayPut(s,'p1',id);assert.equal(s.state.shared.relay.length,3);assert.equal(s.state.shared.relay.filter(Boolean).length,1);assert.equal(s.state.players[0].tray.includes(id),false);s=trioRelayTake(s,'p2',0);assert.equal(s.state.shared.relay[0],null);assert.equal(s.state.players[1].tray.includes(id),true)});
test('shared Pulse derives from valid trio and cannot double spend below zero',()=>{let s=make();for(let i=0;i<3;i++)s=trioPickTile(s,'p1',tile(s,'p1'));assert.equal(s.state.shared.pulse.value,1);s=trioUseSharedPulse(s,'p2');assert.equal(s.state.shared.pulse.value,0);const before=JSON.stringify(s.state);s=trioUseSharedPulse(s,'p3');assert.ok(s.rejection);assert.equal(JSON.stringify(s.state),before)});
test('presentation keeps remote boards compact',()=>{const s=make();const view=projectTrioSession(s,'p1');assert.ok(view.local.board);assert.equal(view.players.every(p=>!('board'in p)),true);assert.doesNotThrow(()=>JSON.stringify(view))});
test('authoritative Trio binds authenticated actor and preserves revision/actionId replay',()=>{let m=createAuthoritativeTrioMatch({matchId:'m1',playerIds:ids,seed:'auth'});const id=getAvailableTileIds(m.state.players[0].board)[0];const input={matchId:'m1',mode:'trio',actorId:'p1',actionId:'a1',expectedRevision:0,command:{type:'PICK_TILE',payload:{tileId:id}}};const spoof=executeAuthoritativeTrioCommand(m,input,{authenticatedActorId:'p2'});assert.equal(spoof.receipt.accepted,false);const first=executeAuthoritativeTrioCommand(m,input,{authenticatedActorId:'p1'});assert.equal(first.receipt.accepted,true);assert.equal(first.match.revision,1);const replay=executeAuthoritativeTrioCommand(first.match,input,{authenticatedActorId:'p1'});assert.equal(replay.receipt.replayed,true);assert.equal(replay.match.revision,1)});
test('XP and rewards remain fail closed before verified terminal result',()=>{const m=createAuthoritativeTrioMatch({matchId:'m2',playerIds:ids});assert.throws(()=>createRewardsBridgePayload(m),/VERIFIED_RESULT_REQUIRED/)});
test('determinism serialization and board benchmark stay bounded',()=>{const a=createTrioSession({seed:'same',playerIds:ids});const b=createTrioSession({seed:'same',playerIds:ids});assert.equal(JSON.stringify(a.state),JSON.stringify(b.state));const start=performance.now();for(let i=0;i<10;i++)createTrioSession({seed:`bench-${i}`,playerIds:ids});assert.ok(performance.now()-start<4000)});
