import test from'node:test';import assert from'node:assert/strict';import{createGameState,createPlayerState,createModeRules,createRulesContext,createCommand,createValidatedBoardState,createTile,dispatch,createCoreTransitions,TRAY_CAPACITY}from'../src/zuno-stack-v2/core/index.mjs';
function stateFor(tiles,tray=[]){const board=createValidatedBoardState({tiles,layerCount:Math.max(...tiles.map(t=>t.layer))+1});return createGameState({mode:'core-test',players:[createPlayerState({playerId:'p1',board,tray})]})}
function pick(state,tileId){const rules=createModeRules({modeId:'core-test',playerSlots:1,transitions:createCoreTransitions()});return dispatch(state,createCommand({type:'PICK_TILE',actorId:'p1',payload:{tileId}}),createRulesContext({rules}))}
const tile=(id,family,x,layer=0)=>createTile({id,family,position:{x,y:0},layer});
test('valid pick removes board tile and appends canonical tray entry',()=>{const result=pick(stateFor([tile('a','A',0)]),'a');assert.equal(result.accepted,true);assert.equal(result.state.players[0].board.tiles[0].removed,true);assert.deepEqual(result.state.players[0].tray,[{tileId:'a',family:'A'}]);assert.deepEqual(result.events.map(e=>e.type),['TILE_PICKED','TRAY_CHANGED'])});
test('blocked, missing and already removed tiles reject atomically',()=>{const original=stateFor([tile('low','A',0,0),tile('high','B',0,1)]);for(const id of['low','missing']){const result=pick(original,id);assert.equal(result.accepted,false);assert.strictEqual(result.state,original)}const removed=structuredClone(original);removed.players[0].board.tiles[1].removed=true;const result=pick(removed,'high');assert.equal(result.accepted,false);assert.strictEqual(result.state,removed)});
test('third same family resolves exactly one trio in same transition',()=>{const initial=stateFor([tile('c','A',0)],[{tileId:'a',family:'A'},{tileId:'b',family:'A'},{tileId:'x',family:'B'}]);const result=pick(initial,'c');assert.equal(result.accepted,true);assert.deepEqual(result.state.players[0].tray,[{tileId:'x',family:'B'}]);assert.deepEqual(result.events.map(e=>e.type),['TILE_PICKED','TRIO_RESOLVED','TRAY_CHANGED']);assert.deepEqual(result.events[1].payload.tileIds,['a','b','c'])});
test('multiple families preserve insertion order independent of UI',()=>{const initial=stateFor([tile('c','A',0)],[{tileId:'b1',family:'B'},{tileId:'a1',family:'A'},{tileId:'b2',family:'B'},{tileId:'a2',family:'A'}]);const result=pick(initial,'c');assert.deepEqual(result.state.players[0].tray.map(e=>e.tileId),['b1','b2'])});
test('tray capacity seven rejects overflow without mutation',()=>{const tray=Array.from({length:TRAY_CAPACITY},(_,i)=>({tileId:`q${i}`,family:String(i)}));const original=stateFor([tile('x','X',0)],tray);const result=pick(original,'x');assert.equal(result.accepted,false);assert.equal(result.rejection.code,'TRAY_FULL');assert.strictEqual(result.state,original);assert.equal(original.players[0].board.tiles[0].removed,false)});
test('transition is deterministic and serializable',()=>{const original=stateFor([tile('a','A',0)]);const a=pick(original,'a'),b=pick(original,'a');assert.deepEqual(a,b);assert.deepEqual(JSON.parse(JSON.stringify(a.state)),a.state)});
test('long PICK_TILE sequence stays bounded and fast',()=>{const tiles=Array.from({length:90},(_,i)=>tile(`t${i}`,`F${i%3}`,i));let state=stateFor(tiles);const start=process.hrtime.bigint();for(let i=0;i<90;i++){const result=pick(state,`t${i}`);assert.equal(result.accepted,true);state=result.state;assert.ok(state.players[0].tray.length<TRAY_CAPACITY)}const ms=Number(process.hrtime.bigint()-start)/1e6;assert.ok(ms<3000,`sequence exceeded ceiling: ${ms.toFixed(1)}ms`);assert.equal(state.players[0].board.tiles.length,90)});
