import test from 'node:test';import assert from 'node:assert/strict';import {getAvailableTileIds} from '../src/zuno-stack-v2/core/index.mjs';import {createPvpSession,projectPvpSession} from '../src/zuno-stack-v2/pvp/pvp-session.mjs';import {createAuthoritativePvpMatch,executeAuthoritativePvpCommand} from '../src/zuno-stack-v2/pvp/pvp-authority.mjs';
const ids=['p1','p2'];const make=()=>createAuthoritativePvpMatch({matchId:'pvp-basic',playerIds:ids,seed:'fair'});const input=(m,actorId,actionId,tileId,rev=m.revision)=>({matchId:m.matchId,mode:'pvp',actorId,actionId,expectedRevision:rev,command:{type:'PICK_TILE',payload:{tileId}}});
test('requires exactly two unique players',()=>{for(const bad of [[],['a'],['a','a'],['a','b','c']])assert.throws(()=>createPvpSession({playerIds:bad}))});
test('creates stable independent slots boards and trays',()=>{const s=createPvpSession({playerIds:ids,seed:'same'});assert.deepEqual(s.slots,[{slot:0,playerId:'p1'},{slot:1,playerId:'p2'}]);assert.notEqual(s.state.players[0].board,s.state.players[1].board);assert.notEqual(s.state.players[0].tray,s.state.players[1].tray);assert.deepEqual(s.state.players[0].board,s.state.players[1].board)});
test('projection exposes local board but remote compact state',()=>{const s=createPvpSession({playerIds:ids});const v=projectPvpSession({...s,state:{...s.state,status:'PLAYING'}},'p1');assert.ok(v.local.board);assert.equal(v.players[1].board,undefined);assert.equal(v.players[1].tray,undefined)});
test('authenticated actor binding rejects spoof atomically',()=>{const m=make();const tile=getAvailableTileIds(m.state.players[0].board)[0];const out=executeAuthoritativePvpCommand(m,input(m,'p1','spoof',tile),{authenticatedActorId:'p2'});assert.equal(out.receipt.accepted,false);assert.equal(out.receipt.rejection.code,'AUTHENTICATED_ACTOR_MISMATCH');assert.equal(out.match.revision,0)});
test('player cannot pick tile from opponent board',()=>{const m=make();const foreign=getAvailableTileIds(m.state.players[1].board)[0];const out=executeAuthoritativePvpCommand(m,input(m,'p1','foreign',foreign),{authenticatedActorId:'p1'});assert.equal(out.receipt.accepted,false)});
test('revision and actionId idempotency are server authoritative',()=>{let m=make();const tile=getAvailableTileIds(m.state.players[0].board)[0];const first=executeAuthoritativePvpCommand(m,input(m,'p1','once',tile),{authenticatedActorId:'p1'});assert.equal(first.receipt.accepted,true);const replay=executeAuthoritativePvpCommand(first.match,input(first.match,'p1','once',tile,0),{authenticatedActorId:'p1'});assert.equal(replay.receipt.replayed,true);const staleTile=getAvailableTileIds(first.match.state.players[0].board)[0];const stale=executeAuthoritativePvpCommand(first.match,input(first.match,'p1','stale',staleTile,0),{authenticatedActorId:'p1'});assert.equal(stale.receipt.accepted,false)});
test('same seed is deterministic and serializable',()=>{const a=createPvpSession({playerIds:ids,seed:'det'});const b=createPvpSession({playerIds:ids,seed:'det'});assert.equal(JSON.stringify(a.state),JSON.stringify(b.state));assert.doesNotThrow(()=>JSON.stringify(a))});
