import {createCommand,createDomainEvent,createGameState,createPlayerState,dispatch} from '../core/index.mjs';
import {PVP_COMMAND,PVP_COUNTDOWN_TICKS,PVP_INTERFERENCE,PVP_MODE,PVP_RULESET_VERSION,PVP_STATUS,createPvpBoard,createPvpRulesContext,evaluatePvpStatus,getPvpWinnerId} from './pvp-rules.mjs';
const clone=value=>JSON.parse(JSON.stringify(value));
const reject=(session,code)=>({...session,events:[],rejection:{code,details:null}});
const lifecycle=(playerIds,status=PVP_STATUS.FORMING)=>({status,ready:Object.fromEntries(playerIds.map(id=>[id,false])),countdownRemaining:PVP_COUNTDOWN_TICKS,winnerId:null,terminalReason:null});
export function createPvpSession({seed='pvp-seed',playerIds=['pvp-1','pvp-2'],boardConfig}={}){if(!Array.isArray(playerIds)||playerIds.length!==2||new Set(playerIds).size!==2)throw new TypeError('PvP requires exactly 2 unique player slots');const players=playerIds.map(playerId=>createPlayerState({playerId,board:createPvpBoard(boardConfig,`${seed}|fair-board`,playerId)}));return{state:createGameState({mode:PVP_MODE,seed,rulesetVersion:PVP_RULESET_VERSION,status:PVP_STATUS.FORMING,players,shared:{pendingPressure:Object.fromEntries(playerIds.map(id=>[id,0])),lastPressureRevision:Object.fromEntries(playerIds.map(id=>[id,null])),logicalTurn:0,lifecycle:lifecycle(playerIds)}}),context:createPvpRulesContext(),slots:playerIds.map((playerId,index)=>({slot:index,playerId})),events:[],rejection:null}}
export function preparePvpSession(session){if(session.state.status!==PVP_STATUS.FORMING)return reject(session,'PVP_NOT_FORMING');return{...session,state:{...session.state,status:PVP_STATUS.PREPARING,shared:{...session.state.shared,lifecycle:{...session.state.shared.lifecycle,status:PVP_STATUS.PREPARING}}},events:[createDomainEvent('PVP_PREPARING',{})],rejection:null}}
export function openPvpReadyCheck(session){if(session.state.status!==PVP_STATUS.PREPARING)return reject(session,'PVP_NOT_PREPARING');return{...session,state:{...session.state,status:PVP_STATUS.READY_CHECK,shared:{...session.state.shared,lifecycle:{...session.state.shared.lifecycle,status:PVP_STATUS.READY_CHECK}}},events:[createDomainEvent('PVP_READY_CHECK_OPENED',{})],rejection:null}}
export function setPvpReady(session,actorId){if(session.state.status!==PVP_STATUS.READY_CHECK)return reject(session,'PVP_NOT_READY_CHECK');if(!session.slots.some(s=>s.playerId===actorId))return reject(session,'PVP_ACTOR_NOT_IN_SLOT');const ready={...session.state.shared.lifecycle.ready,[actorId]:true};const allReady=session.slots.every(s=>ready[s.playerId]);const nextStatus=allReady?PVP_STATUS.COUNTDOWN:PVP_STATUS.READY_CHECK;return{...session,state:{...session.state,status:nextStatus,shared:{...session.state.shared,lifecycle:{...session.state.shared.lifecycle,status:nextStatus,ready}}},events:[createDomainEvent('PVP_PLAYER_READY',{actorId}),...(allReady?[createDomainEvent('PVP_COUNTDOWN_STARTED',{remaining:PVP_COUNTDOWN_TICKS})]:[])],rejection:null}}
export function tickPvpCountdown(session){if(session.state.status!==PVP_STATUS.COUNTDOWN)return reject(session,'PVP_NOT_COUNTDOWN');const remaining=Math.max(0,session.state.shared.lifecycle.countdownRemaining-1);const status=remaining===0?PVP_STATUS.PLAYING:PVP_STATUS.COUNTDOWN;return{...session,state:{...session.state,status,shared:{...session.state.shared,lifecycle:{...session.state.shared.lifecycle,status,countdownRemaining:remaining}}},events:[createDomainEvent(status===PVP_STATUS.PLAYING?'PVP_STARTED':'PVP_COUNTDOWN_TICK',{remaining})],rejection:null}}
export function startPvpSession(session){let next=preparePvpSession(session);if(next.rejection)return next;next=openPvpReadyCheck(next);return next}
export function executePvpCommand(session,{actorId,type,payload={}}={}){if(session.state.status!==PVP_STATUS.PLAYING)return reject(session,'PVP_NOT_PLAYING');if(!session.slots.some(s=>s.playerId===actorId))return reject(session,'PVP_ACTOR_NOT_IN_SLOT');if(type===PVP_COMMAND.PRESSURE){const targetId=payload.targetPlayerId;if(Object.keys(payload).some(key=>!['targetPlayerId'].includes(key)))return reject(session,'PVP_PRESSURE_PAYLOAD');if(targetId===actorId||!session.slots.some(s=>s.playerId===targetId))return reject(session,'PVP_INVALID_TARGET');const actor=session.state.players.find(p=>p.playerId===actorId);const pulse=actor.pulse?.value??actor.pulse??0;if(pulse<PVP_INTERFERENCE.pressure.cost)return reject(session,'PVP_PRESSURE_COST');const current=session.state.shared.pendingPressure[targetId]??0;if(current>=PVP_INTERFERENCE.pressure.maxPendingPerTarget)return reject(session,'PVP_PRESSURE_LIMIT');const last=session.state.shared.lastPressureRevision[actorId];if(last!==null&&session.state.shared.logicalTurn-last<PVP_INTERFERENCE.pressure.cooldownRevisions)return reject(session,'PVP_PRESSURE_COOLDOWN');const players=session.state.players.map(p=>p.playerId===actorId?{...p,pulse:typeof p.pulse==='object'?{...p.pulse,value:p.pulse.value-PVP_INTERFERENCE.pressure.cost}:p.pulse-PVP_INTERFERENCE.pressure.cost}:p);const shared={...session.state.shared,pendingPressure:{...session.state.shared.pendingPressure,[targetId]:current+1},lastPressureRevision:{...session.state.shared.lastPressureRevision,[actorId]:session.state.shared.logicalTurn},logicalTurn:session.state.shared.logicalTurn+1};return{...session,state:{...session.state,players,shared},events:[createDomainEvent('PVP_PRESSURE_QUEUED',{actorId,targetPlayerId:targetId})],rejection:null}}
const result=dispatch(session.state,createCommand({type,actorId,payload}),session.context);if(!result.accepted)return{...session,events:result.events,rejection:result.rejection};const status=evaluatePvpStatus(result.state);const winnerId=status===PVP_STATUS.RESOLVING?getPvpWinnerId(result.state):null;return{...session,state:{...result.state,status,shared:{...result.state.shared,logicalTurn:(result.state.shared.logicalTurn??0)+1,lifecycle:{...result.state.shared.lifecycle,status,winnerId,terminalReason:winnerId?'board_cleared':null}}},events:[...result.events,...(winnerId?[createDomainEvent('PVP_RESOLVING',{winnerId})]:[])],rejection:null}}
export function finishPvpResolution(session){if(session.state.status!==PVP_STATUS.RESOLVING)return reject(session,'PVP_NOT_RESOLVING');const winnerId=session.state.shared.lifecycle.winnerId;if(!winnerId)return reject(session,'PVP_WINNER_REQUIRED');return{...session,state:{...session.state,status:PVP_STATUS.FINISHED,shared:{...session.state.shared,lifecycle:{...session.state.shared.lifecycle,status:PVP_STATUS.FINISHED}}},events:[createDomainEvent('PVP_FINISHED',{winnerId})],rejection:null}}
export function projectPvpSession(session,viewerId){const viewer=session.state.players.find(p=>p.playerId===viewerId);if(!viewer)throw new Error('PVP_VIEWER_NOT_IN_MATCH');return clone({mode:session.state.mode,status:session.state.status,viewerId,shared:{logicalTurn:session.state.shared.logicalTurn,lifecycle:session.state.shared.lifecycle,pendingPressure:session.state.shared.pendingPressure},players:session.state.players.map(p=>({playerId:p.playerId,score:p.score,trayCount:p.tray.length,remainingTiles:p.board.tiles.filter(t=>!t.removed).length,pulse:p.pulse?.value??p.pulse??0,local:p.playerId===viewerId})),local:{board:viewer.board,tray:viewer.tray,pulse:viewer.pulse},events:session.events})}
