import {createCommand,createDomainEvent,createGameState,createPlayerState,dispatch} from '../core/index.mjs';
import {PVP_COMMAND,PVP_INTERFERENCE,PVP_MODE,PVP_RULESET_VERSION,PVP_STATUS,createPvpBoard,createPvpRulesContext,evaluatePvpStatus} from './pvp-rules.mjs';
const clone=value=>JSON.parse(JSON.stringify(value));
const reject=(session,code)=>({...session,events:[],rejection:{code,details:null}});
export function createPvpSession({seed='pvp-seed',playerIds=['pvp-1','pvp-2'],boardConfig}={}){if(!Array.isArray(playerIds)||playerIds.length!==2||new Set(playerIds).size!==2)throw new TypeError('PvP requires exactly 2 unique player slots');const players=playerIds.map(playerId=>createPlayerState({playerId,board:createPvpBoard(boardConfig,`${seed}|fair-board`,playerId)}));return{state:createGameState({mode:PVP_MODE,seed,rulesetVersion:PVP_RULESET_VERSION,status:PVP_STATUS.CREATED,players,shared:{pendingPressure:Object.fromEntries(playerIds.map(id=>[id,0])),logicalTurn:0}}),context:createPvpRulesContext(),slots:playerIds.map((playerId,index)=>({slot:index,playerId})),events:[],rejection:null}}
export function startPvpSession(session){if(session.state.status!==PVP_STATUS.CREATED)return reject(session,'PVP_ALREADY_STARTED');return{...session,state:{...session.state,status:PVP_STATUS.PLAYING},events:[createDomainEvent('PVP_STARTED',{players:session.slots.map(s=>s.playerId)})],rejection:null}}
export function executePvpCommand(session,{actorId,type,payload={}}={}){if(session.state.status!==PVP_STATUS.PLAYING)return reject(session,'PVP_NOT_PLAYING');if(!session.slots.some(s=>s.playerId===actorId))return reject(session,'PVP_ACTOR_NOT_IN_SLOT');if(type===PVP_COMMAND.PRESSURE){const targetId=payload.targetPlayerId;if(targetId===actorId||!session.slots.some(s=>s.playerId===targetId))return reject(session,'PVP_INVALID_TARGET');const actor=session.state.players.find(p=>p.playerId===actorId);if((actor.pulse?.value??actor.pulse??0)<PVP_INTERFERENCE.pressure.cost)return reject(session,'PVP_PRESSURE_COST');const current=session.state.shared.pendingPressure[targetId]??0;if(current>=PVP_INTERFERENCE.pressure.maxPendingPerTarget)return reject(session,'PVP_PRESSURE_LIMIT');const players=session.state.players.map(p=>p.playerId===actorId?{...p,pulse:typeof p.pulse==='object'?{...p.pulse,value:p.pulse.value-PVP_INTERFERENCE.pressure.cost}:p.pulse-PVP_INTERFERENCE.pressure.cost}:p);const shared={...session.state.shared,pendingPressure:{...session.state.shared.pendingPressure,[targetId]:current+1},logicalTurn:session.state.shared.logicalTurn+1};return{...session,state:{...session.state,players,shared},events:[createDomainEvent('PVP_PRESSURE_QUEUED',{actorId,targetPlayerId:targetId})],rejection:null}}
const result=dispatch(session.state,createCommand({type,actorId,payload}),session.context);if(!result.accepted)return{...session,events:result.events,rejection:result.rejection};const status=evaluatePvpStatus(result.state);return{...session,state:{...result.state,status,shared:{...result.state.shared,logicalTurn:(result.state.shared.logicalTurn??0)+1}},events:result.events,rejection:null}}
export function projectPvpSession(session,viewerId){const viewer=session.state.players.find(p=>p.playerId===viewerId);if(!viewer)throw new Error('PVP_VIEWER_NOT_IN_MATCH');return clone({mode:session.state.mode,status:session.state.status,viewerId,shared:session.state.shared,players:session.state.players.map(p=>({playerId:p.playerId,score:p.score,trayCount:p.tray.length,remainingTiles:p.board.tiles.filter(t=>!t.removed).length,local:p.playerId===viewerId})),local:{board:viewer.board,tray:viewer.tray,pulse:viewer.pulse},events:session.events})}
