import {createRankingStore,getRankingStandings,processVerifiedRankingResult} from './ranking-processor.mjs';
const clone=value=>JSON.parse(JSON.stringify(value));
const canonical=value=>{if(Array.isArray(value))return value.map(canonical);if(value&&typeof value==='object')return Object.fromEntries(Object.keys(value).sort().map(key=>[key,canonical(value[key])]));return value};
const stable=value=>JSON.stringify(canonical(value));
const pairKey=players=>[...players].sort().join('|');
export function createRankingRepository(initial=createRankingStore()){let store=clone(initial);let queue=Promise.resolve();return {read:()=>clone(store),transact(fn){const run=queue.then(async()=>{const next=await fn(store);if(next?.store)store=next.store;return clone(next)});queue=run.then(()=>undefined,()=>undefined);return run;}}}
export function deriveServerAntiFarmFlags(store,result,{repeatParticipantsLimit=null,minDurationMs=null}={}){const flags=[];const history=store.history??[];if(Number.isSafeInteger(repeatParticipantsLimit)&&repeatParticipantsLimit>=0){const pair=pairKey(result.players??[]);const repeats=history.filter(x=>x.mode===result.mode&&pairKey(x.players??[])===pair).length;if(repeats>=repeatParticipantsLimit)flags.push('REPEATED_PARTICIPANTS');}if(Number.isSafeInteger(minDurationMs)&&minDurationMs>=0&&Number.isSafeInteger(result.startedAt)&&Number.isSafeInteger(result.finishedAt)&&result.finishedAt-result.startedAt<minDurationMs)flags.push('MATCH_TOO_SHORT');if(result.disconnectReason||result.abandoned===true)flags.push('ABANDON_OR_DISCONNECT');return flags;}
export async function consumeVerifiedRankingResult(repository,{season,result,policy={}}={}){return repository.transact(store=>{const serverFlags=deriveServerAntiFarmFlags(store,result,policy);const trustedResult={...clone(result),antiFarmFlags:[...new Set([...(Array.isArray(result?.antiFarmFlags)?result.antiFarmFlags:[]),...serverFlags])]};return processVerifiedRankingResult(store,{season,result:trustedResult,blockingAntiFarmFlags:policy.blockingFlags??[]});});}
export function rebuildRankingStore(history=[]){const store=createRankingStore();for(const item of history){const ladderKey=`${item.seasonId}:${item.mode}`;const ladder=store.standings[ladderKey]??={};for(const playerId of item.players){const delta=Number(item.deltas?.[playerId]??0);const current=ladder[playerId]??{playerId,points:0,matches:0,wins:0,lastFinishedAt:null,bestRemainingTiles:null};const win=item.mode==='pvp'&&delta>0;ladder[playerId]={...current,points:current.points+delta,matches:current.matches+1,wins:current.wins+(win?1:0),lastFinishedAt:item.finishedAt,bestRemainingTiles:item.tieBreak?.remainingTiles===undefined?current.bestRemainingTiles:(current.bestRemainingTiles===null?item.tieBreak.remainingTiles:Math.min(current.bestRemainingTiles,item.tieBreak.remainingTiles))};}store.history.push(clone(item));store.processed[item.key]={fingerprint:'history-rebuild',receipt:{key:item.key,seasonId:item.seasonId,formulaVersion:item.formulaVersion,mode:item.mode,matchId:item.matchId,deltas:clone(item.deltas),antiFarmSignals:clone(item.antiFarmSignals??[])}};}return store;}
export function auditRankingStore(store){const rebuilt=rebuildRankingStore(store.history??[]);const modes=['solo','trio','pvp'];const keys=new Set([...Object.keys(store.standings??{}),...Object.keys(rebuilt.standings)]);const divergences=[];for(const key of keys){const split=key.lastIndexOf(':');const seasonId=key.slice(0,split),mode=key.slice(split+1);if(!modes.includes(mode))continue;const actual=getRankingStandings(store,{seasonId,mode});const expected=getRankingStandings(rebuilt,{seasonId,mode});if(stable(actual)!==stable(expected))divergences.push({key,actual,expected});}return {ok:divergences.length===0,divergences,rebuilt};}
