import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';

const root=process.cwd();
const sourceExt=new Set(['.html','.js','.mjs','.css']);
const runtimeExt=new Set(['.html','.js','.mjs','.css','.svg','.webp','.png','.json','.txt']);
const ignoreDirs=new Set(['.git','node_modules']);
const canonicalRoots=new Set(['index.html','entrada.html','login.html','cadastro.html','perfil.html','avatar.html','amigos.html','conversas.html','notificacoes.html','comunidades.html','salas.html','sala.html','jogos.html','historico.html','momentos.html','zuno-stack.html','manifest.json','sw.js','nav.js','icon-192.png','icon-512.png','zuno-app-icon.svg']);
function walk(dir,rel=''){const out=[];for(const ent of fs.readdirSync(dir,{withFileTypes:true})){if(ignoreDirs.has(ent.name))continue;const r=path.posix.join(rel,ent.name),abs=path.join(dir,ent.name);if(ent.isDirectory())out.push(...walk(abs,r));else out.push(r)}return out}
const files=walk(root),fileSet=new Set(files),inbound=new Map(files.map(f=>[f,new Set()])),broken=new Set(),versionedRefs=new Set(),rpcCalls=new Map();
function norm(from,raw){let value=String(raw||'').trim();if(!value||/^(?:https?:|data:|mailto:|javascript:|#)/i.test(value))return null;if(/[|*\\{}\[\]]/.test(value)||value.includes('${')||value.includes('`'))return null;value=value.split('#',1)[0].split('?',1)[0];if(!value)return null;if(value.startsWith('/'))value=value.slice(1);else value=path.posix.normalize(path.posix.join(path.posix.dirname(from),value));if(value.startsWith('../'))return null;return value.replace(/^\.\//,'')}
const quoted=/["'`]((?:\.?\.?\/|\/)?[^"'`\s<>]+\.(?:html|js|mjs|css|svg|webp|png|json|txt)(?:\?[^"'`\s<>]*)?)["'`]/gi;
const cssUrl=/url\(\s*["']?([^"')\s]+)["']?\s*\)/gi;
const loaders=[/(?:src|href)\s*=\s*["']([^"']+)["']/gi,/(?:location\.(?:href|replace)|window\.location\.href)\s*(?:=|\()\s*["']([^"']+)["']/gi,/new\s+URL\(\s*["']([^"']+)["']/gi,/(?:\.src|\.href)\s*=\s*["']([^"']+)["']/gi,/(?:fetch|import)\(\s*["']([^"']+)["']/gi,/\b(?:js|css|load)\(\s*["'][^"']*["']\s*,\s*["']([^"']+)["']/gi,cssUrl];
for(const f of files){const ext=path.extname(f).toLowerCase();if(!sourceExt.has(ext)||f.startsWith('.github/')||f.startsWith('scripts/'))continue;let text='';try{text=fs.readFileSync(path.join(root,f),'utf8')}catch{continue}for(const re of [quoted,cssUrl]){re.lastIndex=0;let m;while((m=re.exec(text))){const raw=m[1],target=norm(f,raw);if(!target)continue;if(/\?v=\d+/i.test(raw))versionedRefs.add(`${f} -> ${raw}`);if(fileSet.has(target)&&f!=='sw.js')inbound.get(target)?.add(f)}}for(const re of loaders){re.lastIndex=0;let m;while((m=re.exec(text))){const target=norm(f,m[1]);if(target&&runtimeExt.has(path.extname(target).toLowerCase())&&!fileSet.has(target))broken.add(`${f} -> ${target}`)}}const rpc=/\.rpc\(\s*["']([^"']+)["']/g;let rm;while((rm=rpc.exec(text))){if(!rpcCalls.has(rm[1]))rpcCalls.set(rm[1],new Set());rpcCalls.get(rm[1]).add(f)}}
const rootRuntime=files.filter(f=>!f.includes('/')&&runtimeExt.has(path.extname(f).toLowerCase()));
const orphanRoot=rootRuntime.filter(f=>!canonicalRoots.has(f)&&(inbound.get(f)?.size||0)===0).sort();
const hashes=new Map();for(const f of files){const ext=path.extname(f).toLowerCase();if(!runtimeExt.has(ext))continue;const buf=fs.readFileSync(path.join(root,f));if(!buf.length)continue;const h=crypto.createHash('sha256').update(buf).digest('hex');if(!hashes.has(h))hashes.set(h,[]);hashes.get(h).push(f)}
const exactDup=[...hashes.values()].filter(v=>v.length>1).sort((a,b)=>b.length-a.length);
const families=new Map();for(const f of rootRuntime){const m=f.match(/^(.*?)(?:[-_.]v)(\d+)(\.[^.]+)$/i);if(!m)continue;const key=(m[1]+m[3]).toLowerCase();if(!families.has(key))families.set(key,[]);families.get(key).push({file:f,v:Number(m[2])})}const multi=[...families.values()].filter(v=>v.length>1).map(v=>v.sort((a,b)=>a.v-b.v));
const sw=fs.readFileSync('sw.js','utf8'),nav=fs.readFileSync('nav.js','utf8'),current=fs.readFileSync('zuno-current.js','utf8');const navV=nav.match(/const\s+V=['"](\d+)['"]/)?.[1],swV=sw.match(/CACHE_NAME\s*=\s*["']zunoplay-v(\d+)["']/)?.[1],curV=current.match(/const\s+VERSION=['"](\d+)['"]/)?.[1];const stale=[...versionedRefs].filter(x=>x.startsWith('sw.js -> ')).filter(x=>{const m=x.match(/\?v=(\d+)/);return m&&swV&&m[1]!==swV}).sort();
function section(title,values){console.log(`\n=== ${title} (${values.length}) ===`);if(!values.length)console.log('none');else for(const v of values)console.log(Array.isArray(v)?v.map(x=>typeof x==='string'?x:x.file).join(' | '):v)}
console.log(`Files scanned: ${files.length}`);console.log(`Frontend versions: nav=${navV||'?'} sw=${swV||'?'} current=${curV||'?'}`);section('BROKEN ACTIVE LOCAL REFERENCES',[...broken].sort());section('ROOT RUNTIME FILES WITH NO ACTIVE INBOUND REFERENCE',orphanRoot);section('EXACT DUPLICATE FILE CONTENT',exactDup);section('MULTIPLE VERSION FAMILIES',multi);section('STALE ?v= REFERENCES IN SERVICE WORKER',stale);section('FRONTEND RPC CALLS',[...rpcCalls.entries()].sort().map(([name,refs])=>`${name}: ${[...refs].sort().join(', ')}`));
const generationMismatch=![navV,swV,curV].every(Boolean)||new Set([navV,swV,curV]).size!==1;
if(generationMismatch||broken.size||stale.length||orphanRoot.length){if(orphanRoot.length)console.error('\nRuntime órfão é falha de CI: remova o arquivo ou referencie-o explicitamente.');process.exitCode=2}
