create table if not exists public.friend_request_events (
  id bigint generated by default as identity primary key,
  request_id uuid,
  sender_id uuid not null references public.profiles(id) on delete cascade,
  receiver_id uuid not null references public.profiles(id) on delete cascade,
  event_type text not null check (event_type in ('created','accepted','rejected','cancelled','deleted')),
  status text,
  created_at timestamptz not null default now()
);

create index if not exists friend_request_events_sender_idx on public.friend_request_events(sender_id, created_at desc);
create index if not exists friend_request_events_receiver_idx on public.friend_request_events(receiver_id, created_at desc);

alter table public.friend_request_events enable row level security;

drop policy if exists friend_request_events_select_participants on public.friend_request_events;
create policy friend_request_events_select_participants
on public.friend_request_events
for select
to authenticated
using (auth.uid() = sender_id or auth.uid() = receiver_id);

revoke all on public.friend_request_events from anon;
grant select on public.friend_request_events to authenticated;

create or replace function public.emit_friend_request_event()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if tg_op = 'INSERT' then
    insert into public.friend_request_events(request_id,sender_id,receiver_id,event_type,status)
    values (new.id,new.sender_id,new.receiver_id,'created',new.status);
    return new;
  elsif tg_op = 'UPDATE' then
    if new.status is distinct from old.status then
      insert into public.friend_request_events(request_id,sender_id,receiver_id,event_type,status)
      values (
        new.id,new.sender_id,new.receiver_id,
        case new.status when 'accepted' then 'accepted' when 'rejected' then 'rejected' else 'created' end,
        new.status
      );
    end if;
    return new;
  elsif tg_op = 'DELETE' then
    insert into public.friend_request_events(request_id,sender_id,receiver_id,event_type,status)
    values (old.id,old.sender_id,old.receiver_id,case when old.status='pending' then 'cancelled' else 'deleted' end,old.status);
    return old;
  end if;
  return null;
end;
$$;

drop trigger if exists trg_friend_request_events on public.friend_requests;
create trigger trg_friend_request_events
after insert or update or delete on public.friend_requests
for each row execute function public.emit_friend_request_event();

create or replace function public.send_friend_request(target_user_id uuid)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  me uuid := auth.uid();
  req_id uuid;
begin
  if me is null then raise exception 'not_authenticated'; end if;
  if target_user_id is null or target_user_id = me then raise exception 'invalid_target'; end if;
  if not exists(select 1 from public.profiles where id=target_user_id) then raise exception 'target_not_found'; end if;
  if exists(select 1 from public.friendships where (user_id=me and friend_id=target_user_id) or (user_id=target_user_id and friend_id=me)) then
    raise exception 'already_friends';
  end if;
  if exists(select 1 from public.friend_requests where status='pending' and ((sender_id=me and receiver_id=target_user_id) or (sender_id=target_user_id and receiver_id=me))) then
    raise exception 'request_pending';
  end if;
  insert into public.friend_requests(sender_id,receiver_id,status)
  values(me,target_user_id,'pending') returning id into req_id;
  return req_id;
end;
$$;

create or replace function public.respond_friend_request(request_id uuid, decision text)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  me uuid := auth.uid();
  r public.friend_requests%rowtype;
begin
  if me is null then raise exception 'not_authenticated'; end if;
  if decision not in ('accepted','rejected') then raise exception 'invalid_decision'; end if;
  select * into r from public.friend_requests where id=request_id for update;
  if not found then raise exception 'request_not_found'; end if;
  if r.receiver_id <> me then raise exception 'not_receiver'; end if;
  if r.status <> 'pending' then raise exception 'request_not_pending'; end if;

  update public.friend_requests set status=decision where id=r.id;

  if decision='accepted' then
    begin
      insert into public.friendships(user_id,friend_id)
      values(r.sender_id,r.receiver_id);
    exception when unique_violation then
      null;
    end;
  end if;
  return true;
end;
$$;

create or replace function public.cancel_friend_request(request_id uuid)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  me uuid := auth.uid();
  r public.friend_requests%rowtype;
begin
  if me is null then raise exception 'not_authenticated'; end if;
  select * into r from public.friend_requests where id=request_id for update;
  if not found then raise exception 'request_not_found'; end if;
  if r.sender_id <> me then raise exception 'not_sender'; end if;
  if r.status <> 'pending' then raise exception 'request_not_pending'; end if;
  delete from public.friend_requests where id=r.id;
  return true;
end;
$$;

revoke all on function public.send_friend_request(uuid) from public, anon;
revoke all on function public.respond_friend_request(uuid,text) from public, anon;
revoke all on function public.cancel_friend_request(uuid) from public, anon;
grant execute on function public.send_friend_request(uuid) to authenticated;
grant execute on function public.respond_friend_request(uuid,text) to authenticated;
grant execute on function public.cancel_friend_request(uuid) to authenticated;

do $$
begin
  if not exists (
    select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='friend_request_events'
  ) then
    alter publication supabase_realtime add table public.friend_request_events;
  end if;
end $$;
