create table public.xp_rules (
  source text primary key,
  min_xp integer not null check (min_xp >= 0),
  max_xp integer not null check (max_xp >= min_xp),
  default_xp integer not null check (default_xp between min_xp and max_xp),
  daily_limit integer check (daily_limit is null or daily_limit > 0),
  lifetime_limit integer check (lifetime_limit is null or lifetime_limit > 0),
  enabled boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

insert into public.xp_rules(source,min_xp,max_xp,default_xp,daily_limit,lifetime_limit,enabled) values
 ('game_completed',20,20,20,null,null,true),
 ('game_win_bonus',10,10,10,null,null,true),
 ('first_win_daily',30,30,30,1,null,true),
 ('daily_mission',50,100,50,null,null,true),
 ('weekly_mission',250,500,250,null,null,true),
 ('achievement_common',50,50,50,null,null,true),
 ('achievement_rare',100,500,100,null,null,true),
 ('onboarding_completed',100,100,100,null,1,true),
 ('special_event',0,0,0,null,null,false);

create table public.user_xp_progression (
  user_id uuid primary key references public.profiles(id) on delete cascade,
  total_xp bigint not null default 0 check (total_xp >= 0),
  level integer not null default 1 check (level >= 1),
  updated_at timestamptz not null default now()
);

create table public.xp_transactions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  amount integer not null check (amount > 0),
  source text not null references public.xp_rules(source),
  source_event_id text not null,
  idempotency_key text not null unique,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  unique (user_id, source, source_event_id)
);

create index xp_transactions_user_created_idx on public.xp_transactions(user_id, created_at desc);
create index xp_transactions_source_created_idx on public.xp_transactions(source, created_at desc);

create or replace function public.zuno_global_level_for_xp(p_xp bigint)
returns integer
language sql
immutable
set search_path = ''
as $$
  select greatest(1, floor((-1 + sqrt(9 + (4 * greatest(p_xp,0)::numeric / 25))) / 2)::integer);
$$;

create or replace function public.zuno_global_xp_for_level(p_level integer)
returns bigint
language sql
immutable
set search_path = ''
as $$
  select case when p_level <= 1 then 0::bigint else (25::bigint * (p_level - 1) * (p_level + 2)) end;
$$;

create schema if not exists private;

create or replace function private.zuno_award_global_xp(
  p_user uuid,
  p_source text,
  p_source_event_id text,
  p_amount integer default null,
  p_metadata jsonb default '{}'::jsonb
)
returns table(total_xp bigint, level integer, awarded_xp integer)
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_rule public.xp_rules%rowtype;
  v_amount integer;
  v_daily_count integer;
  v_lifetime_count integer;
  v_total bigint;
  v_level integer;
begin
  if p_user is null or p_source is null or length(trim(p_source_event_id)) = 0 then
    raise exception 'invalid_xp_event' using errcode='22023';
  end if;

  if not exists (select 1 from public.profiles where id = p_user) then
    raise exception 'profile_not_found' using errcode='P0002';
  end if;

  select * into v_rule from public.xp_rules where source = p_source and enabled = true;
  if not found then
    raise exception 'xp_source_disabled_or_unknown' using errcode='22023';
  end if;

  v_amount := coalesce(p_amount, v_rule.default_xp);
  if v_amount < v_rule.min_xp or v_amount > v_rule.max_xp or v_amount <= 0 then
    raise exception 'xp_amount_out_of_rule' using errcode='22023';
  end if;

  if v_rule.daily_limit is not null then
    select count(*) into v_daily_count
    from public.xp_transactions
    where user_id=p_user and source=p_source and created_at >= date_trunc('day', now());
    if v_daily_count >= v_rule.daily_limit then
      raise exception 'xp_daily_limit_reached' using errcode='22023';
    end if;
  end if;

  if v_rule.lifetime_limit is not null then
    select count(*) into v_lifetime_count
    from public.xp_transactions
    where user_id=p_user and source=p_source;
    if v_lifetime_count >= v_rule.lifetime_limit then
      raise exception 'xp_lifetime_limit_reached' using errcode='22023';
    end if;
  end if;

  insert into public.xp_transactions(user_id, amount, source, source_event_id, idempotency_key, metadata)
  values(p_user, v_amount, p_source, p_source_event_id, p_user::text || ':' || p_source || ':' || p_source_event_id, coalesce(p_metadata,'{}'::jsonb));

  insert into public.user_xp_progression(user_id,total_xp,level)
  values(p_user,v_amount,public.zuno_global_level_for_xp(v_amount))
  on conflict(user_id) do update set
    total_xp = public.user_xp_progression.total_xp + excluded.total_xp,
    level = public.zuno_global_level_for_xp(public.user_xp_progression.total_xp + excluded.total_xp),
    updated_at = now()
  returning user_xp_progression.total_xp,user_xp_progression.level into v_total,v_level;

  return query select v_total,v_level,v_amount;
end;
$$;

alter table public.xp_rules enable row level security;
alter table public.user_xp_progression enable row level security;
alter table public.xp_transactions enable row level security;

create policy "users_read_own_xp_progression" on public.user_xp_progression
for select to authenticated
using ((select auth.uid()) = user_id);

create policy "users_read_own_xp_transactions" on public.xp_transactions
for select to authenticated
using ((select auth.uid()) = user_id);

revoke all on public.xp_rules from anon, authenticated;
revoke insert, update, delete on public.user_xp_progression from anon, authenticated;
revoke insert, update, delete on public.xp_transactions from anon, authenticated;
revoke all on function private.zuno_award_global_xp(uuid,text,text,integer,jsonb) from public, anon, authenticated;
grant usage on schema private to service_role;
grant execute on function private.zuno_award_global_xp(uuid,text,text,integer,jsonb) to service_role;

grant select on public.user_xp_progression to authenticated;
grant select on public.xp_transactions to authenticated;
grant execute on function public.zuno_global_level_for_xp(bigint) to authenticated;
grant execute on function public.zuno_global_xp_for_level(integer) to authenticated;

