-- 1) Private messages: sender must be the authenticated user and both users must be friends.
drop policy if exists messages_insert on public.messages;
create policy messages_insert
on public.messages
for insert
to authenticated
with check (
  sender_id = (select auth.uid())
  and sender_id <> receiver_id
  and exists (
    select 1
    from public.friendships f
    where (f.user_id = sender_id and f.friend_id = receiver_id)
       or (f.user_id = receiver_id and f.friend_id = sender_id)
  )
);

-- 2) Room messages: only an authenticated member of that room can send.
drop policy if exists "Usuários podem enviar mensagens" on public.room_messages;
create policy "Membros podem enviar mensagens"
on public.room_messages
for insert
to authenticated
with check (
  user_id = (select auth.uid())
  and exists (
    select 1
    from public.room_members rm
    where rm.room_id = room_messages.room_id
      and rm.user_id = (select auth.uid())
  )
);

-- 3) Notifications are server-generated by SECURITY DEFINER triggers; clients only read/update their own.
drop policy if exists "Users can insert notifications" on public.notifications;
revoke insert on table public.notifications from authenticated;

-- 4) Profiles: authenticated users may edit only the fields the current app legitimately owns.
-- Keep level writable for the current client-side Desafio Zuno progression; protect coins and identity/system fields.
revoke update on table public.profiles from authenticated;
grant update (username, avatar_url, bio, level) on table public.profiles to authenticated;

-- Profiles are created by the auth trigger, not directly by the client.
revoke insert on table public.profiles from authenticated;

-- 5) The chat uses this RPC; expose exactly this safe function to authenticated users.
revoke all on function public.mark_message_notifications_read(uuid) from public, anon;
grant execute on function public.mark_message_notifications_read(uuid) to authenticated;
