create table if not exists public.zunoplay_data_archive (
  id bigint generated by default as identity primary key,
  entity_type text not null,
  original_id text,
  payload jsonb not null,
  archived_at timestamptz not null default now()
);
alter table public.zunoplay_data_archive enable row level security;
revoke all on public.zunoplay_data_archive from anon, authenticated;

insert into public.zunoplay_data_archive(entity_type,original_id,payload)
select 'friend_request', fr.id::text, to_jsonb(fr)
from public.friend_requests fr
where exists (
  select 1 from public.profiles p
  left join auth.users u on u.id=p.id
  where u.id is null and (p.id=fr.sender_id or p.id=fr.receiver_id)
);

insert into public.zunoplay_data_archive(entity_type,original_id,payload)
select 'profile', p.id::text, to_jsonb(p)
from public.profiles p
left join auth.users u on u.id=p.id
where u.id is null;

delete from public.friend_requests fr
where exists (
  select 1 from public.profiles p
  left join auth.users u on u.id=p.id
  where u.id is null and (p.id=fr.sender_id or p.id=fr.receiver_id)
);

delete from public.profiles p
where not exists (select 1 from auth.users u where u.id=p.id);

create unique index if not exists profiles_username_lower_unique
on public.profiles (lower(btrim(username)))
where username is not null and btrim(username) <> '';

