create table if not exists public.zuno_stack_game_events (
  id bigint generated by default as identity primary key,
  room_id uuid not null references public.rooms(id) on delete cascade,
  action_id text not null,
  event_type text not null,
  payload jsonb not null default '{}'::jsonb,
  actor_id uuid null references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  unique(room_id, action_id)
);

create index if not exists zuno_stack_game_events_room_created_idx on public.zuno_stack_game_events(room_id, created_at desc);
create index if not exists zuno_stack_game_events_room_type_idx on public.zuno_stack_game_events(room_id, event_type);

alter table public.zuno_stack_game_events enable row level security;

drop policy if exists zuno_stack_events_select_members on public.zuno_stack_game_events;
create policy zuno_stack_events_select_members on public.zuno_stack_game_events
for select to authenticated
using (
  exists(select 1 from public.room_members rm where rm.room_id=zuno_stack_game_events.room_id and rm.user_id=(select auth.uid()))
  or exists(select 1 from public.rooms r where r.id=zuno_stack_game_events.room_id and r.owner_id=(select auth.uid()))
);

drop policy if exists zuno_stack_events_insert_members on public.zuno_stack_game_events;
create policy zuno_stack_events_insert_members on public.zuno_stack_game_events
for insert to authenticated
with check (
  actor_id=(select auth.uid()) and (
    exists(select 1 from public.room_members rm where rm.room_id=zuno_stack_game_events.room_id and rm.user_id=(select auth.uid()))
    or exists(select 1 from public.rooms r where r.id=zuno_stack_game_events.room_id and r.owner_id=(select auth.uid()))
  )
);

create or replace function public.zuno_stack_log_event(p_room_id uuid,p_action_id text,p_event_type text,p_payload jsonb default '{}'::jsonb)
returns bigint
language plpgsql
security invoker
set search_path=public
as $$
declare v_id bigint;
begin
  insert into public.zuno_stack_game_events(room_id,action_id,event_type,payload,actor_id)
  values(p_room_id,p_action_id,left(p_event_type,80),coalesce(p_payload,'{}'::jsonb),(select auth.uid()))
  on conflict(room_id,action_id) do nothing
  returning id into v_id;
  return v_id;
end;
$$;
revoke all on function public.zuno_stack_log_event(uuid,text,text,jsonb) from public;
grant execute on function public.zuno_stack_log_event(uuid,text,text,jsonb) to authenticated;
