update public.notifications set category = case type when 'friend_request' then 'social' when 'friend_accepted' then 'social' when 'message' then 'social' when 'room_invite' then 'rooms' when 'room_activity' then 'rooms' when 'game_invite' then 'games' when 'challenge' then 'games' when 'achievement' then 'rewards' when 'reward' then 'rewards' when 'coins' then 'rewards' when 'avatar' then 'rewards' else coalesce(nullif(category,''),'system') end where category is null or category='system';
update public.notifications set action_url = case type when 'friend_request' then 'amigos.html' when 'friend_accepted' then 'amigos.html' when 'message' then 'conversas.html' when 'room_invite' then 'salas.html' when 'room_activity' then 'salas.html' when 'game_invite' then 'jogos.html' when 'challenge' then 'jogos.html' when 'achievement' then 'historico.html' when 'reward' then 'historico.html' when 'coins' then 'historico.html' when 'avatar' then 'avatar.html' else 'index.html' end where action_url is null;
create or replace function public.zuno_notification_defaults() returns trigger language plpgsql set search_path=public as $$ begin
  if new.category is null or new.category='' or new.category='system' then new.category := case new.type when 'friend_request' then 'social' when 'friend_accepted' then 'social' when 'message' then 'social' when 'room_invite' then 'rooms' when 'room_activity' then 'rooms' when 'game_invite' then 'games' when 'challenge' then 'games' when 'achievement' then 'rewards' when 'reward' then 'rewards' when 'coins' then 'rewards' when 'avatar' then 'rewards' else 'system' end; end if;
  if new.action_url is null then new.action_url := case new.type when 'friend_request' then 'amigos.html' when 'friend_accepted' then 'amigos.html' when 'message' then 'conversas.html' when 'room_invite' then 'salas.html' when 'room_activity' then 'salas.html' when 'game_invite' then 'jogos.html' when 'challenge' then 'jogos.html' when 'achievement' then 'historico.html' when 'reward' then 'historico.html' when 'coins' then 'historico.html' when 'avatar' then 'avatar.html' else 'index.html' end; end if;
  return new;
end $$;
drop trigger if exists zuno_notification_defaults_trigger on public.notifications;
create trigger zuno_notification_defaults_trigger before insert or update of type,category,action_url on public.notifications for each row execute function public.zuno_notification_defaults();
